Repository playframework/playframework, pull requests merged in 2018-08, with the labels that each got.

#8549 Make CSRF filter consider either the cookie or the session, but not both
  framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
  framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
Labels: status:needs-backport

#8550 More logs during Play's evolution
  framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
Labels: enhancement, status:needs-backport, topic:evolutions

#8551 Lazily create SSLEngineProvider
  framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
Labels: enhancement, status:needs-forwardport

#8539 Deprecate Http.Response
  documentation/manual/releases/release27/migration27/Migration27.md
  framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
  framework/src/play/src/main/java/play/mvc/Controller.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/java/play/mvc/Result.java
  framework/src/play/src/main/java/play/mvc/StatusHeader.java
Labels: type:deprecated-feature

#8547 SBTSubProjects.md: fix contradiction about per-project build.sbt
  documentation/manual/working/commonGuide/build/SBTSubProjects.md
Labels: status:needs-backport, topic:documentation, topic:sbt

#8567 Bump play-enhancer plugin version in document.
  documentation/manual/working/commonGuide/build/code/enhancer.sbt
Labels: status:needs-backport, topic:documentation

#8571 Update dependencies
  framework/project/Dependencies.scala
  framework/project/plugins.sbt
Labels: type:updates

#8577 Update Play JSON to 2.6.10
  framework/project/Dependencies.scala
Labels: status:needs-backport, type:updates

#8578 Update Play-WS to version 2.0.0-M3
  framework/project/Dependencies.scala
Labels: type:updates

#8583 Make CoordinatedShutdoownSupport public but internal
  framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
  framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
  framework/src/play/src/main/scala/play/api/Application.scala
  framework/src/play/src/main/scala/play/api/internal/libs/concurrent/CoordinatedShutdownSupport.scala
  framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
  framework/src/play/src/test/scala/play/api/libs/concurrent/ActorSystemProviderSpec.scala
Labels: enhancement, topic:scala-api

#8589 Akka 2.5.16 Security Patch
  framework/project/Dependencies.scala
Labels: status:needs-backport
