Repository playframework/playframework, pull requests merged in 2018-11, with the labels that each got.

#8724 Deprecate more methods that depend on Http.Context
  documentation/manual/working/commonGuide/assets/code/assets/controllers/JavaRangeRequestController.java
  documentation/manual/working/javaGuide/advanced/routing/code/javaguide.binder.routes
  documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/controllers/Application.java
  documentation/manual/working/javaGuide/code/MockJavaAction.scala
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaRouting.scala
  documentation/manual/working/javaGuide/main/ws/code/javaguide.ws.routes
  documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/OpenIDController.java
  framework/src/play-guice/src/test/scala/play/api/http/HttpErrorHandlerSpec.scala
  framework/src/play-java/src/main/java/play/inject/BuiltInModule.java
  framework/src/play-openid/src/main/java/play/libs/openid/DefaultOpenIdClient.java
  framework/src/play-openid/src/main/java/play/libs/openid/OpenIdClient.java
  framework/src/play/src/main/java/play/mvc/FileMimeTypes.java
  framework/src/play/src/main/java/play/mvc/RangeResults.java
  framework/src/play/src/main/java/play/mvc/Results.java
  framework/src/play/src/main/java/play/mvc/StaticFileMimeTypes.java
  framework/src/play/src/main/java/play/mvc/StatusHeader.java
  framework/src/play/src/main/java/play/routing/JavaScriptReverseRouter.java
  framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala
  framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala
  framework/src/play/src/main/scala/play/mvc/FileMimeTypesModule.scala
Labels: in progress

#8685 Fix AssetsBuilder.java
  documentation/manual/working/commonGuide/build/code/javaguide/common/build/controllers/AssetsBuilder.java
Labels: status:needs-backport, topic:documentation

#8753 Deprecate Java Form methods that depend on Http.Context
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
  documentation/manual/working/javaGuide/main/ws/code/javaguide.ws.routes
  documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/OpenIDController.java
  framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java
  framework/src/play-java-forms/src/main/java/play/data/Form.java
  framework/src/play-java-forms/src/main/java/play/data/validation/Constraints.java
  framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java
Labels: in progress

#8752 Update play-file-watch and sbt-web
  framework/project/Dependencies.scala
Labels: in progress, type:updates

#8754 Build stages
  .travis.yml
  framework/bin/test-docs
  framework/bin/validate-docs
  framework/project/plugins.sbt
  framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
  framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
Labels: in progress

#8755 Deprecate ctx.args and add attrs to validation payload instead
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
  framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java
  framework/src/play-java-forms/src/main/java/play/data/Form.java
  framework/src/play-java-forms/src/main/java/play/data/validation/Constraints.java
  framework/src/play/src/main/java/play/mvc/Http.java
Labels: in progress

#8762 Add some missing deprecated annotations and docs
  framework/src/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
  framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
  framework/src/play-ws/src/main/java/play/libs/ws/WSRequest.java
  framework/src/play/src/main/java/play/DefaultApplication.java
  framework/src/play/src/main/java/play/server/ApplicationProvider.java
Labels: review

#8756 Deprecate remaining methods that depend on Http.Context
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/csp/CSPReportController.java
  documentation/manual/working/commonGuide/server/code/SomeJavaController.java
  documentation/manual/working/javaGuide/advanced/routing/code/javaEmbeddedRouter.scala.html
  documentation/manual/working/javaGuide/code/MockJavaAction.scala
  documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaWebSockets.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaCsrf.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaFormHelpers.scala
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/csrf.scala.html
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/fullform.scala.html
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/helpers.scala.html
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/view.scala.html
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/withFieldConstructor.scala.html
  documentation/manual/working/javaGuide/main/http/code/javaguide.http.routing.relative.routes
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActions.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActionsComposition.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaBodyParsers.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaContentNegotiation.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/routing/relative/controllers/Relative.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/views/index.scala.html
  documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/JavaI18N.java
  documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/explicitjavatemplate.scala.html
  documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/helloscalatemplate.scala.html
  documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/hellotemplate.scala.html
  documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/indextemplate.scala.html
  documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java
  documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaMarkerController.java
  documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaTracerController.java
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
  documentation/manual/working/javaGuide/main/ws/code/javaguide.ws.routes
  documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/OpenIDController.java
  documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/Twitter.java
  documentation/manual/working/javaGuide/main/xml/code/javaguide/xml/JavaXmlRequests.java
  framework/project/BuildSettings.scala
  framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
  framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java
  framework/src/play-test/src/main/java/play/test/Helpers.java
  framework/src/play/src/main/java/play/i18n/Messages.java
  framework/src/play/src/main/java/play/mvc/Controller.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/scala/play/api/i18n/Messages.scala
  framework/src/play/src/main/scala/play/api/mvc/Request.scala
  framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala
  framework/src/play/src/main/scala/play/core/j/HttpExecutionContext.scala
  framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
  framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
Labels: in progress

#8761 Better build output
  documentation/build.sbt
  framework/bin/scriptLib
  framework/bin/test-docs
  framework/bin/test-sbt-plugins-0_13
  framework/bin/test-sbt-plugins-1_0
  framework/bin/validate-docs
  framework/bin/validate-microbenchmarks
  framework/project/BuildSettings.scala
  framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala
  framework/src/play-integration-test/src/test/resources/logback.xml
  framework/src/play-integration-test/src/test/scala/play/it/api/SecretConfigurationParserSpec.scala
Labels: review

#8767 Minor improvements to http context
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java
  framework/src/play/src/main/java/play/mvc/Http.java
Labels: in progress

#8769 New APIS to avoid Http.Context when using RoutingDsl
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/FiltersTest.java
  documentation/manual/working/javaGuide/advanced/embedding/code/javaguide/advanced/embedding/JavaEmbeddingPlay.java
  documentation/manual/working/javaGuide/advanced/routing/JavaRoutingDsl.md
  documentation/manual/working/javaGuide/advanced/routing/code/AppLoader.java
  documentation/manual/working/javaGuide/advanced/routing/code/GuiceRouterProvider.java
  documentation/manual/working/javaGuide/advanced/routing/code/javaguide/advanced/routing/JavaRoutingDsl.java
  documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/components/CompileTimeDependencyInjection.java
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/GitHubClientTest.java
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/JavaTestingWebServiceClients.java
  framework/src/play-integration-test/src/test/java/play/routing/AbstractRoutingDslTest.java
  framework/src/play-java/src/main/java/play/routing/RequestFunctions.java
  framework/src/play-java/src/main/java/play/routing/RoutingDsl.java
  framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
  framework/src/play/src/main/java/play/libs/F.java
  framework/src/play/src/main/scala/play/api/mvc/Request.scala
Labels: in progress

#8774 [master]: Honor play settings on AkkaHttpServer for client auth in SSL
  framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
Labels: in progress

#8777 Handle non-upgrade requests for Websockt with a 426 status
  framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
  framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
Labels: in progress

#8772 Handle null content type as if the header was not set
  framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
  framework/src/play/src/main/java/play/http/HttpEntity.java
  framework/src/play/src/main/scala/play/api/http/HttpEntity.scala
Labels: status:needs-backport

#8771 Document how to use a custom reason with coordinated shutdown
  documentation/manual/releases/release27/migration27/Migration27.md
Labels: in progress

#8764 Add missing methods to Java compile-time dependency injection support
  framework/src/play-test/src/main/scala/play/api/test/Selenium.scala
  framework/src/play/src/main/java/play/ApplicationLoader.java
  framework/src/play/src/main/java/play/BuiltInComponents.java
  framework/src/play/src/main/java/play/BuiltInComponentsFromContext.java
  framework/src/play/src/main/java/play/Logger.java
Labels: review

#8758 fixed broken link (issue #8730)
  documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
Labels: status:needs-forwardport, topic:documentation

#8768 Preparations to make Java Session and Flash immutable
  documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaWebSockets.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/views/index.scala.html
  documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/Twitter.java
  framework/project/BuildSettings.scala
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/java/play/mvc/Result.java
  framework/src/play/src/main/java/play/mvc/Security.java
  framework/src/play/src/main/scala/play/api/mvc/Flash.scala
  framework/src/play/src/main/scala/play/api/mvc/Session.scala
Labels: in progress

#8766 Disable Http.Context and JPA thread local via system property
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  framework/project/BuildSettings.scala
  framework/src/play-java-forms/src/main/java/play/data/Form.java
  framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
  framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAComponents.java
  framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAEntityManagerContext.java
  framework/src/play-java-jpa/src/main/resources/reference.conf
  framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
  framework/src/play/src/main/java/play/mvc/Action.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/resources/reference.conf
  framework/src/play/src/main/scala/play/core/j/HttpExecutionContext.scala
  framework/src/play/src/main/scala/play/core/j/JavaAction.scala
  framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
  framework/src/play/src/main/scala/play/core/routing/HandlerInvoker.scala
Labels: in progress

#8785 Add note for `play.ws.ssl` prefix
  documentation/manual/working/commonGuide/configuration/WsSSL.md
Labels: in progress

#8786 upgrade deps for 2.7.0-RC1 release
  documentation/manual/releases/release27/Highlights27.md
  framework/bin/test-scala-212
  framework/build.sbt
  framework/project/BuildSettings.scala
  framework/project/Dependencies.scala
  framework/project/plugins.sbt
Labels: in progress

#8793 Migration notes for PlayMagicForJava implicits deprecations
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  documentation/manual/working/javaGuide/advanced/routing/code/javaEmbeddedRouter.scala.html
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/csrf.scala.html
  framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
Labels: in progress

#8796 Fix problem with publishLocal
  .travis.yml
  framework/bin/publish-local
  framework/src/play/src/main/java/play/BuiltInComponents.java
Labels: in progress

#8799 Minor travis improvements
  framework/bin/publish-local
  framework/bin/test-scala-212
Labels: in progress

#8801 Pass ctx.args between actions in chain when thread-local is disabled
  framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionOrderTest.java
  framework/src/play-integration-test/src/test/java/play/it/http/PreserveContextArgsController.java
  framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala
  framework/src/play/src/main/java/play/mvc/Action.java
Labels: review

#8809 LoggerContext.reset should not remove just added listeners
  framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
Labels: in progress

#8810 Small fix/cleanup for play.Logger
  framework/src/play/src/main/java/play/Logger.java
Labels: in progress

#8813 Don't deprecate whole play.Logger, but only the static Logger singleton
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/User.scala
  documentation/manual/working/scalaGuide/main/application/code/EssentialFilter.scala
  documentation/manual/working/scalaGuide/main/application/code/FiltersRouting.scala
  documentation/manual/working/scalaGuide/main/application/code/ScalaHttpFilters.scala
  documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala
  documentation/manual/working/scalaGuide/main/ws/code/ScalaOpenIdSpec.scala
  framework/src/play/src/main/java/play/Logger.java
  framework/src/play/src/main/scala/play/api/Logger.scala
Labels: in progress

#8816 Update Logger documentation and add Logging trait
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/working/javaGuide/main/logging/JavaLogging.md
  documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaLogging.java
  documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/User.scala
  documentation/manual/working/scalaGuide/main/application/code/EssentialFilter.scala
  documentation/manual/working/scalaGuide/main/application/code/FiltersRouting.scala
  documentation/manual/working/scalaGuide/main/application/code/ScalaHttpFilters.scala
  documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala
  documentation/manual/working/scalaGuide/main/logging/ScalaLogging.md
  documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala
  documentation/manual/working/scalaGuide/main/ws/code/ScalaOpenIdSpec.scala
  framework/src/play/src/main/scala/play/api/Logger.scala
Labels: in progress

#8819 Update sbt native packager and js engine
  documentation/manual/working/commonGuide/production/Deploying.md
  framework/project/Dependencies.scala
  framework/project/plugins.sbt
Labels: in progress, status:needs-backport, type:updates

#8825 Bind WebCommands as a Singleton since it has mutable state
  framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala
  framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceApplicationBuilderSpec.scala
Labels: in progress, status:needs-backport

#8823 Casing fix for CSPFilter links in the migration guide
  documentation/manual/releases/release27/migration27/Migration27.md
Labels: status:needs-backport, topic:documentation

#8607 Support insecure HTTP/2 requests (#8606)
  documentation/manual/working/commonGuide/server/AkkaHttpServer.md
  framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
  framework/src/play-akka-http2-support/src/main/resources/reference.conf
  framework/src/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala
Labels: ready

#8827 Need to filter params for java request
  framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesModels.scala
  framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/tests/RouterSpec.scala
Labels: in progress

#8804 new trait MessagesInjectedController
  framework/src/play/src/main/scala/play/api/mvc/Controller.scala
Labels: status:needs-backport

#8800 Allow direct field access in Java Forms
  documentation/manual/working/javaGuide/main/forms/JavaForms.md
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaFormsDirectFieldAccess.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/u4/User.java
  framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java
  framework/src/play-java-forms/src/main/java/play/data/Form.java
  framework/src/play-java-forms/src/main/resources/reference.conf
  framework/src/play-java-forms/src/test/java/play/data/Subtask.java
  framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
  framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
  framework/src/play-java-forms/src/test/scala/play/data/PartialValidationSpec.scala
Labels: review, status:needs-backport

#8831 Integer.valueOf instead of deprecated new Integer(...)
  documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/models/AgeRange.java
  documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/models/User.java
  framework/src/play-java/src/main/java/play/libs/Time.java
  framework/src/play/src/main/scala/play/api/mvc/Cookie.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/tests/RouterSpec.scala
Labels: in progress

#8834 Fix ambiguous import for Java 11
  documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/playlib/HelloModule.java
Labels: in progress, status:needs-backport

#8835 Another Java 11 fix: linesIterator instead of lines in docs
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaFormHelpers.scala
Labels: in progress, status:needs-backport

#8836 [Travis CI] fast_finish: true
  .travis.yml
Labels: in progress, status:needs-backport

#8808 SameSite attribute for CSRF cookie
  documentation/manual/releases/release27/migration27/Migration27.md
  framework/project/BuildSettings.scala
  framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
  framework/src/play-filters-helpers/src/main/resources/reference.conf
  framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
  framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
  framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
Labels: status:needs-backport

#8839 Java Form doc update on how to bind List
  documentation/manual/working/javaGuide/main/forms/JavaFormHelpers.md
Labels: in progress, status:needs-backport

#8838 Update dependencies before Release Candidate 4
  framework/project/Dependencies.scala
  framework/project/plugins.sbt
  framework/src/play-test/src/main/java/play/test/TestBrowser.java
Labels: in progress, status:needs-forwardport, type:updates

#8846 Do not promote artifacts automatically
  framework/project/BuildSettings.scala
Labels: merge-when-green, review, status:needs-backport, topic:sbt

#8845 Avoid publishing microbenchmarks and integration tests artifacts
  framework/build.sbt
  framework/project/BuildSettings.scala
Labels: in progress, status:needs-backport, topic:sbt
