Repository playframework/playframework, pull requests merged in 2018-02, with the labels that each got.

#8215 Upgrade netty and sbt-native-packager
  framework/project/Dependencies.scala
  framework/project/plugins.sbt
Labels: status:needs-backport

#8213 GH-7105: Remove Play icons from default pages
  framework/src/play/src/main/scala/views/defaultpages/badRequest.scala.html
  framework/src/play/src/main/scala/views/defaultpages/devError.scala.html
  framework/src/play/src/main/scala/views/defaultpages/devNotFound.scala.html
  framework/src/play/src/main/scala/views/defaultpages/error.scala.html
  framework/src/play/src/main/scala/views/defaultpages/notFound.scala.html
  framework/src/play/src/main/scala/views/defaultpages/todo.scala.html
  framework/src/play/src/main/scala/views/defaultpages/unauthorized.scala.html
Labels: enhancement, status:needs-backport

#8159 Add getExistingFile(...) to Java Environment
  framework/src/play/src/main/java/play/Environment.java
Labels: status:needs-backport

#8232 sbt 0.13.17
  framework/project/build.properties
Labels: status:needs-backport, topic:sbt, type:updates

#8208 Added troubleshooting section for Heroku deployment
  documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
Labels: status:needs-backport, topic:documentation

#8161 Changed import of "block-request" example in docs
  documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala
Labels: status:needs-forwardport, topic:documentation

#8244 Make request types covariant
  framework/src/play-test/src/main/scala/play/api/test/Fakes.scala
  framework/src/play/src/main/scala/play/api/mvc/MessagesRequest.scala
  framework/src/play/src/main/scala/play/api/mvc/Security.scala
  framework/src/play/src/test/scala/play/core/test/Fakes.scala
Labels: enhancement, status:needs-backport, topic:scala-api

#8243 Upgrades ALPN agent to 2.0.7
  framework/project/Dependencies.scala
Labels: status:needs-backport, type:updates

#8249 Remove newlines in twirl templates
  framework/src/play-docs-sbt-plugin/src/main/twirl/com/typesafe/play/docs/sbtplugin/translationReport.scala.html
  framework/src/play/src/main/scala/views/defaultpages/badRequest.scala.html
  framework/src/play/src/main/scala/views/defaultpages/devError.scala.html
  framework/src/play/src/main/scala/views/defaultpages/devNotFound.scala.html
  framework/src/play/src/main/scala/views/defaultpages/error.scala.html
  framework/src/play/src/main/scala/views/defaultpages/notFound.scala.html
  framework/src/play/src/main/scala/views/defaultpages/unauthorized.scala.html
  framework/src/play/src/main/scala/views/helper/checkbox.scala.html
  framework/src/play/src/main/scala/views/helper/defaultFieldConstructor.scala.html
  framework/src/play/src/main/scala/views/helper/form.scala.html
  framework/src/play/src/main/scala/views/helper/input.scala.html
  framework/src/play/src/main/scala/views/helper/inputCheckboxGroup.scala.html
  framework/src/play/src/main/scala/views/helper/inputDate.scala.html
  framework/src/play/src/main/scala/views/helper/inputFile.scala.html
  framework/src/play/src/main/scala/views/helper/inputPassword.scala.html
  framework/src/play/src/main/scala/views/helper/inputRadioGroup.scala.html
  framework/src/play/src/main/scala/views/helper/inputText.scala.html
  framework/src/play/src/main/scala/views/helper/javascriptRouter.scala.html
  framework/src/play/src/main/scala/views/helper/requireJs.scala.html
  framework/src/play/src/main/scala/views/helper/select.scala.html
  framework/src/play/src/main/scala/views/helper/textarea.scala.html
  framework/src/play/src/main/scala/views/play20/manual.scala.html
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/views/index.scala.html
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/views/main.scala.html
Labels: enhancement, status:needs-backport

#8236 Prevent none/none to leak into Play (master)
  framework/build.sbt
  framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
  framework/src/play-akka-http-server/src/test/scala/play/core/server/akkahttp/AkkaHeadersWrapperTest.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/RequestHeadersSpec.scala
Labels: status:needs-backport

#8250 Upgrade netty
  framework/project/Dependencies.scala
Labels: status:needs-backport, type:updates

#8252 Upgrade HikariCP
  framework/project/Dependencies.scala
Labels: status:needs-backport

#8160 Once more fix environment evolutions reader
  framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
Labels: bug, status:needs-backport

#8209 add a way to read X-Forwarded-Proto in RedirectHttpsFilter
  documentation/manual/working/commonGuide/filters/RedirectHttpsFilter.md
  framework/project/BuildSettings.scala
  framework/src/play-filters-helpers/src/main/resources/reference.conf
  framework/src/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala
  framework/src/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala
  framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
Labels: enhancement, topic:scala-api

#8253 Update Akka to version 2.5.10
  framework/project/Dependencies.scala
Labels: status:needs-backport, type:updates

#8258 Upgrade twirl
  framework/project/plugins.sbt
Labels: status:needs-backport

#8235 Remove references to g8Scaffold
  documentation/manual/gettingStarted/NewApplication.md
  documentation/manual/gettingStarted/Tutorials.md
Labels: status:needs-backport, topic:documentation, topic:sbt
