Repository playframework/playframework, pull requests merged in 2018-05, with the labels that each got.

#8394 use foldLeft instead of /:
  framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
Labels: enhancement, status:needs-backport

#8395 Update documentation about SBT usage
  documentation/manual/gettingStarted/PlayConsole.md
Labels: status:needs-backport, topic:documentation

#8389 Upgrade Netty
  framework/project/Dependencies.scala
Labels: bug, status:needs-backport, topic:upstream, type:updates

#8410 Use Guice to initialize database connection pools
  framework/src/play-jdbc/src/main/scala/play/api/db/DBModule.scala
  framework/src/play-jdbc/src/main/scala/play/api/db/Databases.scala
  framework/src/play-jdbc/src/test/scala/play/api/db/ConnectionPoolConfigSpec.scala
Labels: bug, status:needs-backport

#8377 [2.6.x] Only apply logback-test.xml in Test mode
  framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
Labels: status:needs-backport, status:needs-forwardport

#8403 TemplateImports cleanup
  framework/src/build-link/src/main/java/play/TemplateImports.java
Labels: enhancement, status:needs-backport

#8415 Netty upgrade
  framework/project/Dependencies.scala
Labels: status:needs-backport

#8426 Correct implementation of ConfigLoader[Seq[Long]] to load all longs
  framework/src/play/src/main/scala/play/api/Configuration.scala
  framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
Labels: status:needs-backport

#8430 Call ExecutionContext.prepare in Action.apply
  framework/src/play/src/main/scala/play/api/mvc/Action.scala
Labels: bug, status:needs-backport

#8431 Use Scala 2.12.6 in tests and docs
  documentation/manual/releases/release26/Highlights26.md
  framework/bin/test-sbt-plugins-1_0
  framework/bin/test-scala-212
  framework/project/BuildSettings.scala
  framework/project/Dependencies.scala
  framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/build.sbt
  framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/build.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/build.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/build.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/build.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/build.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/build.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/module/build.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/build.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/build.sbt
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/build.sbt
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/incremental-compilation/build.sbt
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/build.sbt
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/build.sbt
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/source-mapping/build.sbt
Labels: type:updates

#8437 corrected methods for akka 2.5.12
  framework/project/Dependencies.scala
  framework/src/play-integration-test/src/test/scala/play/it/libs/JavaWSSpec.scala
  framework/src/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala
  framework/src/play-streams/src/test/scala/play/libs/streams/AccumulatorSpec.scala
Labels: type:updates
