Repository playframework/playframework, pull requests merged in 2018-12, with the labels that each got.

#8855 Added sbt 1.2.7 to Play 2.7 migration guide
  documentation/manual/releases/release27/migration27/Migration27.md
Labels: in progress, status:needs-backport, topic:documentation

#8843 Better organize migration guide
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/releases/release27/migration27/index.toc
  framework/src/run-support/src/main/scala/play/runsupport/RunHook.scala
Labels: review, status:needs-backport, topic:documentation

#8844 Query binding tests
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/controllers/Application.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/conf/routes
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/tests/RouterSpec.scala
Labels: in progress, status:needs-backport

#8818 Fix spelling (-ise -> -ize, isation -> ization)
  documentation/manual/ModuleDirectory.md
  documentation/manual/releases/release22/Migration22.md
  documentation/manual/releases/release24/migration24/GlobalSettings.md
  documentation/manual/releases/release24/migration24/Migration24.md
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/working/commonGuide/database/Evolutions.md
  documentation/manual/working/javaGuide/advanced/routing/JavaJavascriptRouter.md
  documentation/manual/working/javaGuide/main/application/JavaHttpFilters.md
  documentation/manual/working/javaGuide/main/dependencyinjection/JavaCompileTimeDependencyInjection.md
  documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md
  documentation/manual/working/javaGuide/main/forms/JavaCsrf.md
  documentation/manual/working/javaGuide/main/forms/JavaForms.md
  documentation/manual/working/javaGuide/main/tests/JavaTestingWithDatabases.md
  documentation/manual/working/scalaGuide/advanced/routing/ScalaJavascriptRouting.md
  documentation/manual/working/scalaGuide/main/application/ScalaHttpFilters.md
  documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaCompileTimeDependencyInjection.md
  documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
  documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
  documentation/manual/working/scalaGuide/main/http/ScalaActionsComposition.md
  documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithDatabases.md
Labels: status:needs-backport, topic:documentation

#8833 Rename clearingLang to withoutLang
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  documentation/manual/working/scalaGuide/main/i18n/ScalaI18N.md
  documentation/manual/working/scalaGuide/main/i18n/code/scalaguide/i18n/ScalaI18nService.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
  framework/src/play/src/main/java/play/mvc/Controller.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/java/play/mvc/Result.java
  framework/src/play/src/main/scala/play/api/i18n/I18nSupport.scala
  framework/src/play/src/main/scala/play/api/mvc/Results.scala
  framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
Labels: review, status:needs-backport

#8858 Ignoring WhiteSource for unpublished projects
  framework/project/BuildSettings.scala
Labels: review, status:needs-backport, topic:sbt

#8859 Fix query string binding
  documentation/manual/releases/release27/migration27/Migration27.md
  framework/src/play/src/main/scala/play/api/mvc/Binders.scala
  framework/src/play/src/main/scala/play/core/routing/GeneratedRouter.scala
  framework/src/play/src/test/scala/play/api/mvc/BindersSpec.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/conf/routes
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/tests/RouterSpec.scala
Labels: in progress, status:needs-backport

#8865 sbt 1.2.7
  project/build.properties
Labels: in progress, status:needs-backport

#8869 Update interplay to version 2.0.5
  framework/project/plugins.sbt
Labels: in progress, status:needs-backport, type:updates

#8860 Select an arbitrary websocket subprotocol proposed by the client
  framework/src/play-akka-http-server/src/main/scala/akka/http/play/WebSocketHandler.scala
  framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
Labels: in progress, status:needs-backport

#8868 Akka 2.5.19
  documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/JavaAkka.java
  framework/project/Dependencies.scala
Labels: in progress, status:needs-backport

#8870 Remove unnecessary file
  project/build.properties
Labels: in progress

#8871 [2.7.x] Remove unnecessary file
  documentation/project/build.properties
  framework/project/build.properties
  project/build.properties
Labels: in progress

#8872 Fix ambiguous @lang, @flash and @session
  framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
  framework/src/play-java/src/test/scala/play/mvc/MixTemplateAndHttpImplicits.scala
Labels: in progress, status:needs-backport

#8878 Add dispositionType to FilePart and FileInfo (which defaults to "form-data")
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
  documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
  framework/project/BuildSettings.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
  framework/src/play/src/main/java/play/mvc/BodyParser.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/java/play/mvc/MultipartFormatter.java
  framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala
  framework/src/play/src/main/scala/play/core/formatters/Multipart.scala
  framework/src/play/src/main/scala/play/core/j/JavaParsers.scala
  framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
Labels: in progress, status:needs-backport

#8880 Handle multipart form upload with empty filename as BadPart
  framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
  framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
Labels: in progress, status:needs-backport

#8883 Issue 8233 | Tried to clarify wording regarding custom errorHandler cfg
  documentation/manual/working/scalaGuide/main/http/ScalaErrorHandling.md
Labels: status:needs-backport, topic:documentation

#8884 Use Akka HTTP snapshots for our cron builds
  .travis.yml
  framework/bin/scriptLib
  framework/project/AkkaSnapshotRepositories.scala
  framework/project/Dependencies.scala
Labels: in progress, status:needs-backport

#8888 Reference application.conf as file in ConfigFile
  documentation/manual/working/commonGuide/configuration/ConfigFile.md
Labels: status:needs-forwardport, topic:documentation

#8887 Decouple scala-reflect library from Play dependencies
  framework/project/Dependencies.scala
Labels: in progress

#8891 Configure mima to run against all crossScalaVersions
  framework/bin/validate-code
  framework/project/BuildSettings.scala
Labels: in progress, status:needs-backport

#8882 Handle multipart form upload with empty file as BadPart
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/working/javaGuide/main/upload/JavaFileUpload.md
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
  documentation/manual/working/scalaGuide/main/upload/ScalaFileUpload.md
  framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
  framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
Labels: in progress

#8894 [2.7.x] Cull MiMa filters & target future 2.7.0 release
  framework/project/BuildSettings.scala
Labels: review

#8890 Minor dependencies updates
  documentation/manual/working/commonGuide/filters/SecurityHeaders.md
  documentation/manual/working/scalaGuide/advanced/routing/ScalaSirdRouter.md
  documentation/manual/working/scalaGuide/main/forms/ScalaCustomValidations.md
  documentation/manual/working/scalaGuide/main/forms/ScalaForms.md
  documentation/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithSpecs2.md
  framework/project/Dependencies.scala
  framework/project/plugins.sbt
  framework/src/sbt-plugin/src/main/scala/play/sbt/Play.scala
Labels: in progress

#8893 Cull MiMa filters & target future 2.8.0 release
  framework/project/BuildSettings.scala
Labels: review

#8896 Add back IT on Java 11
  .travis.yml
Labels: in progress, status:needs-backport

#8897 Update Akka HTTP to version 10.1.6
  framework/project/Dependencies.scala
Labels: review, status:needs-backport, topic:upstream, type:updates

#8899 minor scaladocs improvement
  framework/src/play/src/main/scala/play/api/mvc/Action.scala
Labels: in progress
