Repository playframework/playframework, pull requests merged in 2018-07, with the labels that each got.

#8498 Handle exceptions thrown from stop hooks
  framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala
  framework/src/play/src/test/scala/play/api/inject/DefaultApplicationLifecycleSpec.scala
Labels: enhancement, status:needs-backport

#8499 Fix wrong comments
  framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
Labels: status:needs-backport, topic:documentation

#8506 Use configured HttpErrorHandler for exceptions before action is created
  framework/src/play-integration-test/src/test/scala/play/it/http/HttpErrorHandlingSpec.scala
  framework/src/play-server/src/main/scala/play/core/server/Server.scala
Labels: status:needs-backport

#8495 Fix issues when building on Windows
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
  framework/project/BuildSettings.scala
Labels: status:needs-backport, topic:windows

#8510 [2.6.x] Added asScala API to EssentialFilter
  framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala
  framework/src/play/src/main/java/play/mvc/EssentialFilter.java
  framework/src/play/src/main/scala/play/api/mvc/Filters.scala
Labels: enhancement, status:needs-forwardport, topic:java-api, topic:scala-api

#8517 Fix Windows compatibility issue in assets controller
  framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala
  framework/src/play/src/main/scala/play/api/controllers/Assets.scala
  framework/src/play/src/test/scala/play/api/controllers/AssetsSpec.scala
Labels: enhancement, status:needs-forwardport, topic:windows

#8521 Fix a typo in ScalaConfig.md
  documentation/manual/working/scalaGuide/main/config/ScalaConfig.md
Labels: status:needs-forwardport, topic:documentation

#8067 Nicer syntax for router.withPrefix
  framework/src/play/src/main/scala/play/api/routing/Router.scala
  framework/src/play/src/test/scala/play/core/routing/RouterSpec.scala
Labels: enhancement

#8530 Implementation for issue #8527 (Content-Disposition of multipart/form-data too strict for some implementations)
  framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
  framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
Labels: enhancement, status:needs-backport

#8162 Add setting to configure max header value length in Akka HTTP Server
  framework/project/BuildSettings.scala
  framework/src/play-akka-http-server/src/main/resources/reference.conf
  framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/RequestHeadersSpec.scala
  framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala
  framework/src/play-server/src/main/scala/play/core/server/ServerProvider.scala
  framework/src/play/src/main/scala/play/api/http/StandardValues.scala
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/build.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
Labels: enhancement, status:needs-backport, topic:upstream

#8538 Improved SBT Cookbook in documentation by adding imports for scala.sys.process.Process
  documentation/manual/working/commonGuide/build/code/runhook.sbt
Labels: status:needs-backport, topic:documentation
