Repository playframework/playframework, pull requests merged in 2018-03, with the labels that each got.

#8260 Upgrade akka
  framework/project/Dependencies.scala
Labels: status:needs-backport, type:updates

#8262 Update play-ws to version 1.1.5
  framework/project/Dependencies.scala
Labels: status:needs-backport, type:updates

#8198 Move setAutoCommit call into try block
  framework/src/play-jdbc/src/main/scala/play/api/db/Databases.scala
Labels: status:needs-backport, topic:evolutions

#8263 Update play-ws to version 1.1.6
  framework/project/Dependencies.scala
Labels: status:needs-backport, type:updates

#8271 Update play-json to 2.6.9
  framework/project/Dependencies.scala
Labels: status:needs-backport, type:updates

#8269 Contribution Guidelines: Update Copyright year to 2018
  CONTRIBUTING.md
Labels: status:needs-backport, topic:documentation

#8272 Update Reactive Streams to 1.0.2
  framework/project/Dependencies.scala
Labels: status:needs-backport

#8275 Load standard logback files in LogbackLoggerConfigurator
  framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
Labels: status:needs-backport

#8279 Upgrade + rename Hibernate ORM
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  framework/project/Dependencies.scala
Labels: type:updates

#8287 Remove duplicated copyright headers
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActionCreator.java
  framework/src/play/src/main/java/play/libs/Json.java
  framework/src/play/src/main/scala/views/helper/Helpers.scala
Labels: status:needs-backport

#7921 Fixes issue 5275 with java helper method for parsing json
  documentation/manual/working/javaGuide/main/json/JavaJsonActions.md
  documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala
Labels: enhancement, topic:java-api

#8290 Benji module
  documentation/manual/ModuleDirectory.md
Labels: status:needs-backport, topic:documentation

#8292 currently this should cancel the remoteIn
  framework/src/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala
Labels: status:needs-backport

#8293 Add Scala 2.13.0-M3 support
  .travis.yml
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/working/commonGuide/filters/SecurityHeaders.md
  documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaAsync.java
  documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaTracerController.java
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/BrowserFunctionalTest.java
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/FunctionalTest.java
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/ModelTest.java
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/ServerFunctionalTest.java
  documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java
  documentation/manual/working/scalaGuide/advanced/routing/ScalaSirdRouter.md
  documentation/manual/working/scalaGuide/main/forms/ScalaCustomValidations.md
  documentation/manual/working/scalaGuide/main/forms/ScalaForms.md
  documentation/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithSpecs2.md
  documentation/manual/working/scalaGuide/main/tests/code/specs2/ScalaFunctionalTestSpec.scala
  documentation/manual/working/scalaGuide/main/tests/code/webservice/ScalaTestingWebServiceClients.scala
  documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
  documentation/project/build.properties
  framework/bin/test-scala-213
  framework/build.sbt
  framework/project/BuildSettings.scala
  framework/project/Dependencies.scala
  framework/project/plugins.sbt
  framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceApplicationLoaderSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/parsing/DefaultBodyParserSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/test/OkHttpEndpointSupport.scala
  framework/src/play-java/src/main/scala-2.13.0-M3/play/core/j/JavaImplicitConversions.scala
  framework/src/play/src/main/scala/play/core/formatters/Multipart.scala
  framework/src/play/src/test/scala/play/api/http/HttpConfigurationSpec.scala
  framework/src/play/src/test/scala/play/api/routing/RouterSpec.scala
  framework/src/play/src/test/scala/play/core/routing/RouterSpec.scala
Labels: status:to-review, type:updates

#8309 update the yourkit image and url
  documentation/manual/hacking/ThirdPartyTools.md
  documentation/manual/hacking/images/yourkit.png
Labels: status:needs-backport

#8300 Add contribution and download links to doc README
  documentation/README.md
Labels: status:needs-backport, topic:documentation

#8314 Change Akka HTTP backend to use raw headers
  framework/project/Dependencies.scala
  framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
  framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
  framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
  framework/src/play-integration-test/src/test/scala/play/it/LogTester.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/AkkaResponseHeaderHandlingSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/RequestHeadersSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/libs/ScalaWSSpec.scala
  framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
  framework/src/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala
  framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
  framework/src/play/src/main/scala/play/core/utils/AsciiSet.scala
  framework/src/play/src/main/scala/play/utils/UriEncoding.scala
  framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
Labels: bug, status:needs-forwardport, topic:upstream

#8315 Upgrade jackson
  framework/project/Dependencies.scala
Labels: type:updates

#8291 used typed keys to pass the current context lang to scala (#8288)
  framework/src/play-java/src/test/java/play/mvc/HttpTest.java
  framework/src/play/src/main/java/play/i18n/Messages.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/scala/play/api/i18n/Messages.scala
Labels: status:needs-backport
