Repository playframework/playframework, pull requests merged in 2018-10, with the labels that each got.

#8638 Update to Akka 2.5.17
  framework/project/Dependencies.scala
Labels: review, status:needs-backport, type:updates

#8645 [2.6.x]: Getting started experience improvements
  documentation/README.md
  documentation/addMarkdownCopyright
  documentation/build.sbt
  documentation/manual/gettingStarted/IDE.md
  documentation/manual/gettingStarted/Introduction.md
  documentation/manual/gettingStarted/NewApplication.md
  documentation/manual/gettingStarted/PlayConsole.md
  documentation/manual/gettingStarted/Requirements.md
  documentation/manual/gettingStarted/Tutorials.md
  documentation/manual/gettingStarted/code/PlayConsole.scala
  documentation/manual/gettingStarted/images/comet-clock.png
  documentation/manual/gettingStarted/images/computerdatabase.png
  documentation/manual/gettingStarted/images/forms.png
  documentation/manual/gettingStarted/images/helloworld.png
  documentation/manual/gettingStarted/images/rps-screenshot.png
  documentation/manual/gettingStarted/images/websocket-chat.png
  documentation/manual/gettingStarted/images/zentask.png
  documentation/manual/gettingStarted/index.toc
  documentation/manual/hacking/BuildingFromSource.md
  documentation/manual/hacking/Translations.md
  documentation/manual/index.toc
  documentation/manual/releases/release26/Highlights26.md
  documentation/manual/releases/release26/migration26/CacheMigration26.md
  documentation/manual/releases/release26/migration26/JPAMigration26.md
  documentation/manual/releases/release26/migration26/MessagesMigration26.md
  documentation/manual/tutorial/HelloWorldTutorial.md
  documentation/manual/tutorial/ImplementingHelloWorld.md
  documentation/manual/tutorial/PlayApplicationOverview.md
  documentation/manual/tutorial/Tutorials.md
  documentation/manual/tutorial/code/javaguide/hello/HelloController.java
  documentation/manual/tutorial/code/javaguide/hello/hello.scala.html
  documentation/manual/tutorial/code/javaguide/hello/helloName.scala.html
  documentation/manual/tutorial/code/javaguide/hello/index.scala.html
  documentation/manual/tutorial/code/javaguide/hello/main.scala.html
  documentation/manual/tutorial/code/routes
  documentation/manual/tutorial/code/scalaguide/hello/HelloController.scala
  documentation/manual/tutorial/images/hello-error.png
  documentation/manual/tutorial/images/hello-name.png
  documentation/manual/tutorial/images/hello-page.png
  documentation/manual/tutorial/images/play-request-response.png
  documentation/manual/tutorial/images/play-stack.png
  documentation/manual/tutorial/index.toc
  documentation/manual/working/commonGuide/build/code/javaguide/common/build/controllers/HomeController.java
  documentation/manual/working/commonGuide/configuration/SettingsAkkaHttp.md
  documentation/manual/working/commonGuide/configuration/SettingsSession.md
  documentation/manual/working/commonGuide/configuration/code/CustomAkkaHttpServer.scala
  documentation/manual/working/commonGuide/configuration/code/javaguide/configuration/MyController.java
  documentation/manual/working/commonGuide/schedule/ScheduledTasks.md
  documentation/manual/working/javaGuide/main/config/code/javaguide/config/MyController.java
  documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaMarkerController.java
  documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaTracerController.java
  documentation/project/plugins.sbt
  framework/bin/test-docs
Labels: review

#8646 added generated keystore test
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/app/controllers/HomeController.scala
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/app/router/Routes.scala
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/build.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/conf/application.conf
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/project/Build.scala
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/project/plugins.sbt
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/test
Labels: in progress

#8648 Update documentation links
  documentation/manual/ModuleDirectory.md
  documentation/manual/about/PlayUserGroups.md
  documentation/manual/gettingStarted/Anatomy.md
  documentation/manual/gettingStarted/Installing.md
  documentation/manual/gettingStarted/Requirements.md
  documentation/manual/hacking/ThirdPartyTools.md
  documentation/manual/hacking/images/TravisCI-Full-Color.png
  documentation/manual/hacking/images/cloudbees.png
  documentation/manual/releases/release21/Highlights21.md
  documentation/manual/releases/release21/Migration21.md
  documentation/manual/releases/release23/Highlights23.md
  documentation/manual/releases/release23/Migration23.md
  documentation/manual/releases/release25/Highlights25.md
  documentation/manual/releases/release25/migration25/CryptoMigration25.md
  documentation/manual/releases/release25/migration25/JavaMigration25.md
  documentation/manual/releases/release25/migration25/Migration25.md
  documentation/manual/releases/release26/Highlights26.md
  documentation/manual/releases/release26/migration26/Migration26.md
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/tutorial/Tutorials.md
  documentation/manual/working/commonGuide/assets/AssetsCoffeeScript.md
  documentation/manual/working/commonGuide/assets/AssetsLess.md
  documentation/manual/working/commonGuide/assets/AssetsOverview.md
  documentation/manual/working/commonGuide/assets/AssetsSass.md
  documentation/manual/working/commonGuide/assets/RequireJS-support.md
  documentation/manual/working/commonGuide/configuration/SettingsNetty.md
  documentation/manual/working/commonGuide/configuration/WsSSL.md
  documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
  documentation/manual/working/commonGuide/shutdown/Shutdown.md
  documentation/manual/working/javaGuide/main/forms/JavaForms.md
  documentation/manual/working/javaGuide/main/sql/JavaJPA.md
  documentation/manual/working/javaGuide/main/ws/JavaOpenID.md
  documentation/manual/working/scalaGuide/main/logging/ScalaLogging.md
  documentation/manual/working/scalaGuide/main/ws/ScalaOpenID.md
  documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
  framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsValidation.scala
Labels: review, status:needs-backport, topic:documentation

#8653 Backports cd56580 from master
  documentation/manual/ModuleDirectory.md
  documentation/manual/about/PlayUserGroups.md
  documentation/manual/gettingStarted/Anatomy.md
  documentation/manual/gettingStarted/Installing.md
  documentation/manual/gettingStarted/Requirements.md
  documentation/manual/hacking/ThirdPartyTools.md
  documentation/manual/hacking/images/TravisCI-Full-Color.png
  documentation/manual/hacking/images/cloudbees.png
  documentation/manual/releases/release21/Highlights21.md
  documentation/manual/releases/release21/Migration21.md
  documentation/manual/releases/release23/Highlights23.md
  documentation/manual/releases/release23/Migration23.md
  documentation/manual/releases/release25/Highlights25.md
  documentation/manual/releases/release25/migration25/CryptoMigration25.md
  documentation/manual/releases/release25/migration25/JavaMigration25.md
  documentation/manual/releases/release25/migration25/Migration25.md
  documentation/manual/releases/release26/Highlights26.md
  documentation/manual/releases/release26/migration26/Migration26.md
  documentation/manual/tutorial/Tutorials.md
  documentation/manual/working/commonGuide/assets/AssetsCoffeeScript.md
  documentation/manual/working/commonGuide/assets/AssetsLess.md
  documentation/manual/working/commonGuide/assets/AssetsOverview.md
  documentation/manual/working/commonGuide/assets/AssetsSass.md
  documentation/manual/working/commonGuide/assets/RequireJS-support.md
  documentation/manual/working/commonGuide/configuration/SettingsNetty.md
  documentation/manual/working/commonGuide/configuration/WsSSL.md
  documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
  documentation/manual/working/javaGuide/main/forms/JavaForms.md
  documentation/manual/working/javaGuide/main/sql/JavaJPA.md
  documentation/manual/working/javaGuide/main/ws/JavaOpenID.md
  documentation/manual/working/scalaGuide/main/logging/ScalaLogging.md
  documentation/manual/working/scalaGuide/main/ws/ScalaOpenID.md
  documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
  framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsValidation.scala
Labels: review

#8642 Honor play settings on AkkaHttpServer for client auth in SSL
  framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
Labels: in progress, status:needs-forwardport

#8649 Upgrade to changes pushed up to ssl-config
  framework/project/BuildSettings.scala
  framework/project/Dependencies.scala
  framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala
  framework/src/play-server/src/test/scala/play/core/server/ssl/FakeKeyStoreSpec.scala
Labels: review

#8655 More asJava methods
  framework/project/BuildSettings.scala
  framework/src/play/src/main/scala/play/api/i18n/Langs.scala
  framework/src/play/src/main/scala/play/api/i18n/Messages.scala
Labels: in progress, status:needs-backport

#8657 Guice 4.2.1 with better JDK 11 support
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/releases/release27/migration27/Migration27.md
  framework/project/Dependencies.scala
Labels: in progress

#8659 Upgrade to ssl-config 0.3.4
  framework/project/BuildSettings.scala
  framework/project/Dependencies.scala
  framework/src/play-integration-test/src/test/scala/play/it/test/ServerEndpoint.scala
  framework/src/play-server/src/main/scala/play/core/server/ssl/DefaultSSLEngineProvider.scala
  framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala
Labels: review

#8621 Also pass config via validation payload
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
  framework/project/BuildSettings.scala
  framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java
  framework/src/play-java-forms/src/main/java/play/data/Form.java
  framework/src/play-java-forms/src/main/java/play/data/FormFactory.java
  framework/src/play-java-forms/src/main/java/play/data/FormFactoryComponents.java
  framework/src/play-java-forms/src/main/java/play/data/validation/Constraints.java
  framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java
  framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
  framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
  framework/src/play-java-forms/src/test/scala/play/data/PartialValidationSpec.scala
Labels: review

#8656 Lookup form helpers' _label and _name attributes in messages
  framework/src/play/src/main/scala/views/helper/Helpers.scala
  framework/src/play/src/test/resources/messages
  framework/src/play/src/test/scala/views/html/helper/HelpersSpec.scala
Labels: in progress, status:needs-backport

#8654 Fix precedence of PlayMagicForJava implicits vs. passed ones
  framework/project/BuildSettings.scala
  framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
  framework/src/play-java/src/test/java/play/mvc/HttpTest.java
  framework/src/play-java/src/test/resources/messages
  framework/src/play-java/src/test/resources/messages.en-US
  framework/src/play-java/src/test/resources/messages.fr
  framework/src/play-java/src/test/scala/play/mvc/ImplicitLang.scala
  framework/src/play-java/src/test/scala/play/mvc/ImplicitLangInclude.scala
  framework/src/play-java/src/test/scala/play/mvc/ImplicitMessages.scala
  framework/src/play-java/src/test/scala/play/mvc/ImplicitMessagesInclude.scala
  framework/src/play-java/src/test/scala/play/mvc/ImplicitRequest.scala
  framework/src/play-java/src/test/scala/play/mvc/ImplicitRequestInclude.scala
  framework/src/play-java/src/test/scala/play/mvc/NoImplicitLang.scala
  framework/src/play-java/src/test/scala/play/mvc/NoImplicitMessages.scala
  framework/src/play-java/src/test/scala/play/mvc/NoImplicitRequest.scala
  framework/src/play/src/main/java/play/i18n/Messages.java
Labels: review

#8665 Output exception description for better diagnostics.
  framework/src/play-exceptions/src/main/java/play/api/UsefulException.java
Labels: enhancement, status:needs-backport

#8671 escaped oracle reserved word using doublequote
  framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
Labels: status:needs-backport

#8670 Fixed two broken links
  CONTRIBUTING.md
Labels: status:needs-backport

#8666 Make sure a new ctx gets set in the Context.current ThreadLocal
  framework/src/play-filters-helpers/src/main/java/play/filters/csp/AbstractCSPAction.java
  framework/src/play/src/main/java/play/mvc/Security.java
Labels: in progress, status:needs-backport

#8662 Make sure request and header stay in sync in Http.Context
  framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java
  framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
  framework/src/play/src/main/java/play/mvc/Http.java
Labels: in progress

#8668 Sync Scala and Java cookie default values
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/scala/play/api/mvc/Cookie.scala
  framework/src/play/src/test/java/play/mvc/CookieBuilderTest.java
Labels: in progress

#8667 Simply use ctx.withRequest instead of a new WrappedContext
  framework/src/play-filters-helpers/src/main/java/play/filters/csp/AbstractCSPAction.java
  framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
Labels: in progress

#8675 Also copy lang in ctx copy constructor and ctx.withRequest
  framework/src/play-java/src/test/java/play/mvc/HttpTest.java
  framework/src/play/src/main/java/play/mvc/Http.java
Labels: in progress

#8673 Deprecated Java Context.id()
  framework/src/play-integration-test/src/test/scala/play/it/http/JavaRequestsSpec.scala
  framework/src/play/src/main/java/play/mvc/Http.java
Labels: in progress

#8674 Deprecated Java Context.fileMimeTypes()
  framework/src/play/src/main/java/play/mvc/Http.java
Labels: in progress

#8546 Deprecate Http.Context.clearLang and Http.Context.changeLang methods
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/releases/release27/migration27/index.toc
  documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/JavaI18N.java
  documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/explicitjavatemplate.scala.html
  documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/hellotemplate.scala.html
  documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/indextemplate.scala.html
  framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
  framework/src/play/src/main/java/play/i18n/MessagesApi.java
  framework/src/play/src/main/java/play/mvc/Controller.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/java/play/mvc/Result.java
  framework/src/play/src/main/resources/reference.conf
Labels: type:deprecated-feature

#8677 Update ssl-config to version 0.3.5
  framework/project/Dependencies.scala
  framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/test
Labels: review

#8676 Correctly handle lang in WrappedContext
  framework/src/play-java/src/test/java/play/mvc/HttpTest.java
  framework/src/play/src/main/java/play/mvc/Http.java
Labels: in progress

#8681 Migrate Play Akka gRPC testkit changes into Play
  framework/build.sbt
  framework/src/play-integration-test/src/test/scala/play/it/http/AkkaHttpCustomServerProviderSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/FlashCookieSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/FormFieldOrderSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/HttpErrorHandlingSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/HttpFiltersSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/SecureFlagSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/test/EndpointIntegrationSpecification.scala
  framework/src/play-integration-test/src/test/scala/play/it/test/OkHttpEndpointSupport.scala
  framework/src/play-integration-test/src/test/scala/play/it/test/WSEndpointSupport.scala
  framework/src/play-microbenchmark/src/test/scala/play/microbenchmark/it/HelloWorldBenchmark.scala
  framework/src/play-test/src/main/scala/play/api/test/ApplicationFactory.scala
  framework/src/play-test/src/main/scala/play/api/test/RunningServer.scala
  framework/src/play-test/src/main/scala/play/api/test/ServerEndpoint.scala
  framework/src/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala
  framework/src/play-test/src/main/scala/play/api/test/ServerEndpoints.scala
Labels: review

#8663 DiscardingCookie never sends "HTTPOnly"
  framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/java/play/mvc/Result.java
  framework/src/play/src/main/scala/play/api/mvc/Cookie.scala
Labels: in progress

#8686 Fix Travis
  framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
Labels: in progress

#8672 Config for the language cookie's SameSite attribute
  documentation/manual/working/scalaGuide/advanced/extending/code/ScalaExtendingPlay.scala
  documentation/manual/working/scalaGuide/main/i18n/ScalaI18N.md
  documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md
  framework/project/BuildSettings.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
  framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
  framework/src/play/src/main/java/play/i18n/MessagesApi.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/resources/reference.conf
  framework/src/play/src/main/scala/play/api/Configuration.scala
  framework/src/play/src/main/scala/play/api/Play.scala
  framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala
  framework/src/play/src/main/scala/play/api/i18n/Messages.scala
  framework/src/play/src/test/scala/play/api/i18n/MessagesSpec.scala
Labels: in progress

#8683 Remove dead code
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
Labels: in progress

#8687 Deprecate Http.Context.session method
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaWebSockets.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java
  documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/Twitter.java
  framework/src/play/src/main/java/play/mvc/Controller.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/java/play/mvc/Result.java
  framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala
  framework/src/play/src/main/scala/play/api/mvc/Session.scala
  framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
Labels: in progress

#8688 Deprecate Http.Context.flash method
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  documentation/manual/working/commonGuide/configuration/code/detailedtopics/httpec/MyController.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
  framework/project/BuildSettings.scala
  framework/src/play/src/main/java/play/mvc/Controller.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/java/play/mvc/Result.java
  framework/src/play/src/main/scala/play/api/mvc/Flash.scala
  framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala
  framework/src/play/src/main/scala/play/api/mvc/Results.scala
  framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
Labels: in progress

#8691 Bumps ssl-config to 0.3.6
  framework/project/Dependencies.scala
Labels: in progress

#8690 Move ServerEndpoint to play.core.server
  framework/src/play-integration-test/src/test/scala/play/it/http/FlashCookieSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/test/EndpointIntegrationSpecification.scala
  framework/src/play-integration-test/src/test/scala/play/it/test/OkHttpEndpointSupport.scala
  framework/src/play-integration-test/src/test/scala/play/it/test/WSEndpointSupport.scala
  framework/src/play-microbenchmark/src/test/scala/play/microbenchmark/it/HelloWorldBenchmark.scala
  framework/src/play-server/src/main/scala/play/core/server/ServerEndpoint.scala
  framework/src/play-server/src/main/scala/play/core/server/ServerEndpoints.scala
  framework/src/play-test/src/main/scala/play/api/test/RunningServer.scala
  framework/src/play-test/src/main/scala/play/api/test/ServerEndpoint.scala
  framework/src/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala
Labels: review

#8692 Merge the ctx's flash/session with the result ones
  framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
Labels: in progress

#8689 More testkit changes from Akka gRPC experiments
  framework/src/play-specs2/src/main/scala/play/api/test/Specs.scala
  framework/src/play-test/src/main/scala/play/api/test/RunningServer.scala
  framework/src/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala
  framework/src/play-test/src/main/scala/play/api/test/TestServerFactory.scala
Labels: review

#8695 Extract SelfSigned into a separate file
  framework/bin/test-docs
  framework/src/play-server/src/main/scala/play/core/server/SelfSigned.scala
  framework/src/play-server/src/main/scala/play/core/server/ServerEndpoint.scala
  framework/src/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala
  framework/src/play-test/src/main/scala/play/api/test/TestServerFactory.scala
Labels: review

#8701 bumps play-ws
  framework/project/Dependencies.scala
Labels: in progress

#8639 Pass request to action methods / Add new Action class that takes a request
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
  documentation/manual/working/javaGuide/code/MockJavaAction.scala
  documentation/manual/working/javaGuide/main/http/code/javaguide/ActionCreator.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActionCreator.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActionsComposition.java
  documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/Application.java
  framework/project/BuildSettings.scala
  framework/src/play-filters-helpers/src/test/scala/play/filters/csp/JavaCSPActionSpec.scala
  framework/src/play-filters-helpers/src/test/scala/play/filters/csp/JavaCSPReportSpec.scala
  framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala
  framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionOrderTest.java
  framework/src/play-integration-test/src/test/scala/play/it/http/JAction.scala
  framework/src/play/src/main/java/play/mvc/Action.java
  framework/src/play/src/main/scala/play/core/j/JavaAction.scala
  framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
  framework/src/play/src/main/scala/play/core/routing/HandlerInvoker.scala
  framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesFileParser.scala
  framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesModels.scala
  framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
  framework/src/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes-with-request-passed/a/app/controllers/a/A.java
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes-with-request-passed/a/conf/a.routes
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes-with-request-passed/b/app/controllers/b/B.java
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes-with-request-passed/b/conf/b.routes
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes-with-request-passed/build.sbt
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes-with-request-passed/c/app/controllers/c/C.java
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes-with-request-passed/c/conf/c.routes
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes-with-request-passed/conf/routes
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes-with-request-passed/nonplay/src/main/scala/nonplay.NonPlay.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes-with-request-passed/project/plugins.sbt
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes-with-request-passed/test
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/app/controllers/Application.java
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/app/controllers/InstanceController.java
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/app/controllers/module/ModuleController.java
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/app/controllers/πø$7ß.java
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/app/models/UserId.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/app/utils/JavaScriptRouterGenerator.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/build.sbt
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/conf/module.routes
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/conf/routes
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/project/plugins.sbt
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/project/scala-sbt-0.13/Common.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/project/scala-sbt-1.0/Common.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/public/css/abcd1234-main.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/public/css/abcd1234-minmain-min.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/public/css/main.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/public/css/main.css.md5
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/public/css/minmain-min.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/public/css/minmain-min.css.md5
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/public/css/minmain.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/public/css/nonfingerprinted-minmain-min.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/public/css/nonfingerprinted-minmain.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/public/css/nonfingerprinted.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/test
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/tests/RouterSpec.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/tests/assets/JavaScriptRouterSpec.js
Labels: in progress

#8694 Change occurrences of call(ctx) to call(req)
  framework/src/play-cache/src/main/java/play/cache/CachedAction.java
  framework/src/play-filters-helpers/src/main/java/play/filters/csp/AbstractCSPAction.java
  framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
  framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java
  framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionActionCreator.java
  framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionOrderTest.java
  framework/src/play-java-jpa/src/main/java/play/db/jpa/TransactionalAction.java
  framework/src/play/src/main/java/play/http/DefaultActionCreator.java
  framework/src/play/src/main/java/play/mvc/Security.java
  framework/src/play/src/test/java/play/mvc/SecurityTest.java
Labels: in progress

#8721 Forms - add support for IndexedSeq and Vector bindings
  framework/src/play/src/main/scala/play/api/data/Forms.scala
  framework/src/play/src/test/scala/play/api/data/FormSpec.scala
Labels: enhancement, status:needs-forwardport

#8723 Fixed wrong JavaDoc
  framework/src/play/src/main/java/play/mvc/Http.java
Labels: in progress

#8712 Fix HttpErrorHandlerSpec and make JsonHttpErrorHandler injectable
  framework/src/play-guice/src/test/scala/play/api/http/HttpErrorHandlerSpec.scala
  framework/src/play/src/main/java/play/http/JsonHttpErrorHandler.java
  framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
Labels: in progress, status:needs-backport

#8728 Remove redundant data from DynamicForm
  framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java
Labels: in progress

#8735 New APIs to discard headers on results
  framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
  framework/src/play/src/main/java/play/mvc/ResponseHeader.java
  framework/src/play/src/main/java/play/mvc/Result.java
  framework/src/play/src/main/scala/play/api/mvc/Results.scala
Labels: enhancement, status:needs-backport, topic:java-api, topic:scala-api

#8737 [2.6.x]: java versions of runningHttpPort/runningHttpsPort methods added to TestServer
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/ServerFunctionalTest.java
  framework/src/play-test/src/main/java/play/test/Helpers.java
  framework/src/play-test/src/main/java/play/test/TestServer.java
  framework/src/play-test/src/test/java/play/test/TestServerTest.java
Labels: in progress

#8742 Netty 4.1.30.Final
  framework/project/Dependencies.scala
Labels: type:updates

#8741 Fix copy/paste javadoc typo
  framework/src/play/src/main/java/play/mvc/Security.java
Labels: in progress

#8743 Add request.rmAttr(key)
  framework/project/BuildSettings.scala
  framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java
  framework/src/play/src/main/java/play/libs/typedmap/TypedMap.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/scala/play/api/libs/typedmap/TypedMap.scala
  framework/src/play/src/main/scala/play/api/mvc/Request.scala
  framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala
  framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
  framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
Labels: in progress

#8731 Java Form and DynamicForm cleanup
  framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java
  framework/src/play-java-forms/src/main/java/play/data/Form.java
Labels: in progress

#8744 Start action composition chain with call(req) not with call(ctx)
  framework/src/play/src/main/java/play/mvc/Action.java
  framework/src/play/src/main/scala/play/core/j/JavaAction.scala
Labels: in progress

#8745 Update dependencies
  framework/project/Dependencies.scala
Labels: in progress

#8718 Update Text Body Parser with US-ASCII as default charset
  documentation/manual/releases/release27/migration27/Migration27.md
  framework/project/BuildSettings.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/parsing/TextBodyParserSpec.scala
  framework/src/play/src/main/java/play/mvc/BodyParser.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala
  framework/src/play/src/test/scala/play/api/mvc/TextBodyParserSpec.scala
  framework/src/play/src/test/scala/play/mvc/TextBodyParserSpec.scala
Labels: in progress

#8740 Deprecate constructors in DefaultJPAApi which use ThreadLocal
  framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
Labels: in progress

#8750 Upgrades migration27 to fix guava version
  documentation/manual/releases/release27/migration27/Migration27.md
Labels: in progress, topic:documentation

#8714 No package declaration necessary in routes file
  framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesFileParser.scala
  framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala
  framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesModels.scala
  framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
  framework/src/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl
  framework/src/routes-compiler/src/main/twirl/play/routes/compiler/static/javaWrappers.scala.twirl
  framework/src/routes-compiler/src/main/twirl/play/routes/compiler/static/javascriptReverseRouter.scala.twirl
  framework/src/routes-compiler/src/main/twirl/play/routes/compiler/static/reverseRouter.scala.twirl
  framework/src/routes-compiler/src/test/scala/play/routes/compiler/RoutesFileParserSpec.scala
  framework/src/routes-compiler/src/test/scala/play/routes/compiler/templates/TemplatesSpec.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/app/models/UserId.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/app/router/Application.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/app/router/InstanceController.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/app/router/module/ModuleController.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/app/router/πø$7ß.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/app/utils/JavaScriptRouterGenerator.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/build.sbt
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/conf/router.module.routes
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/conf/routes
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/project/plugins.sbt
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/project/scala-sbt-0.13/Common.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/project/scala-sbt-1.0/Common.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/public/css/abcd1234-main.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/public/css/abcd1234-minmain-min.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/public/css/main.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/public/css/main.css.md5
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/public/css/minmain-min.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/public/css/minmain-min.css.md5
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/public/css/minmain.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/public/css/nonfingerprinted-minmain-min.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/public/css/nonfingerprinted-minmain.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/public/css/nonfingerprinted.css
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/test
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/tests/RouterSpec.scala
  framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/no-package-declaration-in-routes-file/tests/assets/JavaScriptRouterSpec.js
Labels: in progress

#8720 Require minimum length for secret
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/working/commonGuide/configuration/ApplicationSecret.md
  documentation/manual/working/commonGuide/production/Deploying.md
  documentation/manual/working/commonGuide/production/ProductionConfiguration.md
  documentation/manual/working/javaGuide/advanced/embedding/JavaEmbeddingPlay.md
  documentation/manual/working/scalaGuide/advanced/embedding/ScalaEmbeddingPlayAkkaHttp.md
  documentation/manual/working/scalaGuide/advanced/embedding/ScalaEmbeddingPlayNetty.md
  framework/project/BuildSettings.scala
  framework/src/play-filters-helpers/src/test/resources/application.conf
  framework/src/play-filters-helpers/src/test/scala/play/filters/csp/JavaCSPActionSpec.scala
  framework/src/play-filters-helpers/src/test/scala/play/filters/csp/JavaCSPReportSpec.scala
  framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
  framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
  framework/src/play-guice/src/test/scala/play/api/http/HttpErrorHandlerSpec.scala
  framework/src/play-integration-test/src/test/resources/application.conf
  framework/src/play-integration-test/src/test/resources/logback.xml
  framework/src/play-integration-test/src/test/scala/play/it/api/SecretConfigurationParserSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/auth/SecuritySpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsSpec.scala
  framework/src/play-jdbc/src/test/resources/application.conf
  framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala
  framework/src/play/src/test/scala/play/api/http/HttpConfigurationSpec.scala
  framework/src/play/src/test/scala/play/api/http/SecretConfigurationParserSpec.scala
  framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown/src/main/resources/application.conf
Labels: in progress
