Repository playframework/playframework, pull requests merged in 2018-04, with the labels that each got.

#8333 avoid procedure syntax
  documentation/manual/working/scalaGuide/main/tests/code/specs2/WithDbDataSpec.scala
  framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
  framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/SecureFlagSpec.scala
  framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala
  framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
  framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
  framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala
  framework/src/play-server/src/main/scala/play/core/server/ssl/DefaultSSLEngineProvider.scala
  framework/src/play-streams/src/test/scala/play/api/libs/streams/ExecutionSpec.scala
  framework/src/play-test/src/main/scala/play/api/test/Selenium.scala
  framework/src/play-test/src/main/scala/play/api/test/TestServer.scala
  framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
  framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala
  framework/src/play/src/main/scala/play/api/mvc/Cookie.scala
  framework/src/play/src/main/scala/play/core/j/HttpExecutionContext.scala
  framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
  framework/src/play/src/test/scala/play/utils/ResourcesSpec.scala
  framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
  framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
Labels: status:needs-backport

#8331 Adds cross-linking to Akka and Java SE javadocs
  framework/project/Docs.scala
Labels: status:needs-backport, topic:documentation

#8298 Update issue template to point to discuss.lightbend.com
  .github/ISSUE_TEMPLATE.md
Labels: status:needs-backport

#8328 Add documentation about Java Config
  documentation/build.sbt
  documentation/manual/working/commonGuide/configuration/ConfigFile.md
  documentation/manual/working/commonGuide/configuration/code/javaguide/configuration/MyController.java
  documentation/manual/working/javaGuide/main/config/JavaConfig.md
  documentation/manual/working/javaGuide/main/config/code/javaguide/config/MyController.java
  documentation/manual/working/javaGuide/main/config/index.toc
  documentation/manual/working/javaGuide/main/index.toc
  documentation/manual/working/scalaGuide/main/config/ScalaConfig.md
Labels: status:needs-backport, topic:documentation

#8341 Update play-ws to version 1.1.7
  framework/project/Dependencies.scala
Labels: status:needs-backport, type:updates

#8317 Configure apiURL to enable cross-linking
  framework/project/BuildSettings.scala
Labels: topic:documentation

#8351 Upgrade sbt-native-packager
  documentation/manual/working/commonGuide/production/Deploying.md
  framework/project/plugins.sbt
Labels: status:needs-backport, type:updates

#8339 New major release of HikariCP
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/releases/release27/migration27/Migration27.md
  framework/project/Dependencies.scala
  framework/src/play-jdbc/src/main/resources/reference.conf
  framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
  framework/src/play-jdbc/src/test/scala/play/api/db/HikariCPConfigSpec.scala
Labels: type:updates

#8353 Documentation test task depending on publishLocal for play-docs
  documentation/build.sbt
  framework/project/BuildSettings.scala
Labels: status:needs-backport, topic:documentation, topic:sbt

#8374 Store AsciiSet fields in ServerResultUtils
  framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
Labels: status:needs-backport

#8378 Fix LogbackLoggerConfigurator#init
  framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
Labels: status:needs-backport
