Repository playframework/playframework, pull requests merged in 2019-04, with the labels that each got.

#9144 New sbt-native-packager release
  project/plugins.sbt
Labels: status:needs-backport

#9057 Added import play.twirl.api.Html;
  documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/OpenIDController.java
Labels: status:backlog, status:needs-forwardport, topic:documentation

#9164 Update Play-WS to version 2.0.3
  core/play-integration-test/src/it/scala/play/it/server/ServerReloadingSpec.scala
  documentation/manual/releases/release27/migration27/Migration27.md
  project/Dependencies.scala
Labels: status:needs-backport, type:updates

#9166 Update akka-actor, akka-slf4j, akka-stream, ... to 2.5.22
  project/Dependencies.scala
Labels: status:needs-backport

#9172 [2.7.x]: Fix Scala 2.11 build script
  scripts/test-scala-211
Labels: topic:build/tests

#9135 [2.7.x]: Avoid using Akka and Akka HTTP snapshots for all build tasks
  scripts/it-test-scala-212
  scripts/it-test-scala-213
  scripts/scriptLib
  scripts/test-docs
  scripts/test-sbt-plugins-0_13
  scripts/test-sbt-plugins-1_0
  scripts/test-scala-212
  scripts/validate-docs
  scripts/validate-microbenchmarks
Labels: status:needs-forwardport

#9177 Result.as must also copy flash, session and cookies data
  core/play/src/main/java/play/mvc/Result.java
  core/play/src/test/java/play/mvc/ResultsTest.java
Labels: status:needs-backport, status:needs-backport-2.6, topic:java-api

#9139 Disable branch builds
  .travis.yml
Labels: status:needs-backport

#9185 Update sbt-twirl to 1.4.1
  documentation/project/plugins.sbt
Labels: status:needs-backport

#9148 Updates swagger list
  documentation/manual/ModuleDirectory.md
Labels: status:needs-backport

#9183 Detect twirl template changes when using maven layout
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
  dev-mode/sbt-plugin/src/sbt-test/README.md
  dev-mode/sbt-plugin/src/sbt-test/maven-layout/twirl-reload/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/maven-layout/twirl-reload/project/Build.scala
  dev-mode/sbt-plugin/src/sbt-test/maven-layout/twirl-reload/project/plugins.sbt
  dev-mode/sbt-plugin/src/sbt-test/maven-layout/twirl-reload/src/changes/index.scala.html.1
  dev-mode/sbt-plugin/src/sbt-test/maven-layout/twirl-reload/src/changes/index.scala.html.2
  dev-mode/sbt-plugin/src/sbt-test/maven-layout/twirl-reload/src/main/resources/application.conf
  dev-mode/sbt-plugin/src/sbt-test/maven-layout/twirl-reload/src/main/resources/logback.xml
  dev-mode/sbt-plugin/src/sbt-test/maven-layout/twirl-reload/src/main/resources/routes
  dev-mode/sbt-plugin/src/sbt-test/maven-layout/twirl-reload/src/main/scala/controllers/HomeController.scala
  dev-mode/sbt-plugin/src/sbt-test/maven-layout/twirl-reload/src/main/twirl/views/index.scala.html
  dev-mode/sbt-plugin/src/sbt-test/maven-layout/twirl-reload/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/build.sbt
  documentation/manual/gettingStarted/Anatomy.md
Labels: status:needs-backport

#9192 Netty 4.1.35
  project/Dependencies.scala
Labels: status:needs-backport

#9188 Fix integration tests on Java 11 & enforce
  .travis.yml
  core/play-integration-test/src/it/scala/play/it/test/OkHttpEndpointSupport.scala
Labels: status:needs-backport, topic:jdk-next

#9200 Follow sbt 1 recommendation when integrating with sbt-release
  project/Release.scala
Labels: status:needs-forwardport, topic:build/tests

#9203 [master]: forward port fixes to release process
  project/BuildSettings.scala
  project/Release.scala
Labels: topic:build/tests

#9204 [2.6.x]: backport fixes to release process
  project/BuildSettings.scala
  project/Release.scala
Labels: topic:build/tests

#9217 [2.7.x]: Fix play-docs artifact generation
  project/Docs.scala
Labels: status:needs-backport-2.6, status:needs-forwardport, topic:build/tests

#9191 Fixed an issue where RequestHeader.path was decoded when using AkkaHt…
  core/play-integration-test/src/test/scala/play/it/http/RequestHeadersSpec.scala
  transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
  transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
  transport/server/play-server/src/main/scala/play/core/server/common/PathAndQueryParser.scala
Labels: status:needs-forwardport
