Repository playframework/playframework, pull requests merged in 2019-09, with the labels that each got.

#9644 Fix "memory leak" in DelegatingMultipartFormDataBodyParser
  core/play/src/main/java/play/mvc/BodyParser.java
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
  project/BuildSettings.scala
Labels: type:defect

#9647 Make Scala's file/temporaryFile parser respect max length
  core/play/src/main/java/play/mvc/BodyParser.java
  core/play/src/main/scala/play/api/mvc/BodyParsers.scala
  documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala
Labels: type:defect

#9655 Add back "-subpackages play" on pre-Java 11
  project/Docs.scala
Labels: status:block-merge

#9659 Send HSTS header when X-Forwarded-Proto header is 'https'
  documentation/manual/releases/release28/migration28/Migration28.md
  web/play-filters-helpers/src/main/resources/reference.conf
  web/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala
  web/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala
Labels: status:needs-backport

#9649 BodyParsers check Content-Length header if it exceeds maxLength
  core/play/src/main/java/play/mvc/BodyParser.java
  core/play/src/main/scala/play/api/mvc/BodyParsers.scala
  core/play/src/test/scala/play/api/mvc/MaxLengthBodyParserSpec.scala
  core/play/src/test/scala/play/mvc/DummyDelegatingMultipartFormDataBodyParser.java
  core/play/src/test/scala/play/mvc/MaxLengthBodyParserSpec.scala
Labels: type:improvement

#9675 Document how to use reverse router to test controllers in Java
  documentation/manual/working/javaGuide/main/tests/JavaFunctionalTest.md
  documentation/manual/working/javaGuide/main/tests/code/javaguide.tests.routes
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/FunctionalTest.java
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/controllers/HomeController.java
Labels: topic:documentation
