Repository playframework/playframework, pull requests merged in 2019-03, with the labels that each got.

#9068 Fix documentation external links
  documentation/manual/about/Philosophy.md
  documentation/manual/releases/release23/Migration23.md
  documentation/manual/releases/release26/migration26/Migration26.md
  documentation/manual/tutorial/Tutorials.md
  documentation/manual/working/commonGuide/assets/AssetsJSHint.md
  documentation/manual/working/commonGuide/assets/AssetsLess.md
  documentation/manual/working/commonGuide/assets/AssetsOverview.md
  documentation/manual/working/commonGuide/filters/SecurityHeaders.md
  documentation/manual/working/javaGuide/main/tests/JavaTest.md
Labels: in progress, status:needs-backport, status:to-review, topic:documentation

#9063 Added comment syntax to a comment
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
Labels: status:needs-forwardport, topic:documentation

#9062 fixed typo in Shutdown.md
  documentation/manual/working/commonGuide/shutdown/Shutdown.md
Labels: status:needs-forwardport, topic:documentation

#9051 Form input helper argument "_error" should handle String
  core/play/src/main/scala/views/helper/Helpers.scala
  core/play/src/test/scala/views/html/helper/HelpersSpec.scala
Labels: status:needs-backport

#9049 Netty: Make sure to init static Epoll/UnixChannelOption members
  dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/app/controllers/HomeController.scala
  dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/conf/application.conf
  dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/conf/logback.xml
  dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/conf/routes
  dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/expected-application-log.txt
  dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/project/Build.scala
  dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/project/plugins.sbt
  dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/disabled-assets-jar/build.sbt
  transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
Labels: status:needs-backport

#9064 Form was missing a closing bracket after User
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
Labels: status:needs-forwardport, topic:documentation

#9016 Added Security.Authenticator changes
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
Labels: status:needs-backport, topic:documentation

#8988 Fixes issue #245, Hello World link goes to wrong example
  documentation/manual/gettingStarted/Anatomy.md
  documentation/manual/gettingStarted/Introduction.md
  documentation/manual/gettingStarted/LearningExamples.md
  documentation/manual/gettingStarted/NewApplication.md
  documentation/manual/gettingStarted/PlayConsole.md
  documentation/manual/gettingStarted/Requirements.md
  documentation/manual/gettingStarted/index.toc
Labels: status:needs-backport, topic:documentation

#8990 fix jmh Microbenchmarks
  build.sbt
  core/play-microbenchmark/src/test/scala/play/microbenchmark/it/HelloWorldBenchmark.scala
  scripts/validate-microbenchmarks
Labels: topic:build/tests

#9074 Scalafmt 2.0.0-RC5
  .scalafmt.conf
  scripts/scalafmt
Labels: status:needs-backport

#9072 Add javafmt to travis build
  core/play/src/main/java/play/mvc/Results.java
  core/play/src/main/java/play/mvc/StatusHeader.java
  scripts/validate-code
  web/play-java-forms/src/test/java/play/data/LoginUser.java
Labels: in progress, status:needs-backport, status:to-review, topic:build/tests

#9077 Fixed early response warning on chunked requests
  transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
Labels: in progress, status:needs-backport

#9081 Netty 4.1.34
  project/Dependencies.scala
Labels: status:needs-backport

#9083 Add a "status:needs-backport-2.6" label
  .github/settings.yml
Labels: in progress

#9075 Upgrade twirl (in docs project) and sbt-native-packager
  documentation/project/plugins.sbt
  project/plugins.sbt
Labels: status:needs-backport

#9082 [2.6] examples: drop links to example.lightbend.com
  documentation/manual/tutorial/Tutorials.md
Labels: in progress

#9089 Avoid bindableOption inferring an over-specific type
  core/play/src/main/scala/play/api/mvc/Binders.scala
Labels: in progress

#9097 Show generic configurations in Production Configuration docs
  documentation/manual/working/commonGuide/production/ProductionConfiguration.md
Labels: status:needs-backport, topic:documentation

#9052 Fallback to UTF-8 when reading generated source file
  dev-mode/routes-compiler/src/main/scala/play/routes/compiler/RoutesCompiler.scala
Labels: status:needs-backport

#9084 Fix fork-join-executor config in docs
  documentation/manual/working/javaGuide/main/akka/JavaAkka.md
  documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/akka.conf
  documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md
Labels: status:needs-backport, topic:documentation

#9090 Upgrade guava
  documentation/manual/releases/release27/migration27/Migration27.md
  project/Dependencies.scala
Labels: status:needs-backport

#9094 Add 127.0.0.1 to allowed hosts filter
  web/play-filters-helpers/src/main/resources/reference.conf
Labels: status:needs-backport

#9056 Added package controllers to the template
  documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/OpenIDController.java
Labels: status:backlog, status:needs-forwardport, topic:documentation

#9095 In DEV mode props from args should override props from javaOptions
  dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala
Labels: status:needs-backport

#9096 In DEV mode props from args should (always) override devSettings
  dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala
  dev-mode/run-support/src/test/scala/play/runsupport/FilterArgsSpec.scala
Labels: status:needs-backport

#9100 Update dependencies
  project/Dependencies.scala
Labels: status:needs-backport, type:updates

#9109 Upgrade dependencies
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: status:needs-backport

#9099 Make sure play.server.http(s).port/address always gets set in DEV mode
  dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala
Labels: status:needs-backport

#9114 Tune the AsyncAppender following the overops blogpost on the link
  core/play-logback/src/main/resources/logback-play-default.xml
Labels: status:needs-backport, topic:documentation

#9116 akka-http 10.1.8
  project/Dependencies.scala
Labels: status:needs-backport, type:updates

#9110 Allow to set port(s) and address via env variables
  dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala
  documentation/manual/working/commonGuide/configuration/ConfigFile.md
  documentation/manual/working/commonGuide/production/ProductionConfiguration.md
  transport/server/play-server/src/main/resources/reference.conf
Labels: status:needs-backport

#9121 Synchronize evolutions code
  persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
Labels: status:needs-backport

#9132 Configure travis to build only stable branches and tags
  .travis.yml
Labels: status:needs-backport, topic:build/tests

#9133 Run scripted tests on Java 11
  .travis.yml
Labels: status:needs-backport

#9001 Use sbt 1 to build Play itself
  build.sbt
  documentation/build.sbt
  documentation/project/build.properties
  documentation/project/plugins.sbt
  project/BuildSettings.scala
  project/Docs.scala
  project/Release.scala
  project/Tasks.scala
  project/build.properties
  project/plugins.sbt
  scripts/test-sbt-plugins-0_13
  scripts/test-sbt-plugins-1_0
  scripts/test-scala-213
Labels: status:backlog, status:needs-backport, status:needs-backport-2.6, topic:sbt, type:updates

#9134 Update Slack notification for Travis builds
  .travis.yml
Labels: status:needs-backport, status:needs-backport-2.6, topic:build/tests

#9124 Split cron build extra opts
  scripts/scriptLib
Labels: status:block-merge, status:needs-backport

#9141 Update Slack secret configuration
  .travis.yml
Labels: status:needs-backport, status:needs-backport-2.6, topic:build/tests

#9093 Fixes HTTP and HTTPS port binding in DEV mode
  dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala
  transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala
Labels: status:needs-backport

#9143 Update sbt-header to version 5.2.0
  documentation/project/plugins.sbt
  project/plugins.sbt
Labels: status:needs-backport, topic:build/tests

#9142 [2.6.x]: Update to Akka 2.5.21
  core/play-integration-test/src/test/scala/play/it/libs/JavaWSSpec.scala
  core/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala
  project/Dependencies.scala
Labels: type:updates
