Repository playframework/playframework, pull requests merged in 2019-02, with the labels that each got.

#9008 Add Scala 2.13 support to highlights
  documentation/manual/releases/release27/Highlights27.md
Labels: in progress, status:needs-backport, topic:documentation

#9007 Check binary compatibility for play-caffeine-cache
  framework/build.sbt
Labels: in progress, status:needs-backport

#9009 Update Akka and some of our own dependencies
  framework/project/Dependencies.scala
Labels: in progress, status:needs-backport, type:updates

#9010 Delete playframework-ja from the list of user groups
  documentation/manual/about/PlayUserGroups.md
Labels: status:needs-backport

#9011 Fix typo "PahBindable" -> "PathBindable"
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
Labels: status:needs-forwardport, topic:documentation

#9013 sbt version 1.2.8 in [Migration27.md]
  documentation/manual/releases/release27/migration27/Migration27.md
Labels: status:needs-backport, topic:documentation

#9014 guava 27.0.1
  documentation/manual/releases/release27/migration27/Migration27.md
  framework/project/Dependencies.scala
Labels: status:needs-backport, type:updates

#9017 HikariCP minor release
  framework/project/Dependencies.scala
Labels: status:needs-backport

#9040 Fix spelling of sbt
  build.sbt
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
  documentation/README.md
  documentation/manual/ModuleDirectory.md
  documentation/manual/about/Philosophy.md
  documentation/manual/gettingStarted/Anatomy.md
  documentation/manual/gettingStarted/IDE.md
  documentation/manual/gettingStarted/Installing.md
  documentation/manual/gettingStarted/PlayConsole.md
  documentation/manual/hacking/Documentation.md
  documentation/manual/hacking/Translations.md
  documentation/manual/releases/release21/Highlights21.md
  documentation/manual/releases/release22/Migration22.md
  documentation/manual/releases/release24/Highlights24.md
  documentation/manual/releases/release24/migration24/Migration24.md
  documentation/manual/releases/release26/migration26/Migration26.md
  documentation/manual/releases/release26/migration26/WSMigration26.md
  documentation/manual/working/commonGuide/assets/AssetsOverview.md
  documentation/manual/working/commonGuide/build/Build.md
  documentation/manual/working/commonGuide/build/BuildOverview.md
  documentation/manual/working/commonGuide/build/code/runhook.sbt
  documentation/manual/working/commonGuide/build/index.toc
  documentation/manual/working/commonGuide/build/sbtCookbook.md
  documentation/manual/working/commonGuide/build/sbtDebugging.md
  documentation/manual/working/commonGuide/build/sbtDependencies.md
  documentation/manual/working/commonGuide/build/sbtSettings.md
  documentation/manual/working/commonGuide/build/sbtSubProjects.md
  documentation/manual/working/commonGuide/configuration/SettingsLogger.md
  documentation/manual/working/commonGuide/filters/Filters.md
  documentation/manual/working/commonGuide/production/Deploying.md
  documentation/manual/working/commonGuide/server/AkkaHttpServer.md
  documentation/manual/working/javaGuide/main/forms/JavaForms.md
  documentation/manual/working/javaGuide/main/sql/JavaDatabase.md
  documentation/manual/working/javaGuide/main/sql/JavaJPA.md
  documentation/manual/working/javaGuide/main/tests/JavaTest.md
  documentation/manual/working/scalaGuide/main/http/ScalaRouting.md
  documentation/manual/working/scalaGuide/main/sql/ScalaDatabase.md
  documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md
  documentation/project/plugins.sbt
  project/BuildSettings.scala
  project/Docs.scala
  transport/server/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/project/Build.scala
  transport/server/play-akka-http-server/src/sbt-test/akka-http/system-property/project/Build.scala
Labels: in progress

#9033 Add probot settings
  .github/settings.yml
Labels: in progress

#9031 Correctly read netty channel options
  documentation/manual/working/commonGuide/configuration/SettingsNetty.md
  transport/server/play-netty-server/src/main/resources/reference.conf
  transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
Labels: status:needs-backport

#9025 Update Akka and sbtNativePackager
  core/play-integration-test/src/it/scala/play/it/libs/JavaWSSpec.scala
  core/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala
  project/Dependencies.scala
  project/plugins.sbt
Labels: status:in-progress, status:needs-backport

#9044 [2.7.x] Allow to set inline content-disposition AND filename together
  core/play/src/main/java/play/mvc/Results.java
  core/play/src/main/java/play/mvc/StatusHeader.java
Labels: status:ready

#8989 Disallow @Singleton java actions to avoid data leaks between requests
  core/play-integration-test/src/it/java/play/it/http/ActionCompositionOrderTest.java
  core/play-integration-test/src/it/scala/play/it/http/JavaActionCompositionSpec.scala
  core/play/src/main/scala/play/core/j/JavaAction.scala
Labels: status:backlog

#9038 Allow to set inline content-disposition AND filename together
  core/play/src/main/java/play/mvc/Results.java
  core/play/src/main/java/play/mvc/StatusHeader.java
  core/play/src/main/scala/play/api/mvc/Results.scala
  project/BuildSettings.scala
Labels: status:needs-backport

#9041 Java requires javaWs not ws
  documentation/manual/working/javaGuide/main/ws/code/javaws.sbt
Labels: status:needs-forwardport, topic:documentation

#9021 Changed variable name
  documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
Labels: status:backlog, topic:documentation

#9053 Correct native-packager version in docs
  documentation/manual/working/commonGuide/production/Deploying.md
Labels: status:needs-backport

#9048 Add status(...), ok(...), methods with Path param
  core/play/src/main/java/play/mvc/Results.java
Labels: status:needs-backport

#9054 Update the Mergify config
  .mergify.yml
Labels: in progress

#9050 Change code standard links in CONTRIBUTING
  CONTRIBUTING.md
Labels: in progress

#9047 Document the use of maven central repository
  documentation/manual/hacking/Repositories.md
Labels: status:needs-backport, status:to-review, topic:documentation

#9035 Added ArrayList to imports
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
Labels: status:needs-backport

#9018 Include information about providing a custom CSP for just one route
  documentation/manual/working/commonGuide/filters/CspFilter.md
Labels: status:backlog, status:in-progress

#9036 For Java javaWs needs to be added to build.sbt
  documentation/manual/working/javaGuide/main/ws/JavaWS.md
Labels: status:needs-forwardport

#9060 Build cleanup
  build.sbt
  project/BuildSettings.scala
Labels: in progress

#9065 [2.7.x] Build cleanup
  build.sbt
  project/BuildSettings.scala
Labels: in progress
