Repository playframework/playframework, pull requests merged in 2019-05, with the labels that each got.

#9240 Update sbt-java-formatter to version 0.4.4
  core/play/src/main/java/play/inject/Module.java
  core/play/src/main/java/play/mvc/BodyParser.java
  core/play/src/main/java/play/mvc/Http.java
  core/play/src/main/java/play/mvc/Result.java
  core/play/src/test/java/play/mvc/RangeResultsTest.java
  documentation/build.sbt
  documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/csp/MyDynamicCSPAction.java
  documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/remove/MyAppComponents.java
  documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaStream.java
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/GitHubClient.java
  documentation/project/plugins.sbt
  persistence/play-java-jpa/src/test/java/play/db/jpa/JPAApiTest.java
  persistence/play-jdbc-evolutions/src/main/java/play/db/evolutions/EvolutionsReader.java
  project/plugins.sbt
  scripts/scriptLib
  web/play-java-forms/src/main/java/play/data/DynamicForm.java
  web/play-java-forms/src/main/java/play/data/Form.java
Labels: status:needs-backport, status:needs-backport-2.6, topic:build/tests, type:updates

#9246 Change Scala.asScala to widen Seqs (covariance)
  core/play/src/main/java/play/i18n/Langs.java
  core/play/src/main/java/play/i18n/MessagesApi.java
  core/play/src/main/java/play/libs/Scala.java
Labels: topic:java-api

#9244 [2.6.x] Fix flaky test for Java Cache docs
  documentation/manual/working/javaGuide/main/cache/code/javaguide/cache/JavaCache.java
Labels: topic:build/tests

#9236 Use Akka 2.6.0-M1
  project/Dependencies.scala
  scripts/scriptLib
Labels: topic:build/tests, type:updates, type:upstream

#9248 [2.6.x]: Fix version after release
  version.sbt
Labels: topic:build/tests

#9213 Get rid of some extra Akka "performance" tweaks, refs #7242
  core/play/src/main/resources/play/reference-overrides.conf
Labels: status:to-review

#9292 Remove (Java 11) deprecated usage of Class#newInstance
  core/play/src/main/scala/play/api/ApplicationLoader.scala
Labels: status:needs-backport

#9302 Renamed methods back to their original names
  cache/play-cache/src/main/java/play/cache/AsyncCacheApi.java
  cache/play-cache/src/main/java/play/cache/DefaultAsyncCacheApi.java
  cache/play-cache/src/main/java/play/cache/DefaultSyncCacheApi.java
  cache/play-cache/src/main/java/play/cache/SyncCacheApi.java
  cache/play-cache/src/main/java/play/cache/SyncCacheApiAdapter.java
  cache/play-caffeine-cache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
  cache/play-ehcache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
  core/play/src/main/java/play/libs/Files.java
  core/play/src/main/java/play/mvc/Http.java
  core/play/src/main/java/play/mvc/Result.java
  core/play/src/main/scala/play/api/libs/Files.scala
  core/play/src/main/scala/play/core/j/JavaHelpers.scala
  core/play/src/test/java/play/mvc/ResultsTest.java
  core/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
  documentation/manual/working/javaGuide/main/cache/code/javaguide/cache/JavaCache.java
  documentation/manual/working/javaGuide/main/cache/code/javaguide/ehcache/JavaEhCache.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java
  documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
  project/BuildSettings.scala
Labels: status:block-merge

#9309 Make JavaScriptReverseRouter Http.Context free
  core/play/src/main/java/play/routing/JavaScriptReverseRouter.java
  documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/controllers/Application.java
  project/BuildSettings.scala
Labels: status:block-merge

#9317 Build cron jobs!!
  .travis.yml
Labels: status:needs-backport, status:needs-backport-2.6

#9306 Improve 2.5 migration guide
  documentation/manual/releases/release25/migration25/CryptoMigration25.md
  documentation/manual/releases/release25/migration25/Migration25.md
Labels: topic:documentation

#9332 Deprecate JavaContextComponents
  core/play-guice/src/test/scala/play/api/http/HttpErrorHandlerSpec.scala
  core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
  core/play-java/src/main/java/play/routing/RoutingDsl.java
  core/play-java/src/main/java/play/routing/RoutingDslComponents.java
  core/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
  core/play-java/src/main/scala/play/routing/RoutingDslModule.scala
  core/play/src/main/java/play/BuiltInComponents.java
  core/play/src/main/java/play/BuiltInComponentsFromContext.java
  core/play/src/main/java/play/components/HttpErrorHandlerComponents.java
  core/play/src/main/java/play/core/j/MappedJavaHandlerComponents.java
  core/play/src/main/scala/play/api/Application.scala
  core/play/src/main/scala/play/core/j/JavaAction.scala
  core/play/src/main/scala/play/core/j/JavaHelpers.scala
  core/play/src/main/scala/play/core/j/JavaHttpErrorHandlerAdapter.scala
  documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/FiltersTest.java
  documentation/manual/working/javaGuide/advanced/routing/code/javaguide/advanced/routing/JavaRoutingDsl.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/SimpleHttpRequestHandler.java
  project/BuildSettings.scala
  testkit/play-specs2/src/main/scala/play/api/test/Specs.scala
  testkit/play-test/src/main/java/play/test/Helpers.java
  web/play-filters-helpers/src/main/java/play/filters/components/CSRFComponents.java
  web/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala
  web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFFilter.scala
  web/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
  web/play-filters-helpers/src/main/scala/play/filters/hosts/AllowedHostsFilter.scala
Labels: type:deprecated-feature

#9337 Refactoring Java's Results and StatusHeader class
  core/play/src/main/java/play/mvc/Results.java
  core/play/src/main/java/play/mvc/StatusHeader.java
Labels: status:needs-backport

#9247 Documentation typos
  documentation/manual/working/scalaGuide/main/json/ScalaJsonHttp.md
  documentation/manual/working/scalaGuide/main/json/code/ScalaJsonHttpSpec.scala
Labels: topic:documentation

#9342 [2.7] Enable Akka 2.5 snapshots, including for Scala 2.13, in all CI tasks
  project/Release.scala
  scripts/it-test-scala-212
  scripts/it-test-scala-213
  scripts/publish-local
  scripts/scriptLib
  scripts/test-docs
  scripts/test-sbt-plugins-0_13
  scripts/test-sbt-plugins-1_0
  scripts/test-scala-212
  scripts/test-scala-213
  scripts/validate-docs
  scripts/validate-microbenchmarks
Labels: status:needs-forwardport

#8828 Remove debug options from AHC-WS
  documentation/manual/releases/release28/migration28/Migration28.md
  transport/client/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSModule.scala
Labels: status:ready

#9350 Fix scaladoc
  core/play/src/main/scala/play/api/mvc/Results.scala
Labels: status:needs-backport
