Repository playframework/playframework, pull requests merged in 2019-11, with the labels that each got.

#9800 Revising grammar in philosophy
  documentation/manual/about/Philosophy.md
Labels: status:needs-forwardport

#9798 Correctly direct-access default values of form fields
  web/play-java-forms/src/main/java/play/data/Form.java
  web/play-java-forms/src/test/java/play/data/Subtask.java
  web/play-java-forms/src/test/scala/play/data/FormSpec.scala
Labels: status:needs-backport

#9806 Links in docs should point to "latest"
  documentation/manual/tutorial/ImplementingHelloWorld.md
  documentation/manual/working/commonGuide/production/Deploying.md
  documentation/manual/working/javaGuide/main/ws/JavaWS.md
Labels: topic:documentation

#9828 Update play libraries to GA releases
  core/play-integration-test/src/it/scala/play/it/http/IdleTimeoutSpec.scala
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/commonGuide/production/Deploying.md
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  documentation/project/plugins.sbt
  project/Dependencies.scala
  project/Docs.scala
  project/plugins.sbt
Labels: status:block-merge
