Repository playframework/playframework, pull requests merged in 2019-08, with the labels that each got.

#8999 Dependency Injection for typed actors
  core/play-guice/src/main/java/play/libs/akka/AkkaGuiceSupport.java
  core/play-guice/src/main/scala/play/api/libs/concurrent/ActorModule.scala
  core/play-guice/src/main/scala/play/api/libs/concurrent/AkkaGuiceSupport.scala
  core/play-guice/src/main/scala/play/api/libs/concurrent/TypedActorRefProvider.scala
  core/play-guice/src/main/scala/play/api/libs/concurrent/TypedAkka.scala
  documentation/manual/releases/release28/Highlights28.md
  documentation/manual/working/commonGuide/akka/AkkaTyped.md
  documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/AkkaTypedDocTest.java
  documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/AppComponents.java
  documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/AppModule.java
  documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/ConfiguredActor.java
  documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/HelloActor.java
  documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/Main.java
  documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/AkkaTypedDocSpec.scala
  documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/fp/AppComponents.scala
  documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/fp/AppModule.scala
  documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/fp/ConfiguredActor.scala
  documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/fp/HelloActor.scala
  documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/fp/Main.scala
  documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/AppModule.scala
  documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/ConfiguredActor.scala
  documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/HelloActor.scala
  documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/Main.scala
  documentation/manual/working/commonGuide/akka/index.toc
  documentation/manual/working/commonGuide/index.toc
  project/Dependencies.scala
Labels: type:improvement

#9556 Bump MaxMetaspaceSize for scripted tests
  project/BuildSettings.scala
Labels: status:needs-backport, status:needs-backport-2.6

#9563 Update Tutorials.md
  documentation/manual/tutorial/Tutorials.md
Labels: status:needs-forwardport

#9544 Add full name of WS abbreviation to docs
  documentation/manual/working/javaGuide/main/ws/JavaWS.md
  documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
Labels: status:needs-backport

#9603 Doc fix: CompletableFuture instead of CompletionStage
  documentation/manual/working/javaGuide/main/async/JavaAsync.md
  documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaAsync.java
Labels: status:needs-backport, status:needs-backport-2.6, topic:documentation

#9607 Update sbt-native-packager to 1.4.1
  project/plugins.sbt
Labels: status:blocked
