Repository playframework/playframework, pull requests merged in 2019-01, with the labels that each got.

#8889 Add copy methods to temporary files
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/working/javaGuide/main/upload/code/javaguide/fileupload/controllers/HomeController.java
  framework/src/play/src/main/java/play/libs/Files.java
  framework/src/play/src/main/scala/play/api/libs/Files.scala
  framework/src/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
Labels: in progress

#8886 Add tests for HttpEntity.Streamed content length header
  documentation/manual/releases/release27/Highlights27.md
  framework/src/play-integration-test/src/it/scala/play/it/action/HeadActionSpec.scala
  framework/src/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
  framework/src/play-integration-test/src/it/scala/play/it/http/ScalaResultsHandlingSpec.scala
  framework/src/play-integration-test/src/it/scala/play/it/tools/HttpBin.scala
  framework/src/play/src/main/java/play/mvc/StatusHeader.java
  framework/src/play/src/main/scala/play/api/mvc/Results.scala
Labels: in progress, status:needs-backport

#8875 Execute evolution scripts in DEV mode
  framework/project/BuildSettings.scala
  framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
  framework/src/sbt-plugin/src/sbt-test/README.md
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/app/controllers/UsersController.java
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/app/models/User.java
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/app/views/index.scala.html
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/app/views/main.scala.html
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/build.sbt
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/changes/2.sql
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/changes/3.sql
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/conf/application.conf
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/conf/evolutions/default/1.sql
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/conf/routes
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/project/Build.scala
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/project/plugins.sbt
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/public/images/favicon.png
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-false/test
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/app/controllers/UsersController.java
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/app/models/User.java
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/app/views/index.scala.html
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/app/views/main.scala.html
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/build.sbt
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/changes/2.sql
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/conf/application.conf
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/conf/evolutions/default/1.sql
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/conf/routes
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/project/Build.scala
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/project/plugins.sbt
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/public/images/favicon.png
  framework/src/sbt-plugin/src/sbt-test/evolutions/auto-apply-true/test
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/app/controllers/GroupsController.java
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/app/controllers/UsersController.java
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/app/models/Group.java
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/app/models/User.java
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/app/views/groups.scala.html
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/app/views/main.scala.html
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/app/views/users.scala.html
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/build.sbt
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/changes/groups/2.sql
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/changes/users/2.sql
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/conf/application.conf
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/conf/evolutions/groups/1.sql
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/conf/evolutions/users/1.sql
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/conf/routes
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/project/Build.scala
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/project/plugins.sbt
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/public/images/favicon.png
  framework/src/sbt-plugin/src/sbt-test/evolutions/multiple-databases/test
Labels: in progress, status:needs-backport

#8905 Hibernate 5.4.0
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  framework/project/Dependencies.scala
Labels: in progress

#8906 Scala 2.12.8 and latest sbt
  framework/bin/test-sbt-plugins-1_0
Labels: in progress

#8854 Fix regression in trailing slash handling
  framework/src/play/src/main/scala/play/api/routing/Router.scala
  framework/src/play/src/test/scala/play/api/routing/RouterSpec.scala
  framework/src/play/src/test/scala/play/core/routing/GeneratedRouterSpec.scala
  framework/src/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl
  framework/src/routes-compiler/src/test/scala/play/routes/compiler/RoutesFileParserSpec.scala
Labels: in progress, status:needs-backport

#8898 Java forms bind `multipart/form-data` file uploads
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/working/javaGuide/main/forms/JavaForms.md
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/u1/User.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/u4/User.java
  framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java
  framework/src/play-java-forms/src/main/java/play/data/Form.java
  framework/src/play-java-forms/src/test/java/play/data/Thesis.java
  framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
  framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
Labels: in progress, type:feature

#8916 Correct order of params in doc example
  documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/controllers/Application.java
Labels: in progress, status:needs-backport

#8917 updated dependencies
  framework/project/Dependencies.scala
Labels: in progress

#8918 Fail less hard on Java 11
  framework/project/BuildSettings.scala
Labels: in progress

#8919 Re-adds support for Scala 2.11 and fix compilation
  .travis.yml
  documentation/build.sbt
  framework/bin/test-scala-211
  framework/build.sbt
  framework/project/BuildSettings.scala
  framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
  framework/src/play-java/src/main/scala-2.13.0-M3/play/core/j/JavaImplicitConversions.scala
  framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
  framework/src/play/src/main/java/play/mvc/Filter.java
  framework/src/play/src/main/scala/play/core/routing/GeneratedRouter.scala
Labels: in progress

#8909 Add API additions to 2.7 highlights
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/releases/release27/migration27/Migration27.md
Labels: in progress, status:needs-backport, topic:documentation

#8903 issue #8892 - added http status code "428 precondition required".
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/java/play/mvc/Results.java
  framework/src/play/src/main/scala/play/api/http/StandardValues.scala
  framework/src/play/src/main/scala/play/api/mvc/Results.scala
Labels: status:needs-backport

#8930 Fix class literal syntax in the 2.7 migration guide
  documentation/manual/releases/release27/migration27/Migration27.md
Labels: in progress

#8922 Build using AdoptOpenJDK 8 & 11
  .travis.yml
Labels: review

#8936 Enable MiMa check against 2.7.0-RC9
  framework/project/BuildSettings.scala
Labels: in progress, merge-when-green

#8913 Add FilePart.fileSize
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java
  documentation/manual/working/javaGuide/main/upload/code/javaguide/fileupload/controllers/HomeController.java
  documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
  framework/src/play-integration-test/src/it/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
  framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
  framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java
  framework/src/play/src/main/java/play/mvc/BodyParser.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/java/play/mvc/MultipartFormatter.java
  framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala
  framework/src/play/src/main/scala/play/core/formatters/Multipart.scala
  framework/src/play/src/main/scala/play/core/j/JavaParsers.scala
  framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
Labels: in progress, status:needs-backport

#8944 FilePart backporting
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java
  documentation/manual/working/javaGuide/main/upload/code/javaguide/fileupload/controllers/HomeController.java
  documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
  framework/build.sbt
  framework/src/play-integration-test/src/it/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
  framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
  framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java
  framework/src/play/src/main/java/play/mvc/BodyParser.java
  framework/src/play/src/main/java/play/mvc/Http.java
  framework/src/play/src/main/java/play/mvc/MultipartFormatter.java
  framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala
  framework/src/play/src/main/scala/play/core/formatters/Multipart.scala
  framework/src/play/src/main/scala/play/core/j/JavaParsers.scala
  framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
Labels: in progress

#8915 Rename bodyMultipart(...) which actually saves a RawBuffer
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java
  framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java
  framework/src/play/src/main/java/play/mvc/Http.java
Labels: in progress, status:needs-backport

#8924 Add multipart tests for arrays
  framework/src/play-integration-test/src/it/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
Labels: in progress, status:needs-backport

#8943 Implement ApplicationEvolutions.isUpToDate
  documentation/manual/releases/release27/migration27/Migration27.md
  framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
Labels: in progress, status:needs-backport

#8949 typo
  documentation/manual/tutorial/Tutorials.md
Labels: in progress, status:needs-backport

#8950 renames isUpToDate to upToDate
  documentation/manual/releases/release27/migration27/Migration27.md
  framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
Labels: in progress, status:needs-backport

#8933 Update ScalaRouting.md sird to be uppercase
  documentation/manual/working/scalaGuide/main/http/ScalaRouting.md
Labels: status:needs-forwardport, topic:documentation

#8923 No need to set header, will be set automatically
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java
Labels: in progress, status:needs-backport

#8951 Mergify
  .mergify.yml
Labels: in progress

#8958 [2.7.x] Fix GC bug and API for TemporaryFile move and copy methods
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
  framework/build.sbt
  framework/src/play/src/main/java/play/libs/Files.java
  framework/src/play/src/main/scala/play/api/libs/Files.scala
  framework/src/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
Labels: in progress, status:needs-forwardport

#8960 Add docs for 2.8 release ;)
  documentation/manual/Home.md
  documentation/manual/LatestRelease.md
  documentation/manual/releases/index.toc
  documentation/manual/releases/release28/Highlights28.md
  documentation/manual/releases/release28/index.toc
  documentation/manual/releases/release28/migration28/Migration28.md
  documentation/manual/releases/release28/migration28/index.toc
Labels: topic:documentation

#8961 [master] Fix GC bug and API for TemporaryFile move and copy methods
  documentation/manual/releases/release27/migration27/Migration27.md
  documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
  framework/src/play/src/main/java/play/libs/Files.java
  framework/src/play/src/main/scala/play/api/libs/Files.scala
  framework/src/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
Labels: in progress

#8964 Mergify should squash
  .mergify.yml
Labels: in progress

#8929 specs2 upgrade
  framework/project/Dependencies.scala
Labels: in progress, status:needs-backport

#8963 Honour user's choice of ServerProvider
  framework/src/play-specs2/src/main/scala/play/api/test/Specs.scala
  framework/src/play-test/src/main/scala/play/api/test/TestServerFactory.scala
Labels: in progress, status:needs-forwardport

#8970 Handle non-JDK8 apidocs (cont'd)
  framework/project/BuildSettings.scala
Labels: in progress

#8975 [master] Forward port documentation fixes
  documentation/manual/tutorial/ImplementingHelloWorld.md
  documentation/manual/working/commonGuide/configuration/ConfigFile.md
Labels: topic:documentation

#8976 [2.7.x] Forward port documentation fixes
  documentation/manual/releases/release25/migration25/Migration25.md
  documentation/manual/tutorial/ImplementingHelloWorld.md
  documentation/manual/working/commonGuide/configuration/ConfigFile.md
Labels: topic:documentation

#8977 Hibernate Validator upgrade (critical bugfix)
  framework/project/Dependencies.scala
Labels: status:needs-backport

#8978 Upgrade twirl and play-ws-standalone to final releases
  framework/project/Dependencies.scala
  framework/project/plugins.sbt
Labels: status:needs-backport

#8973 [2.7.x] Use error.invalid when form binding fails and messages are empty
  framework/src/play-java-forms/src/main/java/play/data/Form.java
  framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java
Labels: status:needs-forwardport

#8995 publishLocal for all Scala versions (in daily cron build)
  framework/bin/publish-local
Labels: merge-when-green, status:needs-backport

#8994 Hightlights new Router.orElse method
  documentation/manual/releases/release27/Highlights27.md
Labels: in progress, merge-when-green, status:needs-backport

#8979 Replaced UpdateLogging.FULL with UpdateLogging.Full
  documentation/manual/working/commonGuide/build/SBTCookbook.md
Labels: status:needs-forwardport

#8996 Assert testkit uses the correct ServerProvider
  framework/src/sbt-plugin/src/sbt-test/README.md
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/build.sbt
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/project/plugins.sbt
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/src/main/resources/application.conf
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/src/main/resources/routes
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/src/main/scala/controllers/HomeController.scala
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/src/test/scala/controllers/IntegrationTest.scala
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/test
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/build.sbt
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/project/plugins.sbt
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/src/main/resources/application.conf
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/src/main/resources/routes
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/src/main/scala/controllers/HomeController.scala
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/src/test/scala/controllers/IntegrationTest.scala
  framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/test
  framework/src/sbt-plugin/src/sbt-test/http-backend/netty/build.sbt
  framework/src/sbt-plugin/src/sbt-test/http-backend/netty/project/plugins.sbt
  framework/src/sbt-plugin/src/sbt-test/http-backend/netty/src/main/resources/application.conf
  framework/src/sbt-plugin/src/sbt-test/http-backend/netty/src/main/resources/routes
  framework/src/sbt-plugin/src/sbt-test/http-backend/netty/src/main/scala/controllers/HomeController.scala
  framework/src/sbt-plugin/src/sbt-test/http-backend/netty/src/test/scala/controllers/IntegrationTest.scala
  framework/src/sbt-plugin/src/sbt-test/http-backend/netty/test
Labels: review, status:needs-forwardport

#8993 Tutorial updates
  documentation/manual/tutorial/HelloWorldTutorial.md
  documentation/manual/tutorial/images/hello-page.png
  documentation/manual/tutorial/index.toc
Labels: topic:documentation

#9002 Forwardports from getting Play 2.7 working on Scala 2.13
  framework/build.sbt
  framework/project/BuildSettings.scala
  framework/src/play/src/main/java-scala-2.13+/play/libs/CrossScala.java
  framework/src/play/src/main/java-scala-2.13-/play/libs/CrossScala.java
  framework/src/play/src/main/java/play/libs/Scala.java
  framework/src/play/src/main/java/play/libs/typedmap/TypedMap.java
  framework/src/play/src/main/scala/play/api/data/Form.scala
Labels: in progress

#9003 MiMa should check against 2.7.0 tag in 2.7.x branch
  framework/build.sbt
  framework/project/BuildSettings.scala
Labels: in progress

#9004 MiMa should check against 2.7.0 tag in master branch
  framework/project/BuildSettings.scala
Labels: merge-when-green
