Repository playframework/playframework, pull requests merged in 2020-11, with the labels that each got.

#10487 Remove deprecated FakeKeyStore
  project/BuildSettings.scala
  transport/server/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala
Labels: status:merge-when-green

#10516 Update hibernate-core to 5.4.23.Final
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10521 Update jakarta.transaction-api to 2.0.0
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10525 Update scalacheck to 1.15.1
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10529 Update spring-beans, spring-context, ... to 5.2.11.RELEASE
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10468 Update htmlunit-driver to 2.44.0
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10502 Update mockito-core to 3.6.0
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10485 Update guava to 30.0-jre
  project/Dependencies.scala
Labels: type:updates

#10477 Update caffeine, jcache to 2.8.6
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10459 Update hibernate-validator to 6.1.6.Final
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10511 Fix duplicated code line in docs of JavaFileUpload
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java
Labels: status:merge-when-green

#10410 Update okhttp to 4.8.1
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10531 Update okhttp to 4.9.0
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10532 Update netty-transport-native-epoll to 4.1.54.Final
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10530 Update spring-beans, spring-context, ... to 5.3.1
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10535 Update htmlunit-driver to 2.45.0
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10458 sbt-plugin: handle AssertionError from zinc compilation
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
Labels: status:merge-when-green

#10544 Scala 2.13.4
  documentation/build.sbt
  documentation/manual/hacking/BuildingFromSource.md
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/releases/release28/migration28/Migration28.md
  documentation/manual/working/commonGuide/build/sbtDependencies.md
Labels: status:merge-when-green

#10546 Update sbt to 1.4.4
  documentation/project/build.properties
  project/build.properties
Labels: status:merge-when-green, type:updates

#10542 Update hibernate-core to 5.4.24.Final
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10540 Update jdbc-driver to 1.0.57
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10547 [2.7.x] Fix doc typos in config keys
  documentation/manual/releases/release27/migration27/Migration27.md
Labels: topic:documentation

#10548 Update mockito-core to 3.6.28
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10553 Remove unnecessary modifiers from interfaces in play-jdbc-api
  persistence/play-jdbc-api/src/main/java/play/db/ConnectionCallable.java
  persistence/play-jdbc-api/src/main/java/play/db/ConnectionRunnable.java
  persistence/play-jdbc-api/src/main/java/play/db/DBApi.java
  persistence/play-jdbc-api/src/main/java/play/db/Database.java
Labels: status:merge-when-green

#10551 Create the Play BOM per Scala binary version
  project/BillOfMaterialsPlugin.scala
  project/plugins.sbt
Labels: status:merge-when-green
