Repository playframework/playframework, pull requests merged in 2021-11, with the labels that each got.

#10890 Fix IOException when using sbt thin client
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala
Labels: status:needs-backport, status:needs-backport-2.7-EOL

#11013 spring-beans, spring-context, ... 5.3.12 (was 5.3.10)
  project/Dependencies.scala
Labels: type:updates

#11010 htmlunit-driver 2.54.0 (was 2.53.0)
  project/Dependencies.scala
Labels: type:updates

#11008 joda-time 2.10.13 (was 2.10.12)
  project/Dependencies.scala
Labels: type:updates

#11007 netty-transport-native-epoll 4.1.70.Final (was 4.1.68.Final)
  project/Dependencies.scala
Labels: type:updates

#11015 Correct versions in release drafter template
  .github/release-drafter-master.yml
Labels: status:merge-when-green

#10789 Fixed `###replace:` tag that led to incorrect docs
  documentation/manual/tutorial/code/javaguide/hello/HelloController.java
Labels: topic:documentation

#11024 use new community sonatype profile
  project/BuildSettings.scala
Labels: status:merge-when-green

#11028 update play-ws
  project/Dependencies.scala
Labels: status:merge-when-green

#11030 Update play-json and play-ws
  project/Dependencies.scala
Labels: status:merge-when-green
