Repository playframework/playframework, pull requests merged in 2021-04, with the labels that each got.

#10795 Update netty-transport-native-epoll to 4.1.63.Final
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10796 Update sbt to 1.5.0
  .travis.yml
  documentation/project/build.properties
  project/build.properties
Labels: status:merge-when-green, type:updates

#10693 Add SameSite to DiscardingCookie
  core/play/src/main/java/play/mvc/Result.java
  core/play/src/main/scala/play/api/mvc/Cookie.scala
  project/BuildSettings.scala
Labels: status:merge-when-green

#10797 Akka-Http-Server: allow Headers.remove() to remove Content-Type and Content-Length
  transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
  transport/server/play-akka-http-server/src/test/scala/play/core/server/akkahttp/AkkaHeadersWrapperTest.scala
Labels: status:merge-when-green

#10802 Update mockito-core to 3.9.0
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10804 Sunset bintray 2.1.x
  project/BuildSettings.scala
  project/Release.scala
  project/plugins.sbt
Labels: status:block-merge

#10807 Fix function name in Scala WS guide
  documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
Labels: status:merge-when-green

#10806 Bump akka 2.6.14
  project/Dependencies.scala
Labels: status:merge-when-green

#10808 Initialize static Json objectMapper only once
  core/play-java/src/main/scala/play/core/ObjectMapperModule.scala
Labels: status:merge-when-green

#10811 Long jobs should appear first on a stage
  .travis.yml
Labels: status:merge-when-green

#10814 Update typetools to 0.6.3
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10817 Update htmlunit-driver to 2.49.1
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10818 Fix docs: Flash cookie is signed
  documentation/manual/working/javaGuide/main/http/JavaSessionFlash.md
  documentation/manual/working/scalaGuide/main/http/ScalaSessionFlash.md
Labels: topic:documentation

#10820 Also run netty http 1.1 microbenchmark encrypted
  core/play-microbenchmark/src/test/scala/play/microbenchmark/it/HelloWorldBenchmark.scala
Labels: status:merge-when-green

#10826 Update spring-beans, spring-context, ... to 5.3.6
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10823 Update scalasteward settings
  .scala-steward.conf
Labels: status:merge-when-green

#10822 Used scalafix for a first cleanup of sbt deprecated syntax
  build.sbt
  project/BuildSettings.scala
  project/Docs.scala
  project/Tasks.scala
Labels: status:merge-when-green

#10828 Updated link to OWASP recommended to familiarize with CSRF
  documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
Labels: status:merge-when-green

#10825 Binders for OptionalInt, OptionalLong, OptionalDouble
  core/play/src/main/scala/play/api/mvc/Binders.scala
  core/play/src/main/scala/play/core/routing/GeneratedRouter.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/controllers/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/utils/JavaScriptRouterGenerator.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/assets/JavaScriptRouterSpec.js
Labels: status:merge-when-green

#10276 Support for variable substitution in evolutions scripts
  documentation/manual/releases/release29/Highlights29.md
  documentation/manual/working/commonGuide/database/Evolutions.md
  persistence/play-jdbc-evolutions/src/main/java/play/db/evolutions/Evolutions.java
  persistence/play-jdbc-evolutions/src/main/resources/reference.conf
  persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
  persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
  persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
  persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsHelper.scala
  persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/DefaultEvolutionsConfigParserSpec.scala
  persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsHelperSpec.scala
  persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsSpec.scala
  project/BuildSettings.scala
Labels: status:merge-when-green

#10835 [2.8.x] Run tests with sbt 1.5.1
  .travis.yml
  scripts/scriptLib
  scripts/validate-code
Labels: status:merge-when-green

#10836 sbt 1.5.1
  .travis.yml
  documentation/project/build.properties
  persistence/play-jdbc-evolutions/src/main/java/play/db/evolutions/Evolutions.java
  project/build.properties
  scripts/scriptLib
  scripts/validate-code
Labels: status:merge-when-green
