Repository playframework/playframework, pull requests merged in 2021-06, with the labels that each got.

#10880 Run tests against Scala 2.12.14 and 2.13.6 and sbt 1.5.3
  .travis.yml
  dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
  documentation/build.sbt
  documentation/manual/hacking/BuildingFromSource.md
  documentation/manual/releases/release26/Highlights26.md
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/releases/release28/migration28/Migration28.md
  documentation/manual/working/commonGuide/build/sbtDependencies.md
  documentation/project/build.properties
  project/BuildSettings.scala
  project/Dependencies.scala
  project/build.properties
Labels: status:merge-when-green

#10884 Remove play-enhancer from docs, project is dead
  documentation/build.sbt
  documentation/manual/releases/release24/migration24/Migration24.md
  documentation/manual/working/commonGuide/build/Build.md
  documentation/manual/working/commonGuide/build/PlayEnhancer.md
  documentation/manual/working/commonGuide/build/code/enhancer.sbt
  documentation/manual/working/commonGuide/build/index.toc
  documentation/manual/working/javaGuide/main/forms/JavaForms.md
  documentation/manual/working/javaGuide/main/tests/JavaTest.md
  documentation/project/plugins.sbt
Labels: status:merge-when-green

#10906 sbt-jmh 0.4.3 (was 0.4.2)
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10904 spring-beans, spring-context, ... 5.3.8 (was 5.3.7)
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10898 mockito-core 3.11.1 (was 3.10.0)
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10897 netty-transport-native-epoll 4.1.65.Final (was 4.1.63.Final)
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10896 sbt-mima-plugin 0.9.2 (was 0.9.0)
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10905 webjars-locator-core 0.47 (was 0.46)
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10902 htmlunit-driver 2.50.0 (was 2.49.1)
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10903 specs2-core, specs2-junit, ... 4.12.0 (was 4.11.0)
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10885 Prefer -agentlib:jdwp= over -Xrunjdwp:
  documentation/manual/working/javaGuide/main/tests/JavaTest.md
Labels: status:merge-when-green, topic:documentation

#10858 Use app materializer to execute action in akka-http backend
  transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
  transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
Labels: status:merge-when-green

#10907 Remove routeAndCall(...) methods that depended on StaticRoutesGenerator
  project/BuildSettings.scala
  testkit/play-test/src/main/java/play/test/Helpers.java
Labels: status:merge-when-green

#10888 align indent in `forwardsRouter.scala.twirl`
  dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl
Labels: status:merge-when-green

#10878 add parentheses for lambda param
  cache/play-ehcache/src/test/scala/play/api/cache/CachedSpec.scala
  core/play-integration-test/src/it/scala/play/it/action/HeadActionSpec.scala
  core/play-integration-test/src/it/scala/play/it/auth/SecuritySpec.scala
  core/play-integration-test/src/it/scala/play/it/http/AkkaHttpCustomServerProviderSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/FlashCookieSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/FormFieldOrderSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/IdleTimeoutSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/SecureFlagSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/UriHandlingSpec.scala
  core/play-integration-test/src/it/scala/play/it/libs/ScalaWSSpec.scala
  core/play-integration-test/src/it/scala/play/it/routing/ServerSpec.scala
  core/play-integration-test/src/it/scala/play/it/server/ServerReloadingSpec.scala
  core/play-integration-test/src/it/scala/play/it/test/EndpointIntegrationSpecification.scala
  core/play-integration-test/src/it/scala/play/it/test/EndpointIntegrationSpecificationSpec.scala
  core/play-integration-test/src/it/scala/play/it/test/OkHttpEndpointSpec.scala
  core/play-integration-test/src/it/scala/play/it/test/OkHttpEndpointSupport.scala
  core/play-integration-test/src/it/scala/play/it/test/WSEndpointSpec.scala
  core/play-integration-test/src/it/scala/play/it/test/WSEndpointSupport.scala
  core/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
  core/play/src/main/scala/play/api/http/HttpRequestHandler.scala
  core/play/src/main/scala/play/api/http/Writeable.scala
  core/play/src/main/scala/play/core/routing/GeneratedRouter.scala
  core/play/src/test/scala/play/api/mvc/ResultsSpec.scala
  core/play/src/test/scala/play/core/routing/GeneratedRouterSpec.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
  documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala
  documentation/manual/working/scalaGuide/main/ws/code/ScalaOAuthSpec.scala
  project/Docs.scala
  testkit/play-specs2/src/test/scala/play/api/test/FakesSpec.scala
  testkit/play-test/src/main/scala/play/api/test/ApplicationFactory.scala
  transport/client/play-ahc-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
  transport/client/play-ahc-ws/src/test/scala/play/api/libs/ws/ahc/OptionalAhcHttpCacheProviderSpec.scala
  transport/client/play-ahc-ws/src/test/scala/play/libs/ws/WSSpec.scala
  transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
  transport/server/play-server/src/main/scala/play/core/server/common/ForwardedHeaderHandler.scala
  transport/server/play-server/src/main/scala/play/core/server/common/ReloadCache.scala
  transport/server/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
  transport/server/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
Labels: status:merge-when-green

#10871 fix warnings. use slash syntax instead of old `in`
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-namespace-reverse-router/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/test
  documentation/manual/working/commonGuide/build/sbtDebugging.md
  documentation/manual/working/javaGuide/main/tests/JavaTest.md
  documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md
  project/Dependencies.scala
  project/Docs.scala
  scripts/it-test
  scripts/local-pr-validation.sh
  scripts/scriptLib
  scripts/validate-code
  scripts/validate-docs
Labels: status:merge-when-green

#10870 fix Auto-application warnings
  core/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala
  core/play-guice/src/test/scala/play/core/test/Fakes.scala
  core/play-guice/src/test/scala/play/utils/ReflectSpec.scala
  core/play/src/main/scala/play/api/controllers/Assets.scala
  core/play/src/main/scala/play/api/libs/Comet.scala
  core/play/src/main/scala/play/core/formatters/Multipart.scala
  core/play/src/main/scala/play/utils/OrderPreserving.scala
  testkit/play-test/src/main/scala/play/api/test/Helpers.scala
  web/play-filters-helpers/src/test/scala/play/filters/csp/CSPFilterSpec.scala
  web/play-filters-helpers/src/test/scala/play/filters/csp/ScalaCSPActionSpec.scala
  web/play-filters-helpers/src/test/scala/play/filters/headers/SecurityHeadersFilterSpec.scala
  web/play-java-forms/src/test/scala/play/data/FormSpec.scala
Labels: status:merge-when-green

#10869 fix procedure syntax warnings
  core/play-java/src/main/scala/play/routing/RoutingDslModule.scala
  core/play/src/main/scala/play/core/j/JavaHttpErrorHandlerAdapter.scala
  core/play/src/main/scala/play/core/parsers/Multipart.scala
  documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala
  persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
  testkit/play-specs2/src/main/scala/play/api/test/Specs.scala
  web/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
  web/play-filters-helpers/src/main/scala/play/filters/headers/SecurityHeadersFilter.scala
Labels: status:merge-when-green

#10868 add explicit type annotations for public implicit val and def
  core/play/src/main/scala/controllers/Execution.scala
  core/play/src/main/scala/play/api/Logger.scala
  core/play/src/main/scala/play/api/http/MediaRange.scala
  core/play/src/main/scala/play/api/mvc/Binders.scala
  core/play/src/main/scala/play/api/mvc/Results.scala
  core/play/src/main/scala/play/core/Execution.scala
  core/play/src/main/scala/play/core/routing/ReverseRouteContext.scala
  testkit/play-specs2/src/main/scala/play/api/test/Specs.scala
  testkit/play-test/src/main/scala/play/api/test/Helpers.scala
  transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
Labels: status:merge-when-green

#10865 Remove obsolete CertificateGenerator
  project/BuildSettings.scala
  transport/server/play-server/src/main/scala/play/core/server/ssl/CertificateGenerator.scala
Labels: status:merge-when-green

#10860 For CI jobs, print files used by sbt + env vars
  scripts/scriptLib
Labels: status:merge-when-green

#10844 Small config + comments cleanup
  core/play/src/main/resources/reference.conf
  transport/server/play-akka-http-server/src/main/resources/reference.conf
  transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
Labels: status:merge-when-green

#10909 update `unmanagedSourceDirectories` setting for Scala 3
  build.sbt
Labels: status:merge-when-green

#10910 avoid deprecated scala.Either#right
  core/play-integration-test/src/it/scala/play/it/http/parsing/BodyParserSpec.scala
  core/play/src/main/scala/play/api/data/Form.scala
  core/play/src/main/scala/play/api/data/format/Format.scala
  core/play/src/main/scala/play/api/data/format/package.scala
  core/play/src/main/scala/play/api/i18n/Messages.scala
  core/play/src/main/scala/play/api/mvc/Action.scala
  core/play/src/main/scala/play/api/mvc/Binders.scala
  core/play/src/main/scala/play/api/mvc/BodyParsers.scala
  core/play/src/main/scala/play/api/mvc/WebSocket.scala
  core/play/src/main/scala/play/api/mvc/macros/BinderMacros.scala
  core/play/src/main/scala/play/core/routing/GeneratedRouter.scala
  core/play/src/test/scala/play/api/data/format/FormatSpec.scala
  dev-mode/routes-compiler/src/main/scala/play/routes/compiler/RoutesCompiler.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
  documentation/manual/working/scalaGuide/main/async/code/ScalaWebSockets.scala
  transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
  web/play-filters-helpers/src/main/scala/play/filters/csp/CSPReportActionBuilder.scala
  web/play-joda-forms/src/main/scala/play/api/data/format/JodaFormats.scala
Labels: status:merge-when-green
