Repository playframework/playframework, pull requests merged in 2021-03, with the labels that each got.

#10726 Upgrade to latest JJWT (means we can remove JAXB Api)
  core/play-integration-test/src/it/scala/play/it/api/SecretConfigurationParserSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/SessionCookieSpec.scala
  core/play/src/main/scala/play/api/http/HttpConfiguration.scala
  core/play/src/main/scala/play/api/mvc/Cookie.scala
  core/play/src/test/resources/reference.conf
  core/play/src/test/scala/play/api/http/SecretConfigurationParserSpec.scala
  core/play/src/test/scala/play/api/mvc/CookiesSpec.scala
  core/play/src/test/scala/play/api/mvc/FlashCookieSpec.scala
  documentation/manual/releases/release29/migration29/Migration29.md
  documentation/manual/working/commonGuide/configuration/ApplicationSecret.md
  documentation/src/main/resources/application.conf
  project/BuildSettings.scala
  project/Dependencies.scala
  transport/server/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
Labels: status:merge-when-green

#10731 Improve compatibility with JDKs > 11
  core/play/src/main/java/play/package-info.java
  core/play/src/main/scala/play/utils/Resources.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/plugins.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
  web/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java
Labels: status:merge-when-green

#10732 No need to build a JwtParser each time
  core/play/src/main/scala/play/api/mvc/Cookie.scala
Labels: status:merge-when-green

#10734 Remove Jetty ALPN Agent / sbt-javaagent
  build.sbt
  core/play-microbenchmark/src/test/scala/play/microbenchmark/PlayJmhRunner.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala
  documentation/manual/releases/release29/migration29/Migration29.md
  documentation/manual/working/commonGuide/server/AkkaHttpServer.md
  project/BuildSettings.scala
  project/Dependencies.scala
  project/Tasks.scala
  project/plugins.sbt
Labels: status:merge-when-green

#10736 Update play-file-watch to 1.1.15
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10739 Update HikariCP to 4.0.3
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10730 Adds release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: status:merge-when-green

#10752 Update sbt to 1.4.9
  documentation/project/build.properties
  project/build.properties
Labels: status:merge-when-green, type:updates

#10741 fix Int overflow in BodyParsers.anyContent(maxLength: Option[Long])
  core/play-integration-test/src/it/scala/play/it/http/parsing/AnyContentBodyParserSpec.scala
  core/play/src/main/scala/play/api/mvc/BodyParsers.scala
Labels: status:merge-when-green

#10655 Run scripted tests on sbt 1.4.x + refactoring
  .travis.yml
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/build.sbt.1
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/index.scala.html-2.bad
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/routes-2.bad
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/routes-fail-2.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/twirl-fail-2.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/build.sbt.1
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/project/Helpers.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/app/controllers/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-namespace-reverse-router/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/app/router/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/controllers/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/project/plugins.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/routes
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/show-versions/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/show-versions/test
  project/BuildSettings.scala
  scripts/it-test
  scripts/it-test-scala-213
  scripts/publish-local
  scripts/test
  scripts/test-docs
  scripts/test-docs-212
  scripts/test-scala-212
  scripts/test-scripted
  scripts/test-scripted-13x
Labels: status:merge-when-green

#10756 Remove sbt 1.4.x / Scala 2.12.x (Test only 1.4.x / 2.13.x)
  .travis.yml
Labels: status:merge-when-green

#10723 [2.8.x] Run scripted tests on sbt 1.4.x + refactoring
  .travis.yml
  dev-mode/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/run/PlayReload.scala
  dev-mode/sbt-plugin/src/main/scala-sbt-1.0/play/sbt/run/PlayReload.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/build.sbt.1
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/index.scala.html-2.bad
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/routes-2.bad
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/routes-fail-2.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/twirl-fail-2.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/build.sbt.1
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/project/Helpers.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/project/Helper.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/app/controllers/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-namespace-reverse-router/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/app/router/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/controllers/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/project/plugins.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/routes
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/show-versions/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/show-versions/test
  project/BuildSettings.scala
  scripts/it-test
  scripts/it-test-scala-213
  scripts/publish-local
  scripts/scriptLib
  scripts/test
  scripts/test-docs
  scripts/test-docs-212
  scripts/test-scala-212
  scripts/test-scripted
  scripts/test-scripted-13x
Labels: status:merge-when-green

#10757 Update sbt-native-packager to 1.8.1
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10750 Update sbt-jmh to 0.4.0
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10748 Update sbt-header to 5.6.0
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10745 Update sbt-dynver to 4.1.1
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10738 Update jquery to 3.6.0
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10759 Update play-file-watch to 1.1.16
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10758 Update several dependencies
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/conf/application.conf
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/expected-application-log.txt
  documentation/project/plugins.sbt
  project/Dependencies.scala
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10762 Update sbt-mima-plugin to 0.8.1
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10766 Release drafter should use correct version + 2.8.x branch
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: status:merge-when-green

#10771 Update sbt-twirl to 1.5.1
  documentation/project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10769 Update twirl-api to 1.5.1
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10770 Update guava to 30.1.1-jre
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10765 Update sbt-bill-of-materials to 1.0.2
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#10767 [2.8.x] Upgrade dependencies before releasing Play 2.8.8
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/conf/application.conf
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/expected-application-log.txt
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  documentation/project/plugins.sbt
  project/Dependencies.scala
  project/plugins.sbt
  transport/client/play-ahc-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
Labels: status:merge-when-green

#10768 Update play-ahc-ws-standalone, ... to 2.1.3
  project/Dependencies.scala
  transport/client/play-ahc-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
Labels: status:merge-when-green, type:updates

#10772 Update htmlunit-driver to 2.48.0
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10775 [2.8.x] Add release-drafter workflow for 2.8.x branch + docs update
  .github/workflows/release-drafter.yml
  documentation/manual/releases/release28/migration28/Migration28.md
  documentation/manual/tutorial/Tutorials.md
Labels: status:merge-when-green

#10774 Nice release drafter template for master and 2.8.x branch + docs update
  .github/release-drafter-2.8.x.yml
  .github/release-drafter-master.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  documentation/manual/releases/release28/migration28/Migration28.md
  documentation/manual/releases/release29/migration29/Migration29.md
  documentation/manual/tutorial/Tutorials.md
Labels: status:merge-when-green

#10754 Make public DatabaseEvolutions.databaseEvolutions()
  persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
Labels: status:merge-when-green

#10729 Fix compile error on JDK15: Use direct AlgorithmId.get()
  project/BuildSettings.scala
  transport/server/play-server/src/main/scala/play/core/server/ssl/CertificateGenerator.scala
Labels: status:merge-when-green

#10780 Update ssl-config-core to 0.4.3
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10782 revert changes to playCommonClassloaderTask since we are using scala 2.12.13
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala
Labels: status:merge-when-green

#10781 Bump Jackson to 2.11.x
  .scala-steward.conf
  project/Dependencies.scala
Labels: status:block-merge

#10790 Update netty-transport-native-epoll to 4.1.61.Final
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10793 Update netty-transport-native-epoll to 4.1.62.Final
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates
