Repository playframework/playframework, pull requests merged in 2021-12, with the labels that each got.

#11053 Updating log4j ref in docs to 2.16.0
  documentation/manual/working/commonGuide/configuration/SettingsLogger.md
Labels: status:merge-when-green

#11061 ConsoleReader should be blocking in sbt 1.4+ since System.in already is non-blocking
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala
Labels: status:merge-when-green

#11064 Shutdown dev server when pressing CTRL+C during run
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
Labels: status:merge-when-green

#11070 Add onLoadMessage
  dev-mode/run-support/src/main/scala/play/runsupport/Colors.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/Colors.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
Labels: status:merge-when-green

#11071 [2.8.x] Add onLoadMessage
  dev-mode/run-support/src/main/scala/play/runsupport/Colors.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/Colors.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
Labels: status:merge-when-green

#11050 Bump versions
  .travis.yml
  core/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
  documentation/build.sbt
  documentation/manual/hacking/BuildingFromSource.md
  documentation/manual/hacking/Translations.md
  documentation/manual/releases/release26/Highlights26.md
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/releases/release28/migration28/Migration28.md
  documentation/manual/releases/release29/migration29/Migration29.md
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/commonGuide/build/sbtDependencies.md
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  documentation/project/build.properties
  project/Dependencies.scala
  project/build.properties
Labels: type:updates

#11041 h2 2.0.202 (was 1.4.200)
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/build.sbt
  documentation/build.sbt
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11005 junit-interface 0.13.2 (was 0.11)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11075 Documented the change from ValidationError to JsonValidationError in Migration-2.6
  documentation/manual/releases/release26/migration26/Migration26.md
Labels: status:merge-when-green
