Repository playframework/playframework, pull requests merged in 2021-02, with the labels that each got.

#10661 Don't reload/(re-)compile or even start an app when shutting down in DEV mode
  core/play/src/main/scala/play/api/controllers/Assets.scala
  core/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala
  transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
  transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala
Labels: status:merge-when-green

#10667 Update okhttp to 4.9.1
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10672 Remove very old methods from routes generator
  dev-mode/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
Labels: status:merge-when-green

#10671 Add empty parentheses () to generated reverse route method depending on routes file
  dev-mode/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
  dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/reverseRouter.scala.twirl
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-aggregate-reverse-routes/c/app/controllers/c/C.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/fullform.scala.html
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/helpers.scala.html
  documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala
  documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/implicitMessages.scala.html
  documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/messages.scala.html
  documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/user.scala.html
Labels: status:merge-when-green

#10648 Support sbt 1.4 virtual files when displaying error source
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/app/controllers/HomeController.java
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/build.sbt.1
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/common-fail.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/conf/application.conf
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/conf/routes
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/controller-fail.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/dev-mode-runtime-error-source-sub-project-outside/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/dev-mode-runtime-error-source-sub-project-outside/src/main/scala/Bar.java
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/modules/sub-project-inside/src/main/scala/Foo.java
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/project/plugins.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/sub-project-inside-fail.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/sub-project-outside-fail.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/test
  dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
Labels: status:merge-when-green

#10666 Java forms: Prefix a ValidationError's key with parent form field key
  web/play-java-forms/src/main/java/play/data/Form.java
  web/play-java-forms/src/test/scala/play/data/FormSpec.scala
Labels: status:merge-when-green

#10649 [2.8.x] Support sbt 1.4 virtual files when displaying error source
  dev-mode/sbt-plugin/src/main/scala-sbt-1.0/play/sbt/run/PlayReload.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/app/controllers/HomeController.java
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/build.sbt.1
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/common-fail.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/conf/application.conf
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/conf/routes
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/controller-fail.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/dev-mode-runtime-error-source-sub-project-outside/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/dev-mode-runtime-error-source-sub-project-outside/src/main/scala/Bar.java
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/modules/sub-project-inside/src/main/scala/Foo.java
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/project/plugins.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/sub-project-inside-fail.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/sub-project-outside-fail.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/test
  dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
Labels: status:merge-when-green

#10680 Java forms should handle "foo[].bar" fields when using subforms (index missing)
  web/play-java-forms/src/main/java/play/data/Form.java
  web/play-java-forms/src/test/java/play/data/Letter.java
  web/play-java-forms/src/test/java/play/data/Thesis.java
  web/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
  web/play-java-forms/src/test/scala/play/data/FormSpec.scala
Labels: status:merge-when-green

#10683 Update joda-time to 2.10.10
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10686 Update htmlunit-driver to 2.47.1
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10370 QueryStringBindable.unbind(): Do-do-do URLEncode for all queryString keys!
  core/play/src/main/scala/play/api/mvc/Binders.scala
  core/play/src/test/scala/play/api/mvc/BindersSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/tests/RouterSpec.scala
  documentation/manual/working/javaGuide/advanced/routing/RequestBinders.md
  documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/models/CartItem.java
  documentation/manual/working/scalaGuide/advanced/routing/ScalaRequestBinders.md
  documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/CartItem.scala
Labels: status:merge-when-green

#10690 Catch Throwable instead of NonFatal when starting prod server
  transport/server/play-server/src/main/scala/play/core/server/ProdServerStart.scala
Labels: status:merge-when-green

#10689 No need to target jdk 1.6 anymore for plugins
  project/BuildSettings.scala
Labels: topic:jdk-next

#10698 Update junit to 4.13.2
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10704 Update caffeine, jcache to 2.9.0
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10691 Update netty-transport-native-epoll to 4.1.59.Final
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10706 Update spring-beans, spring-context, ... to 5.3.4
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10696 Update HikariCP to 4.0.2
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10695 Replace comments on variables with readable names in tests
  cache/play-caffeine-cache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
  cache/play-ehcache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
  core/play/src/test/java/play/mvc/ResultsTest.java
Labels: status:merge-when-green

#10708 Update scalacheck to 1.15.3
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10697 Replace generic matchers on specific builtin matchers in tests
  core/play/src/test/scala/play/api/mvc/BindersSpec.scala
  core/play/src/test/scala/play/core/routing/RouterSpec.scala
Labels: status:merge-when-green

#10715 Update mockito-core to 3.8.0
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10717 Upgrade akka and akka-http
  project/Dependencies.scala
Labels: status:merge-when-green

#10718 Scala 2.12.13 and 2.13.5
  documentation/build.sbt
  documentation/manual/hacking/BuildingFromSource.md
  documentation/manual/releases/release26/Highlights26.md
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/releases/release28/migration28/Migration28.md
  documentation/manual/working/commonGuide/build/sbtDependencies.md
  project/Dependencies.scala
Labels: status:merge-when-green

#10724 Update guice to 5.0.0
  documentation/manual/releases/release29/migration29/Migration29.md
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#10727 Update guice to 5.0.1
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates
