Repository playframework/playframework, pull requests merged in 2022-09, with the labels that each got.

#11407 Removing CLA from the PR template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status:merge-when-green

#11424 🔄 Synced file(s) with playframework/.github
  .mergify.yml
Labels: sync

#11418 jquery 3.6.1 (was 3.6.0)
  project/Dependencies.scala
Labels: type:updates

#11412 netty-transport-native-epoll 4.1.81.Final (was 4.1.79.Final)
  project/Dependencies.scala
Labels: type:updates

#11387 spring-beans, spring-context, ... 5.3.22 (was 5.3.19)
  project/Dependencies.scala
Labels: type:updates

#11415 mockito-core 4.8.0 (was 4.6.1)
  project/Dependencies.scala
Labels: type:updates

#11409 jackson-databind 2.13.4 (was 2.13.3)
  project/Dependencies.scala
Labels: type:updates

#11383 hibernate-validator 6.2.4.Final (was 6.2.3.Final)
  project/Dependencies.scala
Labels: type:updates

#11411 akka-actor 2.6.20 (was 2.6.19)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11382 logstash-logback-encoder 7.2 (was 5.3)
  documentation/build.sbt
Labels: type:updates

#11388 webjars-locator-core 0.52 (was 0.50)
  project/plugins.sbt
Labels: type:updates, status:merge-when-green

#11384 sbt-scalafmt 2.4.6 (was 2.0.7)
  documentation/project/plugins.sbt
  project/plugins.sbt
Labels: type:updates

#11431 [2.8.x] Upgrade to Scala 2.12.17 and 2.13.9
  .github/workflows/build-test.yml
  documentation/build.sbt
  documentation/manual/hacking/BuildingFromSource.md
  documentation/manual/releases/release26/Highlights26.md
  documentation/manual/releases/release27/Highlights27.md
  documentation/manual/releases/release28/migration28/Migration28.md
  documentation/manual/working/commonGuide/build/sbtDependencies.md
  project/Dependencies.scala
Labels: status:merge-when-green

#11408 logback-classic 1.4.0 (was 1.2.11)
  project/Dependencies.scala
Labels: type:updates, topic:jdk-next, status:merge-when-green

#11048 Upgrade fluentlenium, selenium and htmlunit-driver to latest versions
  project/Dependencies.scala
Labels: type:updates, topic:jdk-next, status:merge-when-green

#10949 HikariCP 5.0.0 (was 4.0.3)
  project/Dependencies.scala
Labels: type:updates, topic:jdk-next, status:merge-when-green

#11414 jdbc-driver 1.2.1 (was 1.1.4)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11413 joda-time 2.11.1 (was 2.10.14)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11443 fix some warnings
  core/play-integration-test/src/it/scala/play/it/http/HttpPipeliningSpec.scala
  core/play-java/src/main/java/play/libs/XPath.java
  dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
  project/AkkaSnapshotRepositories.scala
  project/BuildSettings.scala
Labels: status:merge-when-green

#10764 Update caffeine, jcache to 3.0.1
  project/Dependencies.scala
Labels: type:updates, topic:jdk-next, status:merge-when-green

#10082 Update derby to 10.15.2.0
  build.sbt
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  project/Dependencies.scala
Labels: type:updates, topic:jdk-next, status:merge-when-green

#11350 sbt-assembly 0.14.10 (was 0.14.5)
  documentation/manual/working/commonGuide/production/Deploying.md
  documentation/project/plugins.sbt
Labels: type:updates, status:merge-when-green
