Repository playframework/playframework, pull requests merged in 2022-04, with the labels that each got.

#11237 spring-beans, spring-context, ... 5.3.18 (was 5.3.16)
  project/Dependencies.scala
Labels: type:updates

#11236 specs2-core, specs2-junit, ... 4.15.0 (was 4.13.3)
  project/Dependencies.scala
Labels: type:updates

#11235 htmlunit-driver 2.60.0 (was 2.59.0)
  project/Dependencies.scala
Labels: type:updates

#11233 joda-time 2.10.14 (was 2.10.13)
  project/Dependencies.scala
Labels: type:updates

#11234 scalacheck 1.16.0 (was 1.15.4)
  project/Dependencies.scala
Labels: type:updates

#11230 sbt-mima-plugin 1.1.0 (was 1.0.1)
  project/plugins.sbt
Labels: type:updates

#11142 CI with GitHub Actions
  .github/workflows/build-test.yml
  .github/workflows/trigger-cache-invalidation.yml
  .gitignore
  .mergify.yml
  .travis.yml
  README.md
  build.sbt
  cache/play-cache/src/test/resources/logback-test.xml
  cache/play-caffeine-cache/src/test/resources/logback-test.xml
  cache/play-ehcache/src/test/resources/logback-test.xml
  core/play-guice/src/test/resources/logback-test.xml
  core/play-integration-test/src/it/resources/logback.xml
  core/play-integration-test/src/it/scala/play/it/ServerIntegrationSpecification.scala
  core/play-java/src/test/resources/logback-test.xml
  core/play-streams/src/test/resources/logback-test.xml
  core/play/src/test/resources/logback-test.xml
  dev-mode/routes-compiler/src/test/resources/logback-test.xml
  dev-mode/run-support/src/test/resources/logback-test.xml
  dev-mode/sbt-plugin/src/test/resources/logback-test.xml
  dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
  documentation/addMarkdownCopyright
  documentation/build.sbt
  persistence/play-java-jdbc/src/test/resources/logback-test.xml
  persistence/play-java-jpa/src/test/resources/logback-test.xml
  persistence/play-jdbc-evolutions/src/test/resources/logback-test.xml
  persistence/play-jdbc/src/test/resources/logback-test.xml
  project/AkkaSnapshotRepositories.scala
  scripts/clean-and-cross-publish-local
  scripts/it-test
  scripts/local-pr-validation.sh
  scripts/publish-local
  scripts/scriptLib
  scripts/test
  scripts/test-docs
  scripts/test-scripted
  scripts/validate-code
  scripts/validate-docs
  scripts/validate-microbenchmarks
  testkit/play-specs2/src/test/resources/logback-test.xml
  testkit/play-test/src/test/resources/logback-test.xml
  transport/client/play-ahc-ws/src/test/resources/logback-test.xml
  transport/server/play-server/src/test/resources/logback-test.xml
  web/play-filters-helpers/src/test/resources/logback-test.xml
  web/play-openid/src/test/resources/logback-test.xml
Labels: status:block-merge

#11232 jakarta.transaction-api 2.0.1 (was 2.0.0)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11231 play-json 2.10.0-RC6 (was 2.10.0-RC5)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11250 Replace scripts/local-pr-validation.sh with sbt validateCode in CONTRIBUTING
  CONTRIBUTING.md
Labels: status:merge-when-green
