Repository playframework/playframework, pull requests merged in 2022-01, with the labels that each got.

#11083 play-ws 2.1.7
  project/Dependencies.scala
Labels: status:merge-when-green

#11091 junit-interface 0.13.3 (was 0.13.2)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11092 h2 2.0.206 (was 2.0.202)
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/build.sbt
  documentation/build.sbt
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11105 Update draft release announcement used for minor releases
  .github/release-drafter-2.8.x.yml
Labels: status:merge-when-green

#11111 Replace gitter with discord
  README.md
Labels: status:merge-when-green

#11081 [master] Upgrade dependencies to fix CI cron build
  .scala-steward.conf
  .travis.yml
  build.sbt
  core/play-integration-test/src/it/scala/play/it/http/UriHandlingSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/conf/evolutions/default/1.sql
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/conf/evolutions/default/1.sql
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/conf/evolutions/groups/1.sql
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/conf/evolutions/users/1.sql
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/conf/application.conf
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/expected-application-log.txt
  dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
  documentation/manual/hacking/Translations.md
  documentation/manual/releases/release29/migration29/Migration29.md
  documentation/project/build.properties
  documentation/project/plugins.sbt
  project/BuildSettings.scala
  project/Dependencies.scala
  project/build.properties
  project/plugins.sbt
  project/project/buildinfo.sbt
  scripts/validate-code
  transport/client/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
  transport/client/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSRequest.scala
Labels: status:merge-when-green

#11115 Make sure to append -SNAPSHOT for sonatype
  build.sbt
Labels: status:merge-when-green

#11109 [2.8.x] Use ssl-config to 0.6.0
  dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
  project/Dependencies.scala
Labels: status:merge-when-green

#11116 [2.8.x] Make sure to append -SNAPSHOT for sonatype
  build.sbt
Labels: status:merge-when-green

#10615 Added description about guice dependency to BuildOverview that was re…
  documentation/manual/working/commonGuide/build/BuildOverview.md
Labels: topic:documentation, status:merge-when-green

#11121 use slash syntax instead of deprecated `in`
  dev-mode/sbt-plugin/src/main/scala/play/sbt/ApplicationSecretGenerator.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayLayoutPlugin.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/akka-fork-join-pool/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/dev-mode-compile-and-config-error-source-sub-project-outside/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/dev-mode-runtime-error-source-sub-project-outside/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/disabled-assets-jar/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http-http2/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-system-property/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/maven-layout-twirl-reload/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/module/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/nested-secret/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-aggregate-reverse-routes-with-request-passed/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-aggregate-reverse-routes/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-incremental-compilation/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-namespace-reverse-router/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/secret/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/show-versions/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-downing/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/build.sbt
Labels: status:merge-when-green

#11074 Small refactoring for better code readability
  dev-mode/build-link/src/main/java/play/core/Build.java
Labels: status:merge-when-green

#11120 fork := true for "sbt run" not needed to set editor (it doesn't even work)
  documentation/manual/gettingStarted/IDE.md
Labels: topic:documentation

#11090 Updated BuildOverview for guice migration in Play 2.6 or higher version.
  documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
Labels: status:merge-when-green

#11132 use slash syntax instead deprecated `in`
  dev-mode/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala
  dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
  documentation/build.sbt
  documentation/manual/gettingStarted/code/ide.sbt
  documentation/manual/working/commonGuide/build/code/cookbook.sbt
  documentation/manual/working/commonGuide/build/sbtCookbook.md
  documentation/manual/working/commonGuide/configuration/ConfigFile.md
  documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
  documentation/manual/working/commonGuide/production/code/assembly.sbt
  documentation/manual/working/commonGuide/production/code/debian.sbt
  documentation/manual/working/commonGuide/production/code/production.sbt
  documentation/manual/working/commonGuide/production/code/rpm.sbt
  documentation/manual/working/javaGuide/main/tests/JavaTest.md
Labels: status:merge-when-green

#11135 fix Seq implicit conversions warnings
  core/play/src/main/scala/play/api/http/AcceptEncoding.scala
  core/play/src/main/scala/play/api/http/MediaRange.scala
  core/play/src/main/scala/play/core/j/JavaAction.scala
  core/play/src/main/scala/play/core/parsers/FormUrlEncodedParser.scala
  persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
  transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
  transport/server/play-server/src/main/scala/play/core/server/ProdServerStart.scala
  transport/server/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
  web/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala
Labels: status:merge-when-green
