Repository playframework/playframework, pull requests merged in 2022-02, with the labels that each got.

#11145 Rename master branch to main
  .github/release-drafter-main.yml
  .github/workflows/release-drafter.yml
  .travis.yml
  CONTRIBUTING.md
  README.md
  core/play/src/main/scala/play/api/mvc/RangeResult.scala
  documentation/manual/hacking/BuildingFromSource.md
  documentation/manual/hacking/ThirdPartyTools.md
  documentation/manual/hacking/Translations.md
  documentation/manual/hacking/WorkingWithGit.md
  documentation/manual/releases/release24/migration24/Migration24.md
  documentation/manual/releases/release26/migration26/Migration26.md
  documentation/manual/working/commonGuide/configuration/ConfigFile.md
  documentation/manual/working/commonGuide/filters/CspFilter.md
  documentation/manual/working/commonGuide/production/ProductionConfiguration.md
  documentation/manual/working/commonGuide/production/cloud/Deploying-CleverCloud.md
  documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
  documentation/manual/working/scalaGuide/main/forms/ScalaForms.md
Labels: status:merge-when-green

#11146 [2.8.x] Rename master branch to main
  .mergify.yml
  .travis.yml
  CONTRIBUTING.md
  core/play/src/main/scala/play/api/mvc/RangeResult.scala
  documentation/manual/hacking/BuildingFromSource.md
  documentation/manual/hacking/ThirdPartyTools.md
  documentation/manual/hacking/Translations.md
  documentation/manual/hacking/WorkingWithGit.md
  documentation/manual/releases/release24/migration24/Migration24.md
  documentation/manual/releases/release26/migration26/Migration26.md
  documentation/manual/working/commonGuide/configuration/ConfigFile.md
  documentation/manual/working/commonGuide/filters/CspFilter.md
  documentation/manual/working/commonGuide/production/ProductionConfiguration.md
  documentation/manual/working/commonGuide/production/cloud/Deploying-CleverCloud.md
  documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
  documentation/manual/working/scalaGuide/main/forms/ScalaForms.md
  project/Dependencies.scala
Labels: status:merge-when-green

#11150 guice 5.1.0 (was 5.0.1)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11152 h2 2.1.210 (was 2.0.206)
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/build.sbt
  documentation/build.sbt
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11156 mockito-core 4.3.1 (was 4.2.0)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11157 sbt 1.6.2 (was 1.6.1)
  documentation/project/build.properties
  project/build.properties
Labels: type:updates, status:merge-when-green

#11158 htmlunit-driver 2.58.0 (was 2.56.0)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11159 jcl-over-slf4j, jul-to-slf4j, ... 1.7.35 (was 1.7.32)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11160 specs2-core, specs2-junit, ... 4.13.2 (was 4.13.1)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11147 JDNI renamed to correct abbreviation JNDI (Java Naming and Directory Interface)
  documentation/manual/working/commonGuide/database/AccessingAnSQLDatabase.md
Labels: topic:documentation, status:merge-when-green
