Repository playframework/playframework, pull requests merged in 2022-03, with the labels that each got.

#11190 jcl-over-slf4j, jul-to-slf4j, ... 1.7.36 (was 1.7.35)
  project/Dependencies.scala
Labels: type:updates

#11191 specs2-core, specs2-junit, ... 4.13.3 (was 4.13.2)
  project/Dependencies.scala
Labels: type:updates

#11195 Doc fix: Body needs to be redirected with `POST`
  documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala
Labels: topic:documentation

#11172 Fix docs: Passing request to WebSocket action not supported
  documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaWebSockets.java
Labels: topic:documentation

#10845 Remove play.akka.config setting
  core/play/src/main/resources/reference.conf
  core/play/src/main/scala/play/api/libs/concurrent/Akka.scala
  core/play/src/test/scala/play/api/PlayGlobalAppSpec.scala
  documentation/manual/releases/release29/migration29/Migration29.md
  documentation/manual/working/javaGuide/main/akka/JavaAkka.md
  documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md
Labels: status:merge-when-green
