Repository playframework/playframework, pull requests merged in 2022-10, with the labels that each got.

#11440 GitHub Workflows security hardening
  .github/workflows/build-test.yml
  .github/workflows/publish.yml
  .github/workflows/release-drafter.yml
Labels: status:merge-when-green

#10997 Remove dependency from play-jdbc-api to play
  build.sbt
  project/Dependencies.scala
Labels: status:merge-when-green

#11470 Use the mergify config from the .github repo
  .github/mergify.yml
  .mergify.yml
Labels: status:blocked

#11471 Removed unmaintained "Play! Authenticate" module from module directory in documentation
  documentation/manual/ModuleDirectory.md
Labels: status:merge-when-green

#11487 spring-beans, spring-context, ... 5.3.23 (was 5.3.22)
  project/Dependencies.scala
Labels: type:updates

#11486 jcl-over-slf4j, jul-to-slf4j, ... 2.0.3 (was 2.0.0)
  project/Dependencies.scala
Labels: type:updates

#11485 selenium-api 4.1.4 (was 4.1.0)
  project/Dependencies.scala
Labels: type:updates

#11483 scalacheck 1.17.0 (was 1.16.0)
  project/Dependencies.scala
Labels: type:updates

#11482 hibernate-validator 6.2.5.Final (was 6.2.4.Final)
  project/Dependencies.scala
Labels: type:updates

#11481 derby, derbytools 10.16.1.1 (was 10.15.2.0)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
Labels: type:updates

#11478 HikariCP 5.0.1 (was 5.0.0)
  project/Dependencies.scala
Labels: type:updates

#11477 play-json 2.10.0-RC7 (was 2.10.0-RC6)
  project/Dependencies.scala
Labels: type:updates

#11476 sbt-mima-plugin 1.1.1 (was 1.1.0)
  project/plugins.sbt
Labels: type:updates

#11475 caffeine, jcache 3.0.6 (was 3.0.1)
  project/Dependencies.scala
Labels: type:updates

#11473 logback-classic 1.4.4 (was 1.4.1)
  project/Dependencies.scala
Labels: type:updates

#11480 joda-time 2.11.2 (was 2.11.1)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11479 netty-transport-native-epoll 4.1.84.Final (was 4.1.81.Final)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11474 jackson-databind 2.13.4.2 (was 2.13.4)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11517 Use environment file instead `set-output`
  .github/workflows/build-test.yml
Labels: status:merge-when-green

#11518 [2.8.x] Use environment file instead `set-output`
  .github/workflows/build-test.yml
  .github/workflows/publish.yml
Labels: status:merge-when-green
