Repository playframework/playframework, pull requests merged in 2022-07, with the labels that each got.

#11346 Remove workaround to trigger cache invalidation
  .github/workflows/trigger-cache-invalidation.yml
Labels: status:merge-when-green

#11352 h2 2.1.214 (was 2.1.212)
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/build.sbt
  documentation/build.sbt
  project/Dependencies.scala
Labels: type:updates

#11355 logstash-logback-encoder 5.3 (was 5.1)
  documentation/build.sbt
Labels: type:updates

#11356 jdbc-driver 1.1.4 (was 1.0.58)
  project/Dependencies.scala
Labels: type:updates

#11354 netty-transport-native-epoll 4.1.79.Final (was 4.1.77.Final)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11359 reactive-streams 1.0.4 (was 1.0.3)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11357 mockito-core 2.28.2 (was 2.18.3)
  documentation/build.sbt
Labels: type:updates, status:merge-when-green

#11358 mockito-core 4.6.1 (was 4.5.1)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11353 okhttp 4.10.0 (was 4.9.3)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11351 jackson-databind 2.13.3 (was 2.13.2.2)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green
