Repository playframework/playframework, pull requests merged in 2023-09, with the labels that each got.

#11804 Play 2.9 highlights and migration guide
  core/play/src/main/scala/play/api/mvc/Request.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala
  documentation/manual/General.md
  documentation/manual/Home.md
  documentation/manual/gettingStarted/Installing.md
  documentation/manual/gettingStarted/Requirements.md
  documentation/manual/index.toc
  documentation/manual/releases/release29/Highlights29.md
  documentation/manual/releases/release29/migration29/Migration29.md
  documentation/manual/releases/release29/migration29/Scala3Migration.md
  documentation/manual/releases/release29/migration29/index.toc
  documentation/manual/working/javaGuide/main/akka/JavaAkka.md
  documentation/manual/working/javaGuide/main/async/JavaWebSockets.md
  documentation/manual/working/javaGuide/main/http/JavaActionsComposition.md
  documentation/manual/working/javaGuide/main/http/JavaBodyParsers.md
  documentation/manual/working/javaGuide/main/sql/JavaJPA.md
  documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md
  web/play-filters-helpers/src/main/resources/reference.conf
Labels: topic:documentation

#11952 netty-transport-native-epoll 4.1.97.Final (was 4.1.96.Final)
  project/Dependencies.scala
Labels: type:updates

#11954 hibernate-core 6.2.8.Final (was 6.2.7.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#11955 mockito-core 5.5.0 (was 5.4.0)
  documentation/build.sbt
  project/Dependencies.scala
Labels: type:updates

#11956 sbt-scalafmt 2.5.2 (was 2.5.0)
  documentation/project/plugins.sbt
Labels: type:updates

#11960 jcl-over-slf4j, jul-to-slf4j, ... 2.0.9 (was 2.0.7)
  project/Dependencies.scala
Labels: type:updates

#11957 scalafmt-core 3.7.14 (was 3.7.11)
  .git-blame-ignore-revs
  .scalafmt.conf
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/app/controllers/HomeController.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/build.sbt
  documentation/.scalafmt.conf
Labels: type:updates

#11951 h2 2.2.222 (was 2.2.220)
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/build.sbt
  documentation/build.sbt
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11959 selenium-api 4.12.1 (was 4.11.0)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11966 Clarify we will not drop Java 11 in Play 3
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/project/plugins.sbt
  documentation/manual/releases/release29/Highlights29.md
  documentation/manual/releases/release29/migration29/Migration29.md
  documentation/manual/working/commonGuide/build/sbtDependencies.md
  documentation/manual/working/javaGuide/main/akka/JavaAkka.md
  documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md
Labels: topic:documentation

#11980 Docs: Use example with idle timout larger than request timeout
  documentation/manual/working/commonGuide/configuration/SettingsAkkaHttp.md
Labels: status:merge-when-green
