Repository playframework/playframework, pull requests merged in 2023-03, with the labels that each got.

#11700 Prepare scripted tests for Scala 3
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/build.sbt.1
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/messages-fail-scala2.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/messages-fail-scala3.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/messages-fail.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/twirl-fail-2-scala2.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/twirl-fail-2-scala3.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/twirl-fail-2.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-namespace-reverse-router/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/build.sbt
Labels: scala3

#11701 Explicit `main` method needed for Scala 3
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/app/utils/JavaScriptRouterGenerator.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/app/utils/JavaScriptRouterGenerator.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-namespace-reverse-router/app/utils/JavaScriptRouterGenerator.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/app/utils/JavaScriptRouterGenerator.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/utils/JavaScriptRouterGenerator.scala
Labels: scala3

#11702 Scala 3: Can't use BeanProperty in Scala code to test Java API
  core/play-integration-test/src/it/scala/play/it/libs/JavaFormSpec.scala
  web/play-java-forms/src/test/scala/play/data/FormSpec.scala
  web/play-java-forms/src/test/scala/play/data/PartialValidationSpec.scala
Labels: scala3

#11704 Scala 3: Avoid making `AhcWSRequest` abstract
  project/BuildSettings.scala
  transport/client/play-ws/src/main/scala/play/api/libs/ws/WSRequest.scala
Labels: scala3

#11707 Scala3: No `-Xsource:3` for RoutesCompilerProject (with explanations)
  build.sbt
  project/BuildSettings.scala
Labels: scala3

#11710 Scala 3: Macro migration
  .github/workflows/build-test.yml
  core/play/src/main/scala-2/play/api/mvc/PathBindableMacros.scala
  core/play/src/main/scala-2/play/api/mvc/QueryStringBindableMacros.scala
  core/play/src/main/scala-2/play/api/mvc/macros/BinderMacros.scala
  core/play/src/main/scala-2/play/api/routing/sird/macroimpl/QueryStringParameterMacros.scala
  core/play/src/main/scala-2/play/api/routing/sird/package.scala
  core/play/src/main/scala-3/play/api/mvc/PathBindableMacros.scala
  core/play/src/main/scala-3/play/api/mvc/QueryStringBindableMacros.scala
  core/play/src/main/scala-3/play/api/mvc/macros/BinderMacros.scala
  core/play/src/main/scala-3/play/api/routing/sird/macroimpl/QueryStringParameterMacros.scala
  core/play/src/main/scala-3/play/api/routing/sird/package.scala
  core/play/src/main/scala/play/api/mvc/Binders.scala
  core/play/src/main/scala/play/api/routing/sird/QueryStringExtractors.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/sird-compiler-errors/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/sird-compiler-errors/project/BufferLogger.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/sird-compiler-errors/project/plugins.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/sird-compiler-errors/src/main/resources/application.conf
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/sird-compiler-errors/src/main/scala/controllers/HomeController.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/sird-compiler-errors/src/main/scala/router/Routes.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/sird-compiler-errors/test
  project/BuildSettings.scala
Labels: scala3

#11728 jcl-over-slf4j, jul-to-slf4j, ... 2.0.7 (was 2.0.6)
  project/Dependencies.scala
Labels: type:updates

#11730 jquery 3.6.4 (was 3.6.3)
  project/Dependencies.scala
Labels: type:updates

#11729 spring-beans, spring-context, ... 5.3.26 (was 5.3.25)
  project/Dependencies.scala
Labels: type:updates

#11718 sbt-buildinfo 0.11.0 (was 0.10.0)
  project/project/buildinfo.sbt
Labels: type:updates

#11720 sbt-native-packager 1.9.16 (was 1.9.15)
  project/plugins.sbt
Labels: type:updates

#11724 jdbc-driver 1.2.5 (was 1.2.2)
  project/Dependencies.scala
Labels: type:updates

#11723 logstash-logback-encoder 7.3 (was 7.2)
  documentation/build.sbt
Labels: type:updates

#11722 netty-transport-native-epoll 4.1.90.Final (was 4.1.89.Final)
  project/Dependencies.scala
Labels: type:updates

#11715 Add ConfigLoader implicits for java.time.Duration
  core/play-configuration/src/main/scala/play/api/Configuration.scala
  core/play-configuration/src/test/scala/play/api/ConfigurationSpec.scala
Labels: status:merge-when-green

#11737 Refactor imports for Scala 3
  core/play-integration-test/src/it/scala/play/it/ServerIntegrationSpecificationSpec.scala
  core/play-integration-test/src/it/scala/play/it/action/HeadActionSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/JavaActionCompositionSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/JavaActionSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/JavaHttpHandlerSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/assets/AssetsSpec.scala
  core/play-integration-test/src/it/scala/play/it/server/ServerReloadingSpec.scala
  core/play-integration-test/src/it/scala/play/it/test/WSEndpointSpec.scala
  web/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala
Labels: scala3
