Repository playframework/playframework, pull requests merged in 2023-04, with the labels that each got.

#11703 Scala 3: Temporary disable three scripted tests
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-downing/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-downing/test.disabled
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/test.disabled
Labels: scala3

#11738 Work around missing `akka-http` Scala 3 artifacts for tests
  build.sbt
  dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala
  project/Dependencies.scala
  project/Tasks.scala
Labels: scala3

#11740 Activate Scala 3 on CI
  .github/workflows/build-test.yml
  core/play/src/main/scala/play/core/parsers/Multipart.scala
  documentation/build.sbt
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaErrorHandling.scala
  documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaAkkaEmbeddingPlay.scala
  documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaNettyEmbeddingPlay.scala
  documentation/manual/working/scalaGuide/main/http/code/ScalaErrorHandling.scala
  project/BuildSettings.scala
  project/plugins.sbt
Labels: scala3

#11741 Avoid usage of specs2 Around
  core/play-integration-test/src/it/scala/play/it/i18n/LangSpec.scala
Labels: scala3

#11742 Add Scala 3 reserved words to routes compiler
  dev-mode/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
Labels: scala3

#11743 Enable two temporary disabled scripted tests
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-downing/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-downing/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-downing/test.disabled
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/test
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/test.disabled
Labels: scala3

#11748 Use scala.jdk converter also for Scala 3 in twirl templates
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
  project/BuildSettings.scala
Labels: scala3

#11736 Let the Java Form validator use the locale selected by Play's i18n.
  project/BuildSettings.scala
  web/play-java-forms/src/main/java/play/data/validation/ValidatorFactoryProvider.java
  web/play-java-forms/src/main/java/play/data/validation/ValidatorsComponents.java
  web/play-java-forms/src/test/scala/play/data/FormSpec.scala
Labels: status:merge-when-green

#11371 Add `resource` scheme for #11253
  core/play/src/main/java/play/controllers/AssetsComponents.java
  core/play/src/main/scala/play/api/controllers/Assets.scala
  core/play/src/main/scala/play/utils/Resources.scala
  core/play/src/test/scala/play/api/controllers/AssetsSpec.scala
  core/play/src/test/scala/play/utils/ResourcesSpec.scala
  documentation/manual/working/commonGuide/build/code/javaguide/common/build/controllers/Assets.java
  documentation/manual/working/commonGuide/build/code/scalaguide/common/build/controllers/SubProjectsAssetsBuilder.scala
  documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/dependencyinjection/controllers/Assets.java
  documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/components/CompileTimeDependencyInjection.java
  documentation/manual/working/scalaGuide/main/dependencyinjection/code/CompileTimeDependencyInjection.scala
Labels: status:merge-when-green

#11719 caffeine, jcache 3.1.6 (was 3.1.3)
  project/Dependencies.scala
  transport/client/play-ahc-ws/src/test/java/play/api/libs/ws/ahc/TestCacheEntryEventFilter.java
  transport/client/play-ahc-ws/src/test/java/play/api/libs/ws/ahc/TestCacheEntryListener.java
  transport/client/play-ahc-ws/src/test/resources/caffeine.conf
Labels: type:updates, status:merge-when-green

#10348 Refactor: replaced some deprecated / redundant logic
  core/play/src/main/scala/play/core/routing/GeneratedRouter.scala
  core/play/src/main/scala/play/core/routing/package.scala
Labels: status:merge-when-green

#11768 scala3-library 3.3.0-RC4 (was 3.3.0-RC3)
  documentation/build.sbt
Labels: type:updates

#11771 selenium-api 4.8.3 (was 4.8.1)
  project/Dependencies.scala
Labels: type:updates

#11763 sbt-mima-plugin 1.1.2 (was 1.1.1)
  project/plugins.sbt
Labels: type:updates

#11762 logback-classic 1.4.7 (was 1.4.6)
  project/Dependencies.scala
Labels: type:updates

#11765 joda-time 2.12.5 (was 2.12.2)
  project/Dependencies.scala
Labels: type:updates

#11773 spring-beans, spring-context, ... 5.3.27 (was 5.3.26)
  project/Dependencies.scala
Labels: type:updates

#11767 mockito-core 5.3.1 (was 5.2.0)
  project/Dependencies.scala
Labels: type:updates

#11764 netty-transport-native-epoll 4.1.91.Final (was 4.1.90.Final)
  project/Dependencies.scala
Labels: type:updates

#11769 scalafmt-core 3.7.3 (was 3.7.2)
  .git-blame-ignore-revs
  .scalafmt.conf
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-system-property/tests/ServerSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-downing/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/build.sbt
  documentation/.scalafmt.conf
Labels: type:updates

#11774 fix reverse routes escape with fixed param
  dev-mode/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/controllers/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes
Labels: status:merge-when-green

#11772 specs2-mock 4.20.0 (was 4.19.2)
  project/Dependencies.scala
Labels: type:updates

#11001 Clean up eliminate warnings tackle deprecations
  core/play-guice/src/main/java/play/libs/akka/BinderAccessor.java
  core/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala
  core/play-guice/src/main/scala/play/api/libs/concurrent/AkkaGuiceSupport.scala
  core/play-integration-test/src/it/scala/play/it/http/JavaRequestsSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
  core/play/src/main/scala/play/core/j/JavaResults.scala
  core/play/src/test/scala/play/api/i18n/MessagesSpec.scala
  core/play/src/test/scala/play/api/libs/TemporaryFileReaperSpec.scala
  persistence/play-jdbc/src/test/scala/play/api/db/DatabasesSpec.scala
  transport/server/play-server/src/main/scala/play/core/server/common/PathAndQueryParser.scala
  transport/server/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala
Labels: status:merge-when-green
