Repository playframework/playframework, pull requests merged in 2023-07, with the labels that each got.

#11859 sbt-header 5.10.0 (was 5.9.0)
  documentation/project/plugins.sbt
Labels: type:updates

#11864 sbt 1.9.1 (was 1.9.0)
  documentation/project/build.properties
  project/build.properties
Labels: type:updates

#11865 scalafmt-core 3.7.5 (was 3.7.3)
  .git-blame-ignore-revs
  .scalafmt.conf
  documentation/.scalafmt.conf
  documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala
  documentation/manual/working/scalaGuide/main/tests/code/database/ScalaTestingWithDatabases.scala
Labels: type:updates

#11856 logback-classic 1.4.8 (was 1.4.7)
  project/Dependencies.scala
Labels: type:updates

#11860 netty-transport-native-epoll 4.1.94.Final (was 4.1.93.Final)
  project/Dependencies.scala
Labels: type:updates

#11863 mockito-core 5.4.0 (was 5.3.1)
  documentation/build.sbt
  project/Dependencies.scala
Labels: type:updates

#11867 spring-beans, spring-context, ... 5.3.28 (was 5.3.27)
  project/Dependencies.scala
Labels: type:updates

#11868 webjars-locator-core 0.53 (was 0.52)
  project/plugins.sbt
Labels: type:updates

#11866 htmlunit-driver, selenium-api 4.10.0 (was 4.9.1)
  project/Dependencies.scala
Labels: type:updates

#11862 hibernate-core 6.2.6.Final (was 6.2.3.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#11869 sbt-jmh 0.4.5 (was 0.4.4)
  project/plugins.sbt
Labels: type:updates, status:merge-when-green

#11858 guava 32.1.1-jre (was 32.0.1-jre)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11883 Make Play compatible with akka 2.8+ / akka-http 10.5+ when using Scala 3
  dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
  documentation/manual/working/javaGuide/main/akka/JavaAkka.md
  documentation/manual/working/javaGuide/main/akka/code/javaguide.akkaupdate.sbt
  documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md
  documentation/manual/working/scalaGuide/main/akka/code/scalaguide.akkaupdate.sbt
Labels: scala3
