Repository playframework/playframework, pull requests merged in 2023-01, with the labels that each got.

#11613 sbt-twirl, twirl-api 1.6.0-RC1 (was 1.6.0-M7)
  documentation/project/plugins.sbt
Labels: type:updates, status:merge-when-green

#11619 jquery 3.6.3 (was 3.6.1)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11616 mockito-core 4.11.0 (was 4.10.0)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11615 joda-convert 2.2.3 (was 2.2.2)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11612 sbt-native-packager 1.9.13 (was 1.9.11)
  project/plugins.sbt
Labels: type:updates, status:merge-when-green

#11618 spring-beans, spring-context, ... 5.3.25 (was 5.3.24)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11614 netty-transport-native-epoll 4.1.87.Final (was 4.1.86.Final)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11631 🔄 synced file(s) with playframework/.github
  common.sbt
  documentation/common.sbt
Labels: sync

#11632 🔄 synced file(s) with playframework/.github
  common.sbt
  documentation/common.sbt
Labels: sync

#11633 Upgrade Scalafmt to latest release of `2.6.x` serias
  .git-blame-ignore-revs
  .scalafmt.conf
  cache/play-jcache/src/test/scala/play/api/libs/jcache/JCacheSpec.scala
  core/play-configuration/src/main/scala/play/api/Configuration.scala
  core/play-integration-test/src/it/scala/play/it/libs/json/JavaJsonSpec.scala
  core/play/src/main/scala/play/api/Application.scala
  core/play/src/main/scala/play/api/Logger.scala
  core/play/src/main/scala/play/api/controllers/ExternalAssets.scala
  core/play/src/main/scala/play/api/data/Forms.scala
  core/play/src/main/scala/play/api/data/package.scala
  core/play/src/main/scala/play/api/data/validation/Validation.scala
  core/play/src/main/scala/play/api/inject/Injector.scala
  core/play/src/main/scala/play/api/inject/Module.scala
  core/play/src/main/scala/play/api/libs/Comet.scala
  core/play/src/main/scala/play/api/libs/EventSource.scala
  core/play/src/main/scala/play/api/mvc/Controller.scala
  core/play/src/main/scala/play/api/mvc/Filters.scala
  core/play/src/main/scala/play/api/package.scala
  core/play/src/main/scala/play/api/routing/sird/PathExtractor.scala
  core/play/src/test/scala/play/api/mvc/TextBodyParserSpec.scala
  dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala
  documentation/.scalafmt.conf
  documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala
  documentation/manual/working/scalaGuide/main/xml/code/ScalaXmlRequests.scala
  persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
  project/BuildSettings.scala
  project/Tasks.scala
  transport/client/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSRequest.scala
  web/play-filters-helpers/src/main/scala/play/filters/cors/CORSConfig.scala
  web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
  web/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
Labels: type:updates

#11634 [2.8.x] Upgrade Scalafmt to latest release of `2.6.x` serias
  .git-blame-ignore-revs
  .scalafmt.conf
  cache/play-jcache/src/test/scala/play/api/libs/jcache/JCacheSpec.scala
  core/play-integration-test/src/it/scala/play/it/libs/json/JavaJsonSpec.scala
  core/play/src/main/scala/play/api/Application.scala
  core/play/src/main/scala/play/api/Configuration.scala
  core/play/src/main/scala/play/api/Logger.scala
  core/play/src/main/scala/play/api/controllers/ExternalAssets.scala
  core/play/src/main/scala/play/api/data/Forms.scala
  core/play/src/main/scala/play/api/data/package.scala
  core/play/src/main/scala/play/api/data/validation/Validation.scala
  core/play/src/main/scala/play/api/inject/Injector.scala
  core/play/src/main/scala/play/api/inject/Module.scala
  core/play/src/main/scala/play/api/libs/Comet.scala
  core/play/src/main/scala/play/api/libs/EventSource.scala
  core/play/src/main/scala/play/api/mvc/Controller.scala
  core/play/src/main/scala/play/api/mvc/Filters.scala
  core/play/src/main/scala/play/api/package.scala
  core/play/src/main/scala/play/api/routing/sird/PathExtractor.scala
  core/play/src/test/scala/play/api/mvc/TextBodyParserSpec.scala
  dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala
  documentation/.scalafmt.conf
  documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala
  documentation/manual/working/scalaGuide/main/xml/code/ScalaXmlRequests.scala
  persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
  project/BuildSettings.scala
  project/Tasks.scala
  transport/client/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSRequest.scala
  transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala
  web/play-filters-helpers/src/main/scala/play/filters/cors/CORSConfig.scala
  web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
  web/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
Labels: type:updates

#11638 [2.8.x] Upgrade Scalafmt to latest release of `2.7.x` serias
  .git-blame-ignore-revs
  .scalafmt.conf
  cache/play-caffeine-cache/src/main/scala/play/api/cache/caffeine/CaffeineCacheApi.scala
  cache/play-caffeine-cache/src/test/scala/play/api/cache/caffeine/CaffeineCacheApiSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/FlashCookieSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
  core/play-integration-test/src/it/scala/play/it/libs/ScalaWSSpec.scala
  core/play-integration-test/src/it/scala/play/it/mvc/HttpSpec.scala
  core/play-integration-test/src/it/scala/play/it/tools/HttpBin.scala
  core/play/src/main/scala/play/api/data/Forms.scala
  core/play/src/main/scala/play/core/formatters/Multipart.scala
  core/play/src/test/scala/views/html/helper/HelpersSpec.scala
  dev-mode/routes-compiler/src/test/scala/play/routes/compiler/templates/TemplatesSpec.scala
  dev-mode/sbt-plugin/src/test/scala/play/sbt/PlayRunHookSpec.scala
  documentation/.scalafmt.conf
  documentation/manual/working/javaGuide/code/MockJavaAction.scala
  documentation/manual/working/scalaGuide/main/json/code/ScalaJsonHttpSpec.scala
  documentation/manual/working/scalaGuide/main/tests/code/specs2/HelloWorldSpec.scala
  persistence/play-jdbc/src/test/scala/play/api/db/ConnectionPoolConfigSpec.scala
  persistence/play-jdbc/src/test/scala/play/api/db/NamedDatabaseSpec.scala
  transport/client/play-ahc-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
  transport/server/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala
  transport/server/play-server/src/test/scala/play/core/server/common/SubnetSpec.scala
  web/play-filters-helpers/src/main/scala/play/filters/csp/CSPReportActionBuilder.scala
  web/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala
  web/play-filters-helpers/src/test/scala/play/filters/headers/SecurityHeadersFilterSpec.scala
  web/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala
  web/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala
  web/play-openid/src/test/scala/play/api/libs/openid/OpenIDSpec.scala
Labels: type:updates, status:merge-when-green

#11637 Upgrade Scalafmt to latest release of `2.7.x` serias
  .git-blame-ignore-revs
  .scalafmt.conf
  build.sbt
  cache/play-caffeine-cache/src/main/scala/play/api/cache/caffeine/CaffeineCacheApi.scala
  cache/play-caffeine-cache/src/test/scala/play/api/cache/caffeine/CaffeineCacheApiSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/FlashCookieSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
  core/play-integration-test/src/it/scala/play/it/libs/ScalaWSSpec.scala
  core/play-integration-test/src/it/scala/play/it/mvc/HttpSpec.scala
  core/play-integration-test/src/it/scala/play/it/tools/HttpBin.scala
  core/play/src/main/scala/play/api/data/Forms.scala
  core/play/src/main/scala/play/core/formatters/Multipart.scala
  core/play/src/test/scala/views/html/helper/HelpersSpec.scala
  dev-mode/routes-compiler/src/test/scala/play/routes/compiler/templates/TemplatesSpec.scala
  dev-mode/sbt-plugin/src/test/scala/play/sbt/PlayRunHookSpec.scala
  documentation/.scalafmt.conf
  documentation/manual/working/javaGuide/code/MockJavaAction.scala
  documentation/manual/working/scalaGuide/main/json/code/ScalaJsonHttpSpec.scala
  documentation/manual/working/scalaGuide/main/tests/code/specs2/HelloWorldSpec.scala
  persistence/play-jdbc/src/test/scala/play/api/db/ConnectionPoolConfigSpec.scala
  persistence/play-jdbc/src/test/scala/play/api/db/NamedDatabaseSpec.scala
  transport/client/play-ahc-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
  transport/server/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala
  transport/server/play-server/src/test/scala/play/core/server/common/SubnetSpec.scala
  web/play-filters-helpers/src/main/scala/play/filters/csp/CSPReportActionBuilder.scala
  web/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala
  web/play-filters-helpers/src/test/scala/play/filters/headers/SecurityHeadersFilterSpec.scala
  web/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala
  web/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala
  web/play-openid/src/test/scala/play/api/libs/openid/OpenIDSpec.scala
Labels: type:updates, status:merge-when-green
