Repository playframework/playframework, pull requests merged in 2023-08, with the labels that each got.

#11904 jquery 3.7.0 (was 3.6.4)
  project/Dependencies.scala
Labels: type:updates

#11903 spring-beans, spring-context, ... 5.3.29 (was 5.3.28)
  project/Dependencies.scala
Labels: type:updates

#11901 scalafmt-core 3.7.11 (was 3.7.5)
  .git-blame-ignore-revs
  .scalafmt.conf
  documentation/.scalafmt.conf
  documentation/manual/working/javaGuide/main/akka/code/javaguide.akkaupdate.sbt
  documentation/manual/working/scalaGuide/main/akka/code/scalaguide.akkaupdate.sbt
Labels: type:updates

#11900 sbt 1.9.3 (was 1.9.2)
  documentation/project/build.properties
  project/build.properties
Labels: type:updates

#11899 hibernate-core 6.2.7.Final (was 6.2.6.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#11898 jdbc-driver 1.2.8 (was 1.2.7)
  project/Dependencies.scala
Labels: type:updates

#11896 netty-reactive-streams-http 2.0.9 (was 2.0.8)
  project/Dependencies.scala
Labels: type:updates

#11895 sbt-mima-plugin 1.1.3 (was 1.1.2)
  project/plugins.sbt
Labels: type:updates

#11892 guava 32.1.2-jre (was 32.1.1-jre)
  project/Dependencies.scala
Labels: type:updates

#11891 caffeine, jcache 3.1.7 (was 3.1.6)
  project/Dependencies.scala
Labels: type:updates

#11894 h2 2.2.220 (was 2.1.214)
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/build.sbt
  documentation/build.sbt
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11897 netty-transport-native-epoll 4.1.96.Final (was 4.1.94.Final)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11902 selenium-api 4.11.0 (was 4.10.0)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11893 jimfs 1.3.0 (was 1.2)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#11910 Fix missed ContextInitializer#configureByResource
  core/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
  project/Dependencies.scala
Labels: status:merge-when-green

#11923 Add sbt-svelte to ModuleDirectory.md
  documentation/manual/ModuleDirectory.md
Labels: status:merge-when-green

#11924 Fix link in docs
  documentation/manual/working/scalaGuide/main/http/ScalaActionsComposition.md
Labels: topic:documentation

#11929 Avoid unapply because we mix Scala 3 and Scala 2.13 artifacts when using akka(-http)
  core/play-streams/src/main/scala/play/api/libs/streams/ActorFlow.scala
Labels: scala3
