Repository playframework/playframework, pull requests merged in 2023-05, with the labels that each got.

#11770 fluentlenium 6.0 (switched to io from org), selenium + htmlunit-driver 4.9.0
  core/play/src/main/java/play/libs/XML.java
  project/BuildSettings.scala
  project/Dependencies.scala
  testkit/play-test/src/main/java/play/test/TestBrowser.java
  testkit/play-test/src/main/scala/play/api/test/Selenium.scala
Labels: type:updates, status:merge-when-green

#11813 sbt 1.9.0-RC3
  .github/workflows/build-test.yml
  documentation/manual/hacking/Translations.md
  documentation/manual/releases/release29/migration29/Migration29.md
  documentation/project/build.properties
  project/build.properties
Labels: status:merge-when-green

#11831 htmlunit-driver, selenium-api 4.9.1 (was 4.9.0)
  project/Dependencies.scala
Labels: type:updates

#11829 jdbc-driver 1.2.7 (was 1.2.6)
  project/Dependencies.scala
Labels: type:updates

#11828 netty-transport-native-epoll 4.1.93.Final (was 4.1.91.Final)
  project/Dependencies.scala
Labels: type:updates

#11820 jackson-databind 2.14.3 (was 2.14.2)
  project/Dependencies.scala
Labels: type:updates

#11821 sbt-ci-release 1.5.12 (was 1.5.11)
  project/plugins.sbt
Labels: type:updates

#11825 okhttp 4.11.0 (was 4.10.0)
  project/Dependencies.scala
Labels: type:updates
