Repository playframework/playframework, pull requests merged in 2023-11, with the labels that each got.

#12196 Upgrade sbt-web to really fix #12187
  project/Dependencies.scala
Labels: status:merge-when-green

#12197 [2.9.x] Upgrade sbt-web to really fix #12187
  project/Dependencies.scala
Labels: status:merge-when-green

#12199 Fix headers check for Play OpenID module
  build.sbt
Labels: status:merge-when-green

#12201 Add suffix to coursier cache key for publish job
  .github/workflows/publish.yml
Labels: status:merge-when-green

#12212 Migration guide: Dispatchers defined directly in the `akka.*` config won’t load automatically anymore
  documentation/manual/releases/release29/migration29/Migration29.md
Labels: topic:documentation

#12222 Patch updates
  .git-blame-ignore-revs
  .scalafmt.conf
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-pekko-http/project/plugins.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/pekko-fork-join-pool/build.sbt
  documentation/.scalafmt.conf
  documentation/project/plugins.sbt
  project/Dependencies.scala
  project/plugins.sbt
Labels: type:updates

#12217 netty-transport-native-epoll 4.1.101.Final (was 4.1.100.Final)
  project/Dependencies.scala
Labels: type:updates
