Repository playframework/playframework, pull requests merged in 2023-12, with the labels that each got.

#12249 Patch updates
  .scalafmt.conf
  documentation/.scalafmt.conf
  documentation/project/plugins.sbt
  project/Dependencies.scala
  project/plugins.sbt
Labels: type:updates

#12246 [2.9.x] hibernate-core 6.3.2.Final (was 6.3.1.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#12244 [2.9.x] netty-transport-native-epoll 4.1.101.Final (was 4.1.100.Final)
  project/Dependencies.scala
Labels: type:updates

#12233 [2.8.x] netty-transport-native-epoll 4.1.101.Final (was 4.1.100.Final)
  project/Dependencies.scala
Labels: type:updates

#12267 Support CSP nonce in Comet helpers
  core/play-java/src/main/java/play/libs/Comet.java
  core/play/src/main/scala/play/api/libs/Comet.scala
Labels: status:merge-when-green

#12162 update `play-stack` image in doc
  documentation/manual/tutorial/HelloWorldTutorial.md
  documentation/manual/tutorial/images/play-stack.png
  documentation/manual/tutorial/images/play-stack.svg
Labels: topic:documentation
