Repository playframework/playframework, pull requests merged in 2023-02, with the labels that each got.

#11645 No scala-reflect for Scala 3
  project/Dependencies.scala
Labels: scala3

#11646 Keep default for crossScalaVersion PlayNonCrossBuiltProject
  project/BuildSettings.scala
Labels: scala3

#11647 replace specs2-mockito with vanilla mockito
  build.sbt
  cache/play-caffeine-cache/src/test/scala/play/api/cache/caffeine/CaffeineCacheApiSpec.scala
  core/play-integration-test/src/it/scala/play/it/http/JavaRequestsSpec.scala
  core/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
  documentation/manual/releases/release29/migration29/Migration29.md
  documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWSSpec.scala
  documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala
  documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md
  documentation/manual/working/scalaGuide/main/tests/code/models/UserSpec.scala
  documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleMockitoSpec.scala
  documentation/manual/working/scalaGuide/main/tests/code/specs2/UserServiceSpec.scala
  project/Dependencies.scala
  testkit/play-test/src/test/scala/play/api/test/InjectingSpec.scala
  transport/client/play-ahc-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
  transport/server/play-server/src/test/scala/play/core/server/ssl/ServerSSLEngineSpec.scala
  web/play-openid/src/test/scala/play/api/libs/openid/DiscoveryClientSpec.scala
  web/play-openid/src/test/scala/play/api/libs/openid/OpenIDSpec.scala
  web/play-openid/src/test/scala/play/api/libs/openid/WsMock.scala
Labels: scala3

#11672 Deprecate TypedMap symbols and replace with named functions
  core/play/src/main/java/play/libs/typedmap/TypedMap.java
  core/play/src/main/java/play/mvc/Http.java
  core/play/src/main/scala/play/api/libs/typedmap/TypedMap.scala
  core/play/src/main/scala/play/api/mvc/Request.scala
  core/play/src/main/scala/play/api/mvc/RequestHeader.scala
  core/play/src/main/scala/play/api/mvc/Results.scala
  core/play/src/main/scala/play/api/mvc/request/RequestFactory.scala
  core/play/src/main/scala/play/core/j/JavaHelpers.scala
  core/play/src/test/scala/play/core/test/Fakes.scala
  project/BuildSettings.scala
  testkit/play-test/src/main/scala/play/api/test/Fakes.scala
Labels: status:merge-when-green

#11687 sbt-jmh 0.4.4 (was 0.4.3)
  project/plugins.sbt
Labels: type:updates

#11685 selenium-api 4.8.1 (was 4.7.2)
  project/Dependencies.scala
Labels: type:updates

#11677 sbt-assembly 2.1.1 (was 2.1.0)
  documentation/project/plugins.sbt
Labels: type:updates

#11678 jackson-databind 2.14.2 (was 2.14.1)
  project/Dependencies.scala
Labels: type:updates

#11680 sbt-native-packager 1.9.15 (was 1.9.13)
  project/plugins.sbt
Labels: type:updates

#11679 caffeine, jcache 3.1.3 (was 3.1.2)
  project/Dependencies.scala
Labels: type:updates

#11681 netty-transport-native-epoll 4.1.89.Final (was 4.1.87.Final)
  project/Dependencies.scala
Labels: type:updates

#11682 jdbc-driver 1.2.2 (was 1.2.1)
  project/Dependencies.scala
Labels: type:updates

#11683 mockito-core 5.1.1 (was 4.11.0)
  project/Dependencies.scala
Labels: type:updates
