Repository playframework/playframework, pull requests merged in 2024-04, with the labels that each got.

#12491 [2.9.x] sbt-buildinfo 0.12.0 (was 0.11.0)
  project/project/buildinfo.sbt
Labels: type:updates

#12509 [3.0.x] sbt-buildinfo 0.12.0 (was 0.11.0)
  project/project/buildinfo.sbt
Labels: type:updates

#12539 [2.9.x] hibernate-core 6.4.5.Final (was 6.4.4.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#12505 [2.8.x] netty-codec-http, netty-handler, ... 4.1.109.Final (was 4.1.107.Final)
  project/Dependencies.scala
Labels: type:updates

#12538 [2.9.x] netty-codec-http, netty-handler, ... 4.1.109.Final (was 4.1.107.Final)
  project/Dependencies.scala
Labels: type:updates

#12512 [3.0.x] netty-codec-http, netty-handler, ... 4.1.109.Final (was 4.1.107.Final)
  project/Dependencies.scala
Labels: type:updates

#12499 [2.9.x] webjars-locator-core 0.58 (was 0.56)
  project/plugins.sbt
Labels: type:updates

#12516 [3.0.x] webjars-locator-core 0.58 (was 0.56)
  project/plugins.sbt
Labels: type:updates

#12500 [2.9.x] Patch updates
  .git-blame-ignore-revs
  .scalafmt.conf
  core/play-integration-test/src/test/scala/play/it/http/parsingdeferred/DeferredBodyParsingSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
  documentation/.scalafmt.conf
  project/Dependencies.scala
Labels: type:updates

#12517 [3.0.x] Patch updates
  .git-blame-ignore-revs
  .scalafmt.conf
  core/play-integration-test/src/test/scala/play/it/http/parsingdeferred/DeferredBodyParsingSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
  documentation/.scalafmt.conf
  project/Dependencies.scala
Labels: type:updates

#12562 [Gradle] Fix `playRun` classpath when project depends on a pure java project
  dev-mode/gradle-plugin/src/main/java/play/gradle/plugin/PlayRunPlugin.java
  dev-mode/gradle-plugin/src/test/java/play/gradle/PlayRunPluginTest.java
Labels: type:defect, status:merge-when-green

#12563 Document flag to use self-signed certificates in DEV and when staging
  documentation/manual/releases/release29/migration29/Migration29.md
  documentation/manual/working/commonGuide/production/ConfiguringHttps.md
Labels: topic:documentation
