Repository playframework/playframework, pull requests merged in 2024-06, with the labels that each got.

#12664 simplify PartialFunction compose
  core/play/src/main/scala/play/api/routing/Router.scala
Labels: status:merge-when-green

#12707 [3.0.x] netty-codec-http, netty-handler, ... 4.1.110.Final (was 4.1.109.Final)
  project/Dependencies.scala
Labels: type:updates

#12708 [3.0.x] sbt-pekko-version-check 0.0.5 (was 0.0.3)
  project/plugins.sbt
Labels: type:updates

#12709 [3.0.x] hibernate-core 6.5.2.Final (was 6.5.0.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#12710 [3.0.x] Patch updates
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#12733 [Gradle] Use `processIsolation` instead of `classLoaderIsolation`
  dev-mode/gradle-plugin/build.gradle.kts
  dev-mode/gradle-plugin/settings.gradle.kts
  dev-mode/gradle-plugin/src/main/java/play/gradle/task/RoutesCompile.java
Labels: status:merge-when-green

#12734 Temporary remove `~run` from docs because it's broken since long time
  documentation/manual/gettingStarted/IDE.md
  documentation/manual/gettingStarted/PlayConsole.md
Labels: topic:documentation

#12771 [Gradle] Template imports for Java project should be minimal
  dev-mode/gradle-plugin/src/main/java/play/gradle/plugin/PlayPlugin.java
Labels: status:merge-when-green

#12788 Add route modifiers on RedirectHttpsFilter. Resolves #12776
  documentation/manual/working/commonGuide/filters/RedirectHttpsFilter.md
  documentation/manual/working/commonGuide/filters/code/CommonRouting.scala
  documentation/manual/working/commonGuide/filters/code/commonguide.http.routing.routes
  project/BuildSettings.scala
  web/play-filters-helpers/src/main/resources/reference.conf
  web/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala
  web/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala
Labels: status:merge-when-green
