Repository playframework/playframework, pull requests merged in 2024-02, with the labels that each got.

#12390 [2.9.x] scalafmt-core 3.8.0 (was 3.7.17)
  .scalafmt.conf
  documentation/.scalafmt.conf
Labels: type:updates

#12370 scalafmt-core 3.8.0 (was 3.7.17)
  .scalafmt.conf
  documentation/.scalafmt.conf
Labels: type:updates

#12387 [2.9.x] netty-transport-native-epoll 4.1.107.Final (was 4.1.104.Final)
  project/Dependencies.scala
Labels: type:updates

#12367 netty-transport-native-epoll 4.1.107.Final (was 4.1.104.Final)
  project/Dependencies.scala
Labels: type:updates

#12388 [2.9.x] hibernate-core 6.4.4.Final (was 6.4.1.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#12368 hibernate-core 6.4.4.Final (was 6.4.1.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#12372 Patch updates
  project/Dependencies.scala
Labels: type:updates

#12378 [2.8.x] netty-transport-native-epoll 4.1.107.Final (was 4.1.104.Final)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#12270 Add option to disable JavaScript routers
  dev-mode/play-docs-sbt-plugin/src/main/scala/org/playframework/docs/sbtplugin/PlayDocsPlugin.scala
  dev-mode/play-routes-compiler/src/main/scala/play/routes/compiler/RoutesCompiler.scala
  dev-mode/play-routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala
  dev-mode/play-routes-compiler/src/main/twirl/play/routes/compiler/static/javaWrappers.scala.twirl
  dev-mode/play-routes-compiler/src/test/scala/play/routes/compiler/RoutesCompilerSpec.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala
Labels: status:merge-when-green

#12412 [2.9.x] Fix typo in docs
  documentation/manual/gettingStarted/LearningExamples.md
Labels: topic:documentation

#12413 Fix typo in docs
  documentation/manual/gettingStarted/LearningExamples.md
Labels: topic:documentation

#12434 Build Play with Java 17
  .github/release-drafts/increasing-minor-version.yml
  .github/workflows/build-test.yml
  .github/workflows/publish.yml
  core/play-java/src/main/java/play/libs/Time.java
  core/play/src/main/scala/play/utils/UriEncoding.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
  documentation/build.sbt
  documentation/manual/gettingStarted/Installing.md
  documentation/manual/gettingStarted/Requirements.md
  documentation/manual/working/commonGuide/configuration/ThreadPools.md
  documentation/manual/working/commonGuide/configuration/WsSSL.md
  documentation/manual/working/commonGuide/filters/CspFilter.md
  documentation/manual/working/commonGuide/filters/GzipEncoding.md
  documentation/manual/working/commonGuide/production/ConfiguringHttps.md
  documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
  documentation/manual/working/javaGuide/main/async/JavaAsync.md
  documentation/manual/working/javaGuide/main/forms/JavaForms.md
  documentation/manual/working/javaGuide/main/i18n/JavaI18N.md
  documentation/manual/working/javaGuide/main/ws/JavaWS.md
  documentation/manual/working/scalaGuide/main/i18n/ScalaI18N.md
  documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
  project/BuildSettings.scala
  project/Docs.scala
  project/PlayLibraryBase.scala
  project/PlaySbtBuildBase.scala
  transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
Labels: not backported to 2.9.x

#11686 Upgrade spring dependencies to v6, hibernate-validator to v7, switch to jakarta namespace
  documentation/manual/working/javaGuide/main/forms/JavaForms.md
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/customconstraint/nopayload/ValidateWithDB.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/customconstraint/nopayload/ValidateWithDBValidator.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/customconstraint/payload/ValidateWithDB.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/customconstraint/payload/ValidateWithDBValidator.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/groups/PartialUserForm.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/groupsequence/OrderedChecks.java
  documentation/manual/working/javaGuide/main/sql/JavaJPA.md
  project/BuildSettings.scala
  project/Dependencies.scala
  web/play-java-forms/src/main/java/play/data/DynamicForm.java
  web/play-java-forms/src/main/java/play/data/Form.java
  web/play-java-forms/src/main/java/play/data/FormFactory.java
  web/play-java-forms/src/main/java/play/data/validation/Constraints.java
  web/play-java-forms/src/main/java/play/data/validation/DefaultConstraintValidatorFactory.java
  web/play-java-forms/src/main/java/play/data/validation/MappedConstraintValidatorFactory.java
  web/play-java-forms/src/main/java/play/data/validation/ValidatorFactoryProvider.java
  web/play-java-forms/src/main/java/play/data/validation/ValidatorProvider.java
  web/play-java-forms/src/main/java/play/data/validation/ValidatorsComponents.java
  web/play-java-forms/src/main/java/play/data/validation/ValidatorsModule.java
  web/play-java-forms/src/test/java/play/data/OrderedChecks.java
  web/play-java-forms/src/test/java/play/data/RedValidator.java
  web/play-java-forms/src/test/java/play/data/SomeUser.java
  web/play-java-forms/src/test/java/play/data/ValidateRed.java
  web/play-java-forms/src/test/java/play/data/validation/TestConstraints.java
  web/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java
  web/play-java-forms/src/test/scala/play/data/FormSpec.scala
Labels: type:updates, topic:jdk-next, status:merge-when-green, not backported to 2.9.x

#12216 HikariCP 5.1.0 (was 5.0.1)
  project/Dependencies.scala
Labels: type:updates

#12435 Update ModuleDirectory.md - Update Silhouette location
  documentation/manual/ModuleDirectory.md
Labels: topic:documentation

#12369 mockito-core 5.10.0 (was 5.6.0)
  documentation/build.sbt
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#12438 derby, derbytools 10.16.1.1 (was 10.15.2.0)
  .github/scala-steward.conf
  project/Dependencies.scala
Labels: not backported to 2.9.x

#11861 logstash-logback-encoder 7.4 (was 7.3)
  documentation/build.sbt
Labels: type:updates, status:merge-when-green, not backported to 2.9.x

#12298 guava 33.0.0-jre (was 32.1.3-jre)
  project/Dependencies.scala
Labels: type:updates, not backported to 2.9.x

#12184 Migrate from Hamcrest/FEST-Assert to AssertJ (test sources)
  build.sbt
  cache/play-caffeine-cache/src/test/java/play/cache/caffeine/NamedCaffeineCacheSpec.java
  core/play-guice/src/test/java/play/inject/guice/GuiceApplicationBuilderTest.java
  core/play-guice/src/test/java/play/inject/guice/GuiceApplicationLoaderTest.java
  core/play-guice/src/test/java/play/inject/guice/GuiceInjectorBuilderTest.java
  core/play-integration-test/src/test/java/play/BuiltInComponentsFromContextTest.java
  core/play-integration-test/src/test/java/play/routing/AbstractRoutingDslTest.java
  core/play-java/src/test/java/play/mvc/HttpTest.java
  core/play-java/src/test/java/play/mvc/RequestBuilderTest.java
  core/play/src/test/java/play/i18n/MessagesTest.java
  core/play/src/test/java/play/libs/concurrent/FuturesTest.java
  persistence/play-java-jdbc/src/test/java/play/db/DatabaseTest.java
  persistence/play-java-jdbc/src/test/java/play/db/NamedDatabaseTest.java
  persistence/play-java-jpa/src/test/java/play/db/jpa/JPAApiTest.java
  project/Dependencies.scala
  testkit/play-test/src/test/java/play/test/HelpersTest.java
  testkit/play-test/src/test/java/play/test/WithApplicationOverrideTest.java
  testkit/play-test/src/test/java/play/test/WithBrowserTest.java
  web/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java
Labels: status:merge-when-green

#12185 Migrate from Hamcrest to AssertJ (docs)
  documentation/build.sbt
  documentation/manual/working/commonGuide/configuration/code/detailedtopics/ThreadPoolsJava.java
  documentation/manual/working/commonGuide/pekko/code/javaguide/pekko/typed/PekkoTypedDocTest.java
  documentation/manual/working/javaGuide/advanced/embedding/code/javaguide/advanced/embedding/JavaEmbeddingPlay.java
  documentation/manual/working/javaGuide/advanced/extending/code/javaguide/advanced/extending/JavaExtendingPlay.java
  documentation/manual/working/javaGuide/advanced/routing/code/javaguide/advanced/routing/JavaRoutingDsl.java
  documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaAsync.java
  documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaComet.java
  documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaStream.java
  documentation/manual/working/javaGuide/main/cache/code/javaguide/cache/JavaCache.java
  documentation/manual/working/javaGuide/main/cache/code/javaguide/ehcache/JavaEhCache.java
  documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/JavaDependencyInjection.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaCsrf.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
  documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaFormsDirectFieldAccess.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActions.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaBodyParsers.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaContentNegotiation.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java
  documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java
  documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/JavaI18N.java
  documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java
  documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaLogging.java
  documentation/manual/working/javaGuide/main/pekko/code/javaguide/pekko/JavaPekko.java
  documentation/manual/working/javaGuide/main/tests/JavaTest.md
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/AssertJTest.java
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/GitHubClientTest.java
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/JavaTestingWebServiceClients.java
  documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/JavaTestingWithDatabases.java
  documentation/manual/working/javaGuide/main/tests/code/tests/guice/JavaGuiceApplicationBuilderTest.java
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
  documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java
Labels: status:merge-when-green, not backported to 2.9.x

#12454 [3.0.x] Patch updates
  project/Dependencies.scala
Labels: type:updates
