Repository playframework/playframework, pull requests merged in 2024-10, with the labels that each got.

#12884 [2.9.x] hibernate-core 6.6.1.Final (was 6.6.0.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#12879 hibernate-core 6.5.3.Final (was 6.5.2.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#12877 logstash-logback-encoder 8.0 (was 7.4)
  documentation/build.sbt
Labels: type:updates

#12876 joda-time 2.13.0 (was 2.12.7)
  project/Dependencies.scala
Labels: type:updates

#12880 mockito-core 5.14.0 (was 5.12.0)
  documentation/build.sbt
  project/Dependencies.scala
Labels: type:updates

#12874 sbt-ci-release 1.6.1 (was 1.5.12)
  project/plugins.sbt
Labels: type:updates

#12882 Patch updates
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/build.sbt
  documentation/build.sbt
  project/Dependencies.scala
  project/plugins.sbt
Labels: type:updates, status:merge-when-green

#12885 [2.9.x] Patch updates
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/build.sbt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-multiple-databases/build.sbt
  documentation/build.sbt
  project/Dependencies.scala
  project/plugins.sbt
Labels: type:updates, status:merge-when-green

#12911 [Gradle] Failed routes compilation should fail gradle task
  dev-mode/gradle-plugin/src/main/java/play/gradle/internal/RoutesCompileAction.java
Labels: type:defect
