Repository playframework/playframework, pull requests merged in 2025-01, with the labels that each got.

#13037 [2.9.x] hibernate-core 6.6.4.Final (was 6.6.3.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#13038 [2.9.x] Patch updates
  .github/workflows/build-test.yml
  documentation/project/build.properties
  project/Dependencies.scala
  project/Versions.scala
  project/build.properties
  project/plugins.sbt
Labels: type:updates, status:merge-when-green

#13078 [3.0.x] hibernate-core 6.6.5.Final (was 6.6.4.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#13099 Add timeout to scripted tests to fix failing it locally
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/test
Labels: ci:skip-tests, ci:skip-docs-tests

#13021 Scala 3.3.5
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-sub.asset-changes-sub-1.0-SNAPSHOT.scala3.jar.txt
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/assets-pipeline/expected-assets-pipeline.assets-pipeline-0.1.0-SNAPSHOT-sans-externalized.scala3.jar.txt
  project/Versions.scala
Labels: ci:skip-tests, ci:skip-docs-tests
