Repository playframework/playframework, pull requests merged in 2025-09, with the labels that each got.

#13498 [3.0.x] sbt-pekko-version-check 0.0.8 (was 0.0.7)
  project/plugins.sbt
Labels: type:updates

#13515 [2.9.x] Patch updates
  .github/workflows/build-test.yml
  documentation/project/build.properties
  project/Versions.scala
  project/build.properties
Labels: type:updates

#13540 [2.9.x] sbt-header 5.11.0 (was 5.10.0)
  documentation/build.sbt
  documentation/project/plugins.sbt
  project/BuildSettings.scala
  project/plugins.sbt
Labels: type:updates

#13544 [2.9.x] hibernate-core 6.6.29.Final (was 6.6.28.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#13549 Remove Watched reference in PlayRun
  dev-mode/sbt-plugin/src/main/scala/sbt/PlayRun.scala
Labels: type:breaks-compatibility

#13550 [2.9.x] Patch updates
  .git-blame-ignore-revs
  .scalafmt.conf
  core/play/src/test/scala/play/libs/XMLSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-cache/build.sbt
  documentation/.scalafmt.conf
Labels: type:updates

#13553 sbt 2 runTask compatibility
  dev-mode/sbt-plugin/src/main/scala-2.12/play/sbt/PluginCompat.scala
  dev-mode/sbt-plugin/src/main/scala-3/play/sbt/PluginCompat.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala
  dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
  dev-mode/sbt-plugin/src/main/scala/sbt/PlayRun.scala
Labels: status:merge-when-green

#13567 [2.9.x] hibernate-core 6.6.30.Final (was 6.6.29.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#13569 [3.0.x] hibernate-core 6.6.30.Final (was 6.6.29.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#13568 [2.9.x] sbt-jmh 0.4.8 (was 0.4.7)
  project/plugins.sbt
Labels: type:updates

#13570 [3.0.x] sbt-jmh 0.4.8 (was 0.4.7)
  project/plugins.sbt
Labels: type:updates
