Repository playframework/playframework, pull requests merged in 2025-03, with the labels that each got.

#13180 [2.9.x] Patch updates
  .github/workflows/build-test.yml
  .scalafmt.conf
  documentation/.scalafmt.conf
  documentation/project/build.properties
  project/Versions.scala
  project/build.properties
Labels: type:updates

#12986 HikariCP 6.2.1 (was 6.1.0)
  persistence/play-jdbc/src/main/resources/reference.conf
  project/Dependencies.scala
Labels: status:merge-when-green

#13205 Fix Heroku deprecated toolbelt URL on ProductionHeroku.md
  documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
Labels: status:merge-when-green

#12977 Fix `JavaHelpers.updateRequestWithUri`
  core/play-java/src/test/java/play/mvc/RequestBuilderTest.java
  core/play/src/main/scala/play/core/j/JavaHelpers.scala
Labels: type:defect

#13215 [3.0.x] hibernate-core 6.6.11.Final (was 6.6.10.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#13216 [3.0.x] Patch updates
  .github/workflows/build-test.yml
  .scalafmt.conf
  documentation/.scalafmt.conf
  documentation/project/build.properties
  project/Dependencies.scala
  project/Versions.scala
  project/build.properties
Labels: type:updates

#13224 Fix Renovate to update Gradle Wrapper correctly
  .github/renovate.json
  dev-mode/gradle-plugin/build.gradle.kts
Labels: status:merge-when-green
