Repository playframework/playframework, pull requests merged in 2025-07, with the labels that each got.

#13389 [2.9.x] hibernate-core 6.6.20.Final (was 6.6.19.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#13391 [3.0.x] hibernate-core 6.6.20.Final (was 6.6.19.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#13392 [3.0.x] Patch updates
  .github/workflows/build-test.yml
  documentation/project/build.properties
  project/Versions.scala
  project/build.properties
Labels: type:updates

#13402 [2.9.x] hibernate-core 6.6.21.Final (was 6.6.20.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#13404 [3.0.x] hibernate-core 6.6.21.Final (was 6.6.20.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#13413 Make sure Java's Session and Flash always exists even if empty req attrs
  core/play-java/src/test/java/play/mvc/AttributesTest.java
  core/play/src/main/java/play/mvc/Http.java
Labels: status:merge-when-green

#13420 [2.9.x] netty-codec-http, netty-handler, ... 4.1.123.Final (was 4.1.122.Final)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#13421 [3.0.x] netty-codec-http, netty-handler, ... 4.1.123.Final (was 4.1.122.Final)
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green

#13429 [3.0.x] hibernate-core 6.6.22.Final (was 6.6.21.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates, status:merge-when-green
