Repository playframework/playframework, pull requests merged in 2025-02, with the labels that each got.

#13035 Add example and fix doc for asynchronous accepting `WebSocket`
  documentation/manual/working/javaGuide/main/async/JavaWebSockets.md
  documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaWebSockets.java
Labels: topic:documentation

#13009 Fix generated router with param `req`
  dev-mode/play-routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
  dev-mode/play-routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/controllers/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes
Labels: type:defect

#13103 [2.9.x] hibernate-core 6.6.6.Final (was 6.6.4.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates

#13012 Add `JavascriptLiteral` for a few missed types
  core/play/src/main/scala/play/api/mvc/Binders.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/controllers/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/utils/JavaScriptRouterGenerator.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes
Labels: type:defect, status:merge-when-green

#12972 Add path binder for `Short`
  core/play/src/main/scala/play/api/mvc/Binders.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/controllers/Application.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
Labels: status:merge-when-green

#12995 Fix reverse router for `Optional[Int|Long|Double]` type of query param
  core/play/src/main/scala/play/api/mvc/Binders.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
Labels: type:defect, status:merge-when-green

#12982 Fix encoding a value of `Char` query param for reverse router
  core/play/src/main/scala/play/api/mvc/Binders.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
Labels: type:defect, status:merge-when-green

#12983 Fix encoding a key of `Boolean` query param for JavaScript reverse router
  core/play/src/main/scala/play/api/mvc/Binders.scala
  core/play/src/test/scala/play/api/mvc/BindersSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/assets/JavaScriptRouterSpec.js
Labels: type:defect, status:merge-when-green

#13039 Avoid error at shutdown if tmpdir is not writeable but was not used in the first place
  core/play/src/main/scala/play/api/libs/Files.scala
Labels: status:merge-when-green

#13119 Add default value to Java Short route param (forgotten in #13012)
  dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes
Labels: ci:skip-tests, ci:skip-docs-tests

#12892 Updates Custom Field Constructor Documentation
  documentation/manual/working/scalaGuide/main/forms/ScalaCustomFieldConstructors.md
Labels: topic:documentation, status:merge-when-green

#12896 Eager bindings docs clarification
  documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md
  documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
Labels: topic:documentation, status:merge-when-green

#12895 Documentation Update: Asset timestamp handling with sbt
  documentation/manual/working/commonGuide/assets/AssetsOverview.md
Labels: topic:documentation, status:merge-when-green

#13014 Documentation update: Add VSCode and url fixes to IDE page
  documentation/manual/gettingStarted/IDE.md
Labels: topic:documentation, status:merge-when-green

#13136 [3.0.x] Patch updates
  .scalafmt.conf
  documentation/.scalafmt.conf
  project/Versions.scala
  project/plugins.sbt
Labels: type:updates

#13134 [3.0.x] netty-codec-http, netty-handler, ... 4.1.118.Final (was 4.1.117.Final)
  project/Dependencies.scala
Labels: type:updates

#13135 [3.0.x] hibernate-core 6.6.8.Final (was 6.6.5.Final)
  documentation/manual/working/commonGuide/build/code/dependencies.sbt
  documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
  project/Dependencies.scala
Labels: type:updates
